### ISSUE TITLE
VisualVM hangs

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#101]
Version 1.4.1

This might be related to https://github.com/oracle/visualvm/issues/64

Sometimes I find VisualVM using 100% of 1 CPU core, stuck in an endless loop. The GUI is non-responsive and must be killed. I don't have repro steps but I am attaching a thread dump and the contents of messages.log for your review.
[messages.log](https://github.com/oracle/visualvm/files/2259130/messages.log)
[thread-dump.txt](https://github.com/oracle/visualvm/files/2259132/thread-dump.txt)

**Comment by jisedlac** [comment]
Based on both the thread dump and logfile, the Marlin rendering engine (https://github.com/bourgesl/marlin-renderer) is busy rendering the VisualVM charts:

java.lang.Thread.State: RUNNABLE
	at sun.java2d.marlin.DDasher.lineTo(java.desktop@10.0.2/DDasher.java:372)

org.netbeans.core.CLIOptions2$EQStuck: GUI is not responsive
	at java.desktop@10.0.2/sun.java2d.marlin.DRenderer.lineTo(DRenderer.java:683)

It seems to be bug in Marlin, the problem doesn't happen with Oracle JDK / OpenJDK. You should file a bug for Marlin and don't use it with VisualVM until fixed.

**Comment by cowwoc** [comment]
@jisedlac 

> It seems to be bug in Marlin, the problem doesn't happen with Oracle JDK / OpenJDK. You should file a bug for Marlin and don't use it with VisualVM until fixed.

What do you mean? I am running Oracle JDK 10.0.2 under Windows 10. I never installed Marlin. If this is a bug with Marlin version that is packed with the JDK, isn't Oracle responsible for chasing this down?

PS: I have never seen this bug outside of using VisualVM.

**Comment by cowwoc** [comment]
PS2: How do we know that VisualVM isn't at fault? Meaning, maybe VisualVM has sent an extremely heavy workload to Marin? (like rendering a billion lines)

**Comment by bourgesl** [comment]
Hi,
Stack traces indicates that jvisualvm chart overlay is causing a huge work to draw a dashed line:
at java.desktop@10.0.2/sun.java2d.SunGraphics2D.drawLine(SunGraphics2D.java:2235)
	at com.sun.tools.visualvm.charts.xy.XYSelectionOverlay.paint(XYSelectionOverlay.java:137)
	at java.desktop@10.0.2/javax.swing.JComponent.paintChildren(JComponent.java:907)

Any idea what is causing this situation: a very (too) long line, maybe wrong viewport size ?

 In jdk10, Marlin 0.8.2 clipping does not clip dashed lines.
 I implemented efficient dash clipping in Marlin 0.9.2 coming in jdk11 or as a jdk10 patch:
https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_2_jdk9

Could you give a try ? And explain me when the problem happens ?

**Comment by cowwoc** [comment]
@bourgesl 

> I implemented efficient dash clipping in Marlin 0.9.2 coming in jdk11 or as a jdk10 patch:
https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_2_jdk9 ... Could you give a try ? 

I don't mind trying but you're going to have to provide me with a pre-compiled version to use under Windows 64-bit. Also, I think it might be unproductive to do so until we narrow down the repro steps. Which leads me to:

> And explain me when the problem happens ?

I don't have concrete repro steps. All I know is that a couple times per day, I switch from VisualVM to my IDE and a few minutes later I notice that CPU usage is high. I track it down to VisualVM. When I try to switch focus back to it, the app is non-responsive and has to be killed.

**Comment by bourgesl** [comment]
As Marlin renderer is pure java code, you just need to patch jvisualvm or jdk10 with the marlin patch jar file given on the github release.
It will confirm or not if your problem is fixed and will be fixed by coming jdk11 in september. 
Anyway jdk10 is soon EOL, so no bug can be fixed anymore.

I agree it is important to determine reproducer steps... what plots do you have on screen (large dataset or zoom window) ?

**Comment by jisedlac** [comment]
OK, I wasn't aware that Marlin is now the default JDK renderer. Is there any way to disable it and run VisualVM with the original renderer on Java 9/10 as a workaround?

**Comment by jisedlac** [comment]
I've reviewed the VisualVM graphs code and there's nothing suspicious - the dashed line is exactly as long as the component size - being painted from 0 to getHeight(). I don't see any "heavy workloads" coming from VisualVM.

I've tried to reproduce the problem on my side - Windows 10, JDK 10.0.2, VisualVM 1.4.1 - with no success, works just fine. It looks like there's some corner case where the Marlin algorithm fails, maybe related to losing/gaining focus and/or visibility, guessing from the description from @cowwoc.

A screenshot of the VisualVM GUI at the point it gets frozen might help to identify the failure conditions.

Please let me know if there's anything we could do on VisualVM side to help to resolve the problem.

**Comment by bourgesl** [comment]
In jdk10, other antialiasing renderers were removed.
I suspect the getHeight() method returning an invalid size (Integer.MAX_VALUE) in some cases (invisible or disabled window...), any clue ? 
Where is the source code of this method ?

**Comment by jisedlac** [comment]
https://github.com/oracle/visualvm/blob/master/visualvm/charts/src/org/graalvm/visualvm/charts/xy/XYSelectionOverlay.java#L137

**Comment by jisedlac** [comment]
Component.getHeight() seems to work fine - I've just tried all possible window states. IMO there would be many other issues including OOME from offscreen buffers if getHeight() returned Integer.MAX_VALUE.

**Comment by bourgesl** [comment]
Maybe unrelated but josm had issues with that change:
https://bugs.openjdk.java.net/browse/JDK-8072682
Concerning marlin bug in jdk10, it can be avoided if the dash phase is 0. In your case the even stroke.

**Comment by jisedlac** [comment]
Regarding the josm bug - probably unrelated, VisualVM graphs don't use getDeviceConfiguration().getBounds().

**Comment by jisedlac** [comment]
Do I understand it correctly that the problem is caused by using a non-zero dash phase? Given that anything >= 0.0f is a valid value, do you plan to fix it for JDK11?

**Comment by jisedlac** [comment]
@cowwoc - please create a heap dump of the frozen VisualVM process once you reproduce the problem again. It could help us to debug the cause.

**Comment by jisedlac** [comment]
We won't change the current implementation in VisualVM given that the code is correct and a fix will be released in JDK.

But still I don't understand why I'm unable to reproduce the problem and @cowwoc reports it to be random. I would expect that a bug caused by wrong dash phase would be easy to hit.

**Comment by bourgesl** [comment]
As explained in the JBS bug, it happens randomly as marlin was summing an uninitialized unsafe float[256] array in jdk10, sometimes the real phase was negative and the dasher was looping forever !
Let's close this issue as WONT-FIX: jdk-10 bug fixed in jdk11. No backport available, except using marlin 0.9.2 release as java.desktop module patch.
Cheers

**Comment by cowwoc** [comment]
@bourgesl The bug you referenced that is fixed in Java 11 looks promising.
@jisedlac I will try taking a heap dump the next time the hang occurs. On a side-note, it would be great if I could spin up a second instance of VisualVM in this case to attach a profiler to the first instance. I couldn't figure out how to do this because the application seems to enforce a single instance per machine. I couldn't delete the "lock" file in the userdir because it was locked by the running instance (again, this is Windows).

You can close this issue for now and I will let you know once I have more information. Thank you for your help.

**Comment by thurka** [comment]
To run second instance of VisualVM, just use different userdir. This is same as with NetBeans.

**Comment by cowwoc** [comment]
It happened again. I was actively using VisualVM. I switched from the Overview tab to the Monitor tab, and the GUI hung. I am attaching a screenshot and a heap dump. I removed my application name from the screenshot but it is otherwise unmodified. don't know if the heap dump is complete because the second instance of VisualVM I was using to produce the dump died mid-way and I was unable to produce a heap dump thereafter. Hopefully it's good.

This was produced with JDK 10.0.2. I will try with JDK 11 later on.

![screenshot](https://user-images.githubusercontent.com/633348/43757199-0f633e62-99e6-11e8-822e-66c2eb7b4c4a.png)
[heapdump-1533621197516.zip](https://github.com/oracle/visualvm/files/2265184/heapdump-1533621197516.zip)

**Comment by thurka** [comment]
JDK 11 is not yet supported. Heap dump is OK.

**Comment by cowwoc** [comment]
@thurka Consider reopening this issue.
@bourgesl Take a look at the heap dump and let us know if this is the same bug that is fixed in JDK 11. Also note that @thurka mentioned VisualVM does not yet run on JDK 11 so it'll be hard to test any fixes.

**Comment by bourgesl** [comment]
I am on holiday so I only have my smartphone, no computer, so it is impossible for me to inspect the heap dump.
If somebody else could figure out what is the shape and its stroke attribute causing the problem, that would help a lot.

Finally try patching your jdk10 with marlin 0.9.2 patch to see if the problem is already fixed.

**Comment by jisedlac** [comment]
@cowwoc There's no bug in VisualVM and latest Marlin version likely fixes the problem you're experiencing, there's no reason to reopen this issue. Since you seem to be the only one to reproduce the bug, we'd appreciate if you could test Marlin 0.9.2 to verify the fix.

To use Marlin 0.9.2 with your JDK 10.0.2, download the bits from https://github.com/bourgesl/marlin-renderer/releases and use the "--patch-module" option mentioned at https://github.com/bourgesl/marlin-renderer/wiki/How-to-use, section "How to use (basic)", part For "JDK 9+".

@bourgesl Is there a visible indicator that the java.desktop module has been successfully patched and JDK 10.0.2 runs with Marlin 0.9.2?

**Comment by jisedlac** [comment]
@bourgesl We've analyzed the heap dump, the DDasher uses a NaN phase and also other values are strange at the point when the problem occurs. Your fix in DDasher.init() seems to address these issues. Let's wait for the verification from @cowwoc.

**Comment by bourgesl** [comment]
Thanks for the diagnostic. 
If marlin patch is in action, you should see following logs (System.out or in log files):

INFO: ===============================================================================
INFO: Marlin software rasterizer           = ENABLED
INFO: Version                              = [marlin-X.Y]
INFO: sun.java2d.renderer                  = org.marlin.pisces.MarlinRenderingEngine
...

**Comment by cowwoc** [comment]
@jisedlac I need your help getting patch-module to work (I am asking you because this problem is not specific to Marlin).

I opened `visualvm.conf` and added `-J--patch-module=java.desktop=C:/Program Files/visualvm_141/marlin-0.9.2-Unsafe-OpenJDK9.jar` to the end of the `visualvm_default_options` variable. Unfortunately this does not work because the path contains spaces. But I can't simply quote the path because the variable value is already quoted.

How is one supposed to quote spaces inside variable values?

**Comment by jisedlac** [comment]
@cowwoc I think the "solution" is perfectly OK for a quick bugfix verification. Glad to see you've found a way to use path with spaces - I don't have any special knowledge of quoting in visualvm.conf.

The output probably goes to just the console, not to the logfile. Please try to start VisualVM from the Windows Command Prompt (cmd) to see it.

**Comment by cowwoc** [comment]
@jisedlac That did it. Thanks.
@bourgesl I enabled the patch but the `sun.java2d.renderer` line does not match what you mentioned:

```
INFO: Marlin software rasterizer           = ENABLED
INFO: Version                              = [marlin-0.9.2-Unsafe-OpenJDK]
INFO: sun.java2d.renderer                  = sun.java2d.marlin.DMarlinRenderingEngine
```

Is this a problem?

**Comment by bourgesl** [comment]
@cowwoc looks good. Hope this marlin upgrade fixes your problem
