### ISSUE TITLE
OS X releases die instantly 1.3.9 - 1.4.1

### ISSUE THREAD

**Issue by atamanroman** [oracle/visualvm#108]
All available OS X releases die instantly on both my Macs:

    $ open /Applications/VisualVM.app/
    LSOpenURLsWithRole() failed with error -10810 for the file /Applications/VisualVM.app.

I guess the shell runner (`./Contents/Resources/visualvm/bin/visualvm`) does fail:

    $ ./Contents/Resources/visualvm/bin/visualvm
    Error occurred during initialization of boot layer
    java.lang.module.FindException: Module java.activation not found

The launcher defaults to Java 11 on my machine (1.8.0+). It looks like the option "-J--add-modules=java.activation" in visualvm.conf has no effect.

VisualVM starts when I override the JDK with `./Contents/Resources/visualvm/bin/visualvm --jdkhome $JAVA8_HOME` 

It seems that others have experienced this as well (see comments): https://stackoverflow.com/a/13690431/366299

I can't find the 1.3.2 or 1.3.5 DMG anywhere, so I can't test if they work.

**Comment by jisedlac** [comment]
VisualVM doesn't run on JDK 11 - see for example GH-106. Please use Java 8 - 10.

Support for JDK 11 will be added in VisualVM 1.4.2 after JDK 11 official release.

**Comment by atamanroman** [comment]
VisualVM should be able to start as long as there is a JDK 8 / 10 available on the machine, right? But the launcher dies if there is JDK 11 installed. 

The problem is that libexec relies on JAVA_HOME which is usually not set for GUI applications on OS X. So there is no good way for the user to control the JDK your launcher picks through `nbexec`. The `visualvm` script should detect the latest supported JDK and start `nbexec` with the correct `--jdkhome`. But right now it just picks the latest JDK, which is JDK 11 on many developer machines.

**Comment by jisedlac** [comment]
VisualVM launcher is not the problem, it works fine. JDK 11 is the failing component in this case, due to incompatible changes from JDK 10.
