### ISSUE TITLE
Page up, page down keys do not work properly in tree tables

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#109]
Version: 1.4.1 (Build 180424); platform 20180424-unknown-revn
System: Windows 10 (10.0) , amd64 64bit
Java: 10.0.2; Java HotSpot(TM) 64-Bit Server VM (10.0.2+13, mixed mode)
Vendor: Oracle Corporation, http://java.oracle.com/
Environment: Cp1252; en_CA (visualvm)

**To Reproduce**
1. Attach VisualVM to an application
2. Click on 'heap dump'
3. Switch to 'Objects' view
4. Use the mouse to select a row in the middle of the list
5. Notice that hitting page down key jumps to the first entry in the list
6. Notice that hitting page up key jumps to the first entry in the list, even if there are many pages of entry above the current row.

**Expected behavior**
* Hitting the page up key should scroll one page up
* Hitting page down key should scroll one page down

* These keys seem to work properly in all other tabs, such as "Threads" and "Sampler"
* This issue is reproducible always.

**Comment by jisedlac** [comment]
Fixed.
