### ISSUE TITLE
Heapdump cache files not deleted

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#111]
**Describe the bug**
VisualVM allows to delete captured heap dumps. However it only deletes the heap dump file and the corresponding cache files in *.hwcache* directory are not deleted.

**To Reproduce**
1. Take a heap dump
2. Open heap dump
3. Find heap dump location
4. Delete heap dump

**Expected behavior**
*.hwcache* directory should be deleted.

**Comment by jisedlac** [comment]
Fixed.
