### ISSUE TITLE
README Link to Netbeans Dev Binaries Outdated

### ISSUE THREAD

**Issue by Amar1729** [oracle/visualvm#116]
The [(broken) link in the README](https://github.com/oracle/visualvm/blame/15dee7f3b8629c2882f606cf1b56784959ece01b/README.md#L17) should be updated to reflect the current version of the dev binaries: 
https://github.com/oracle/visualvm/blob/1b3e83b1143dbd350e528f6f2c5100609f644f57/visualvm/nb90_platform_07082018.zip

Later commits could introduce a symlink such as `visualvm/nb90_platform_current.zip` and point the README to that so the link doesn't have to be constantly updated.

**Comment by thurka** [comment]
Thanks for spotting this. Fixed.
