### ISSUE TITLE
Compare heap dump is missing green/red bar.

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#119]
**Describe the bug**
Compare heap dump is missing green/red bar to visualise difference in instances.

**To Reproduce**
1. Compare two heap dumps in VisualVM 1.4.2
2. Compare two heap dumps in VisualVM 1.3.9

**Expected behavior**
See attached screenshot for expected behavior. 

**Screenshots**
<img width="836" alt="green" src="https://user-images.githubusercontent.com/22048069/48620921-1c165700-e9a2-11e8-9507-d928121b7ef0.png">

**Comment by jisedlac** [comment]
Fixed in master.
