### ISSUE TITLE
Eclipse VisualVM launcher does not accept JDK 10

### ISSUE THREAD

**Issue by OferYuval** [oracle/visualvm#120]
When using   Eclipse Launcher  (Eclipse Version: 2018-09 (4.9.0)) under windows 10, plugin setting does not accept JDK 10. 
See image [here](https://i.stack.imgur.com/VFWUy.jpg) 
And more details [here](https://stackoverflow.com/questions/53060052/integrate-visualvm-with-eclipse-4-9-and-jdk-10/53707353#53707353)
New settings can not be applied when configuration when JDK Home points to JDK 10.
It does accept JDK 1.8.

**Comment by OferYuval** [comment]
Thank you for your message.
I don’t have VisualVM installed right now. 
When I do get it installed I will update you, should there be any issues. 
Kind regards,

**Comment by thurka** [comment]
>Thank you for your message.
>I don’t have VisualVM installed right now.
>When I do get it installed I will update you, should there be any issues.

How long it can take? I was hoping that you can test it before I will release this new version of VisualVM Launcher.

**Comment by OferYuval** [comment]
I installed it and was able to configure  JDK 10. It does accept it now. 
I did not have time yet to launch and use it.

**Comment by thurka** [comment]
>I installed it and was able to configure  JDK 10. It does accept it now.
>I did not have time yet to launch and use it.
Thanks.

**Comment by monochromata** [comment]
I was able to launch VisualVM when launching a test run configuration using visualvm_launcher_u3_eclipse.zip in Eclipse 2018-12. Thank you, thurka!

**Comment by thurka** [comment]
@monochromata Thanks for testing.
