### ISSUE TITLE
Left/right scrolling to switch tabs is annoying

### ISSUE THREAD

**Issue by mihxil** [oracle/visualvm#122]
I think it is a new feature that left/right scrolling (e.g. with an apple mouse) switches between tabs. This is annoying, because it even happens when your focus is not on the tabs, but for example when you  just clicked on one of the sub-table (e.g. the Operations tab of MBeans), it is easy to accidentelly scroll a bit left or right, and the complete window changes in front of you, which leaves me a bit baffled everytime it happens.

I'd like the feature to be optional, or removed alltogether.

**Comment by jisedlac** [comment]
Thanks for the feedback! I assume you're filing against VisualVM 1.4.2 on Mac OS X.

This is not a new feature, it works this way in older VisualVM releases as well. To me it looks like a Swing bug in Aqua LaF, all unhandled wheel scrolls (on a non-scrollable component) are propagated to the parent TabbedPane.

Will try to address for the next release.

**Comment by mihxil** [comment]
Yes, indeed, 1.4.2 on Mac OSX. Thank you for the feedback too!

**Comment by jisedlac** [comment]
Fixed in master.
