### ISSUE TITLE
Let choose dark theme, because VisualVM is not able to detect dark theme itself

### ISSUE THREAD

**Issue by neworld** [oracle/visualvm#124]
**Is your feature request related to a problem? Please describe.**
I am using Qtile windows manager. Everything on my computer is dark, even web pages, thanks to plugins. Only VisualVM is white and burns my eyes.

**Describe the solution you'd like**
Option to choose between themes

**Describe alternatives you've considered**
I tried many things to trick `UiUtils.isDarkResultsBackground()` to return true. However, nothing works or I lack knowledge. Howerver, I will be happy to use any workaround.

**Additional context**
Github, file browser and VisualVM in the same screen:

![1547848709](https://user-images.githubusercontent.com/38703/51415008-fb72a500-1b7c-11e9-9014-ef0e94b517d1.png)

**Comment by Barteks2x** [comment]
Visualvm almost works with gtk dark theme. Everything is dark except a few components that visualvm gui code explicitly changes to some shade of white... But the text on them is still left white as in the gtk theme. Actual support for dark themes would be great.

**Comment by jisedlac** [comment]
Thanks for the feedback! On the screenshot I can see that VisualVM is running with the Metal LaF which AFAIK is independent on the desktop settings and always looks this way.

On Linux VisualVM has to be started with the GTK LaF to appear similar to other applications: `visualvm --laf GTK`. VisualVM 1.4.2 shouldn't display any bright components with white texts on dark themes - please file a new bug if not so.

FYI, `UiUtils.isDarkResultsBackground()` only reads the current Swing color theme, it doesn't control the bright/dark appearance. This is fully under Swing control and VisualVM cannot change it.

**Comment by neworld** [comment]
Thanks @jisedlac. It works!

**Comment by Barteks2x** [comment]
In my case it looks exactly the same as in https://github.com/oracle/visualvm/issues/102

**Comment by jisedlac** [comment]
@Barteks2x you can just download & unzip the latest VisualVM archive from https://visualvm.github.io/download.html, no need to rely on gentoo repositories.
