### ISSUE TITLE
Suppress EULA

### ISSUE THREAD

**Issue by deva10031** [oracle/visualvm#129]
**Describe the bug**
Application asks user to respond on EULA prompt. Need a command-line to suppress this during install.

**To Reproduce**
1. Double click on bin\visualvm.exe
2. See the EULA message appearing on screen. Does not appear again if responded once though.

**Expected behavior**
We need a command-line method or an argument which can be used during install, so that the users do not receive any prompt during application launch.

**Screenshots**
<attached>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version JDK 11.0.2
 - Version 1.4.2
![eula visualvm](https://user-images.githubusercontent.com/38223389/54694499-b3c9b480-4afe-11e9-93a6-c9bb8955cb0f.PNG)

**Comment by jisedlac** [comment]
The VisualVM user is required to read and accept the license. We won't provide any way to suppress this dialog.
