### ISSUE TITLE
VisualVM not launching with Java 12

### ISSUE THREAD

**Issue by n1t4chi** [oracle/visualvm#130]
Latest version available on site (not sure about the status in repo) does not launch under Java 12. Same thing as with: https://github.com/oracle/visualvm/issues/73
Can we get a support soon?

**Comment by SMadani** [comment]
Furthermore I don't understand why they're intentionally blacklisting newer versions of Java. What has Java 12 done that "breaks" compatibility? Surely if you support Java 11 you can support 12 and later?!

**Comment by mgrandi** [comment]
It looks like the lines of code are here: 

https://github.com/oracle/visualvm/blob/027c9b7d502049f9ad6e740242ca8b3c95da94ee/visualvm/startup/src/org/graalvm/visualvm/modules/startup/VisualVMStartup.java#L57-L83

I also see in that method that it is checking for DISABLE_STARTUP_CHECK: 

https://github.com/oracle/visualvm/blob/027c9b7d502049f9ad6e740242ca8b3c95da94ee/visualvm/startup/src/org/graalvm/visualvm/modules/startup/VisualVMStartup.java#L43

so that would mean editing `/Applications/VisualVM.app/Contents/Resources/visualvm/etc/visualvm.conf` to have `-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true` in the JVM arguments, but i cannot for the life of me make it work, it always shows the error message =/

**Comment by mgrandi** [comment]
I have gotten around this by editing `/Applications/VisualVM.app/Contents/Resources/visualvm/etc/visualvm.conf` to set it to use a older version of the JDK:

```
# Default location of JDK:
#
# It can be overridden on command line by using --jdkhome <dir>
# Be careful when changing jdkhome.
# There are two VisualVM launchers for Windows (32-bit and 64-bit) and
# installer points to one of those in the VisualVM application shortcut
# based on the Java version selected at installation time.
#
#visualvm_jdkhome="/path/to/jdk"
visualvm_jdkhome="/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home"
```

**Comment by stokito** [comment]
@thurka could you please take look on this? It looks trivial.

**Comment by MrSandmanRUS** [comment]
@stokito @thurka @n1t4chi 
I create a pull request with fix:
https://github.com/oracle/visualvm/pull/133
Can someone approve it?

**Comment by thurka** [comment]
> Furthermore I don't understand why they're intentionally blacklisting newer versions of Java. What has Java 12 done that "breaks" compatibility? Surely if you support Java 11 you can support 12 and later?!

We cannot guarantee forward compatibility. VisualVM is available from JDK 6 and every major release up to JDK 10 had substantial changes. Proper support for new JDK version needs changes on several places and also some amount of testing.
If you want to try VisualVM 1.4.2 on unsupported and untested JDK, you can always disable the startup check with `bin/visualvm -J-Dcom.sun.tools.visualvm.modules.startup.DisableStartupCheck=true`

**Comment by thurka** [comment]
> so that would mean editing `/Applications/VisualVM.app/Contents/Resources/visualvm/etc/visualvm.conf` to have `-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true` in the JVM arguments, but i cannot for the life of me make it work, it always shows the error message =/

For VisualVM 1.4.2 you should use `-Dcom.sun.tools.visualvm.modules.startup.DisableStartupCheck=true`

**Comment by thurka** [comment]
> @stokito @thurka @n1t4chi @jisedlac
> I created a pull request with fix:
> #133
> Can someone approve it?

Support for new JDK requires additional changes in VisualVM. If you want to disable the startup check, please use `DisableStartupCheck` system property.

**Comment by MrSandmanRUS** [comment]
@thurka
Ok, thanks for the explanation.

**Comment by thurka** [comment]
Fixed in master.
