### ISSUE TITLE
Dark mode support for macOS

### ISSUE THREAD

**Issue by stevespringett** [oracle/visualvm#132]
**Describe the bug**
It's my understanding that VisualVM should identify dark mode and adjust its internal theme accordingly. On macOS Mojave with dark mode enabled, starting Visual VM 1.4.2 results in the default light theme.

**To Reproduce**
1. Enable dark mode in macOS Mojave
2. Install VisualVM 1.4.2
3. Launch VisualVM

**Expected behavior**
Dark mode

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - JDK version JDK 1.8.0_191
 - Version 1.4.2

**Comment by jisedlac** [comment]
VisualVM is a Swing application and Swing is responsible for detecting & following desktop appearance settings (note that JConsole runs with light theme as well). Once Swing supports Mac OS X dark theme, VisualVM will behave correctly.

As a workaround, you should be able to use the Darcula LaF with VisualVM - not designed for VisualVM, but works pretty fine.
