### ISSUE TITLE
GraalVM visualvm will not start on Fedora 30

### ISSUE THREAD

**Issue by pmlopes** [oracle/visualvm#134]
Several NPE's related to fontconfig configuration missing on the CE distribution, and after adding a sample config, NPE locating system fonts.

Both `fontconfig` and `freetype` are installed in the system.

**Comment by thurka** [comment]
This is not a bug in VisualVM. Any other Swing application behaves the same. Try to run for example `jconsole`.  See [GraalVM-1269](https://github.com/oracle/graal/issues/1269) for more details and workaroud. It looks like removing `graalvm-ce-19.0.0/jre/lib/amd64/libfreetype.so.6` resolves the issue.
