### ISSUE TITLE
Error when starting CPU or Memory Profiler

### ISSUE THREAD

**Issue by joujoukinder** [oracle/visualvm#136]
Hi, 

I get the following error when starting the CPU or Memory profiler : 

When starting target JVM, with command: C:\Program Files (x86)\Java\bin\java.exe
-agentpath:C:/Program Files (x86)/Java/jdk1.7.0_75/lib/visualvm/profiler/lib/deployed/jdk16/windows/profilerinterface.dll
-Xbootclasspath/a:C:\Program Files (x86)\Java\jdk1.7.0_75\lib\visualvm\profiler\lib\jfluid-server.jar;C:\Program Files (x86)\Java\jdk1.7.0_75\lib\visualvm\profiler\lib\jfluid-server-15.jar
org.netbeans.lib.profiler.server.ProfilerServer
C:/Program Files (x86)/Java/jdk1.7.0_75/lib/visualvm/profiler/lib/deployed/jdk16/windows
5141
10
____Profiler+Calibration+Run____
, caught an exception: java.io.IOException: Cannot run program "C:\Program Files (x86)\Java\bin\java.exe" (in directory "."): CreateProcess error=2, Cannot find file

My java.exe path is located here : "C:\Program Files (x86)\Java\jre\bin"

How can I tell the profiler to look at the good location ?

Thannks for your help.

Best regards,

MS

**Comment by jisedlac** [comment]
Hello, thanks for the feedback!

I've configured a similar setup on my side and everything works fine, not sure what's the problem. What is the output when executing "C:\Program Files (x86)\Java\bin\java.exe -version" in Windows Command Prompt? Make sure you're executing it as the same user who runs VisualVM and the profiled application.

Any chance to move the JDK installation to a location which doesn't have space in path? Any chance to use a newer JDK? The most recent VisualVM at https://visualvm.github.io requires at least JDK 8.

**Comment by jisedlac** [comment]
Any update on this problem? Have you managed to make the profiling work?

**Comment by thurka** [comment]
Closing until more information is available.
