### ISSUE TITLE
Is there any way to run visualvm and its features like tracer plugin for detecting cpu usages,memory usage etc from the console itself?

### ISSUE THREAD

**Issue by warmachine102** [oracle/visualvm#138]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jisedlac** [comment]
Not sure what running the Tracer plugin from console means. If you are asking for a headless mode, the answer is NO - VisualVM has been designed as a visual tool.
