### ISSUE TITLE
Threads Tab not showing for OpenJdk11

### ISSUE THREAD

**Issue by gianiloveholidays** [oracle/visualvm#139]
**Describe the bug**
The threads tab is not appearing when connect to a OpenJdk11 vm.

**To Reproduce**
1. Run a OpenJdk11 application
2. Open visualVm
3. Select the application you've started UP
4. The threads tab is not there

**Expected behavior**
The threads tab should appear

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

**Screenshots**
![Screenshot 2019-07-10 at 11 01 27](https://user-images.githubusercontent.com/47177332/60961097-4cc94900-a303-11e9-9969-ab83b80ee103.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version [JDK 11.0.2]
 - Version 1.4.3

**Comment by thurka** [comment]
As you can see in the attachment, I am running VisualVM 1.4.3 on MacOS with OpenJDK 11.0.2 and I have Threads tab. Please provide more information, how to reproduce this issue. Thanks.
![openjdk_11](https://user-images.githubusercontent.com/22048069/60966058-ac315400-a317-11e9-88d6-230d20b82416.png)

**Comment by gianiloveholidays** [comment]
I have installed in my machine Java 8 and Java 11.
From Java 8 applications I can see the threads tab.
Is there any configuration that I should give to visualvm to use one or other vm during the startup?
I'm running an springboot standalone application. Using project reactor with parallel threads.
It goes to mysql database and generates a file on a GCP bucket.

**Comment by thurka** [comment]
> I have installed in my machine Java 8 and Java 11.
> From Java 8 applications I can see the threads tab.

There should be no difference in JDK version. Both JDK 8 and JDK 11 should work just fine. Are you sure that the problem is not caused by something else?

> Is there any configuration that I should give to visualvm to use one or other vm during the startup?

If you what to run VisualVM on specific JDK, you can use `--jdkhome` command-line option.

> I'm running an springboot standalone application. Using project reactor with parallel threads.
> It goes to mysql database and generates a file on a GCP bucket.

OK. Can you provide exact steps how to reproduce your problem? Can you attach VisualVM `messages.log` file to help diagnose your problem?

**Comment by Keymaster65** [comment]
I had this problem using a 64bit application and a 32 bit visualvm. Using 64 bit for both solved the problem. I set --jdkhome to a 64 bit jdk.

**Comment by seong-jung** [comment]
I had a same issue on Windows 10. and I solved it to NO running as admin.

**Comment by finion** [comment]
@seong-jung what do you mean NO running as admin? I ran the visualvm by just clicked the bin/visualvm.exe and no thread tab shown.

The visualvm information
![image](https://user-images.githubusercontent.com/4544480/75133073-4235b580-5714-11ea-8f84-ed8e216d7079.png)

Running application
![image](https://user-images.githubusercontent.com/4544480/75133154-9ccf1180-5714-11ea-95d3-4382a07a88a3.png)

OS: windows 10

**Comment by seong-jung** [comment]
@finion
On right click any file, you can see below menu.
_**running as admin**_ means execution by below red one. (this is just one way)
_**NO running as admin**_ means execution by just double click or below menu's Open.
![image](https://user-images.githubusercontent.com/30590761/75138501-baf53b80-572d-11ea-9501-f391a709db82.png)
In my case, my WAS(Tomcat) was _**running as admin**_ and visualVM was _**runnig as NO admin**_.
I resolved it execution WAS to _**running as NO admin**_ or visualVM to _**running as admin**_.

it reproduced in
![image](https://user-images.githubusercontent.com/30590761/75138849-9188df80-572e-11ea-9ffa-866e4997cc15.png)
- tomcat-8.5.34
- Windows 10

**Comment by finion** [comment]
@seong-jung thanks for the explanation.

Problem solved after I added the jvm argument `-Djava.rmi.server.hostname=localhost`

**Comment by jisedlac** [comment]
Missing Threads tab always means a broken JMX connection.

For a local application VisualVM is able to make the connection automatically as long as both the tool and the target app run under the same account (neither or both as administrator, neither or both as a service) and on Windows both must run the same architecture (64bit or 32bit).

If there are any networking issues breaking the automatic local JMX connection, they may be apparently workarounded using the `-Djava.rmi.server.hostname=localhost` argument.

If nothing of the above helps, you should be able to see the Threads tab for an explicit JMX connection (enable the JMX agent in the target app manually and use the Add JMX Connection action).

**Comment by tsaker** [comment]
Connecting via JMX remote I had a similar problem whereby the Threads tab was missing and all actions on the Sampler tab were disabled.  I resolved the issue by using the correct access login (configured in the jmxremote.auth file) with readwrite instead of readonly permissions (configured in the jmxremote.access file).

**Comment by ririliu** [comment]
> Missing Threads tab always means a broken JMX connection.
> 
> For a local application VisualVM is able to make the connection automatically as long as both the tool and the target app run under the same account (neither or both as administrator, neither or both as a service) and on Windows both must run the same architecture (64bit or 32bit).
> 
> If there are any networking issues breaking the automatic local JMX connection, they may be apparently workarounded using the `-Djava.rmi.server.hostname=localhost` argument.
> 
> If nothing of the above helps, you should be able to see the Threads tab for an explicit JMX connection (enable the JMX agent in the target app manually and use the Add JMX Connection action).

`-Djava.rmi.server.hostname=localhost`  should be add to target app vm argument
