### ISSUE TITLE
Profiling not supported on IcedTea and AdoptOpenJDK builds

### ISSUE THREAD

**Issue by Barteks2x** [oracle/visualvm#143]
**Describe the bug**
Profiling is not available for IcedTea and AdoptOpenJDK builds

**To Reproduce**
Run an application with IcedTea or AdoptOpenJDK JDK and attach to it with visualvm. There will be no "profiler" option.

**Expected behavior**
Those JVM builds should be supported.

**Desktop (please complete the following information):**
 - OS: Linux gentoo
 - JDK version IcedTea 1.8.0_212, AdoptOpenJDK 11.0.3_p7
 - Version 1.4.3, also tested commit ad76e9d34ba49213e5b7527b7d2e5ef5a34a97fa

**Additional context**
The supported JVMs are hardcoded here https://github.com/oracle/visualvm/blob/ad76e9d34ba49213e5b7527b7d2e5ef5a34a97fa/visualvm/profiler/src/org/graalvm/visualvm/profiler/ProfilerSupport.java#L332-L340 and doesn't consider IcedTea and AdoptOpenJDK as a supported vendor.
Adding `-J-Dcom.sun.tools.visualvm.profiler.SupportAllVMs=true` for 1.4.3 and `-J-Dorg.graalvm.visualvm.profiler.SupportAllVMs=true` for latest commit as commandline argument work around the issue.

**Comment by thurka** [comment]
Right, `-J-Dcom.sun.tools.visualvm.profiler.SupportAllVMs=true` is the correct workaround.

**Comment by thurka** [comment]
Can you point me to IcedTea 1.8.0_212 download? Thanks.

**Comment by Barteks2x** [comment]
I have it compiled from source on my gentoo system, but there is a bin package. The ebuild points to binaries from here https://dev.gentoo.org/~gyakovlev/distfiles/ (version 3.x is java 8)

**Comment by thurka** [comment]
Thanks. I was able to use  https://dev.gentoo.org/~gyakovlev/distfiles/ .

**Comment by thurka** [comment]
Fixed in VisualVM 1.4.4.
