### ISSUE TITLE
VisualVM doesn't show static fields

### ISSUE THREAD

**Issue by stefan-reich** [oracle/visualvm#146]
Hi, I am not seeing static fields.

Please see [this screenshot](http://botcompany.de/1004590/raw/1101819) which shows a static field `local_log`. Then I click on the class object (`Class#8147`) and [see neither `local_log`](http://botcompany.de/1004590/raw/1101820) nor any other static field that should be there.

Where is the mistake?

This is on OpenJDK 13 EA 31.

Thanks

**Comment by thurka** [comment]
Fixed in master.

**Comment by stefan-reich** [comment]
That's great!
