### ISSUE TITLE
Unable to install plugins from Plugin Center

### ISSUE THREAD

**Issue by sattishv** [oracle/visualvm#148]
**Describe the bug**
While trying to install plugins from plugins center we noticed an error.
"Unable to connect to the VisualVM 1.4.3 Plugins Center because of No such file or directory"

**To Reproduce**
1. Go to 'Tools -> PLugins"
2. Click on "Check for Updates"

**VisualVM log**
Not sure about the log path in MacOS

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version [JDK 1.8.0_131]
 - Version: 1.4.3

**Comment by thurka** [comment]
Please attach VisualVM log. To find out VisualVM log go to VisualVM -> About VisualVM -> Logfile.

**Comment by thurka** [comment]
I am not able to reproduce the problem using above steps to reproduce.

**Comment by sattishv** [comment]
[visualvmlogfile.txt](https://github.com/oracle/visualvm/files/3505899/visualvmlogfile.txt)
have attached  the log file for your review.

**Comment by thurka** [comment]
From your logfile:
`Could not create /Users/sattivasudevan/Library/Caches/VisualVM/1.4/catalogcache`
It looks to me like permission problem. Check the permissions and ownership of `/Users/sattivasudevan/Library/Caches/VisualVM` and `/Users/sattivasudevan/Library/Caches/VisualVM/1.4` directories. Did you run VisualVM as root?

**Comment by thurka** [comment]
If you cannot fix permissions, you can safely delete whole `/Users/sattivasudevan/Library/Caches/VisualVM` directory.

**Comment by sattishv** [comment]
Hi Tomas,

We could install the plugins by creating the directory catalogcache. Curious to know how you identified that the issue is with directory missing since i couldn't see the directory name in error stack trace. Anyway Thanks for your instant response. Appreciate your support

**Comment by thurka** [comment]
> We could install the plugins by creating the directory catalogcache. 

OK, but it does not look like a proper solution. In normal circumstances, this is _not_ required.

>Curious to know how you identified that the issue is with directory missing since i couldn't see 
>the directory name in error stack trace. 

It is in the log file you attached later.

>Anyway Thanks for your instant response. Appreciate your support

You are welcome.
