### ISSUE TITLE
is 'Record allocations stack traces' still supported in 1.4.3?

### ISSUE THREAD

**Issue by shuaiswu** [oracle/visualvm#150]
I am using VisualVM 1.4.3, is 'Record allocations stack traces' available in any plugin? Thanks!

**Comment by shuaiswu** [comment]
I am using VisualVM 1.4.3, and was not able to find the 'Record allocations stack traces' option. Is it in any plugin? Thanks!

**Comment by jisedlac** [comment]
VisualVM 1.4.3 -> Profiler -> Memory settings -> "Limit allocations depth" checkbox. This controls whether/how deep allocation stack traces will be collected (unselect for full allocation stack traces).
