### ISSUE TITLE
Windows: High DPI scaling

### ISSUE THREAD

**Issue by JakobPyttlik** [oracle/visualvm#151]
**Describe the bug**
When working with a screen with higher DPI, the icons and parts of the UI do not scale.

**To Reproduce**
1. Change screen DPI to something > 100% (like 175%)
2. Open VisualVM
3. Icons/toolbar buttons will be small and hard to click (rendererd at native 16x16 instead of scaled size).

**Expected behavior**
Icons and labels should scale according to the selected scaling.

**VisualVM log**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Win10
 - JDK version OpenJDK 1.8
 - Version 1.4.3

**Comment by jisedlac** [comment]
VisualVM is a pure Swing application and doesn't have any chance to control the High DPI appearance on its own except of providing special HiDPI icons set, which is currently not planned.

Please try to run VisualVM with a newer JDK (9+ introduces automatic icons scaling, afaik) and/or experiment with the launcher and Swing settings:

- visualvm.exe -> Properties -> Compatibility -> Change High DPI settings on the OS level
- visualvm.exe -J-Dsun.java2d.uiScale=1.75 on the Swing level

**Comment by JakobPyttlik** [comment]
Thank you!
