### ISSUE TITLE
Can not local Java on MacOS

### ISSUE THREAD

**Issue by hoaphanFox** [oracle/visualvm#152]
**Describe the bug**

**To Reproduce**
1. Got a Mac
2. Install SDKMan
3. Install following JDK
```
➜  ~ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190717_298 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1 based on jdk8u222-b10)
```
4.Set JAVA_HOME too just to be sure
```
JAVA_HOME=/Users/hoa.phan/.sdkman/candidates/java/current
``` 
5. Attempt to run JVisualVM
```
➜  netflix-conductor git:(master) ✗ /Applications/VisualVM.app/Contents/MacOS/visualvm
Unable to find any JVMs matching version "1.8.0+".
Cannot find java. Please use the --jdkhome switch.
```

**Expected behavior**
JVisualVM ran without having to do long command like
```
/Applications/VisualVM.app/Contents/MacOS/visualvm --jdkhome /Users/hoa.phan/.sdkman/candidates/java/current
```

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version [JDK 1.8.0_181]
 - Version 1.4.3

**Additional context**

**Comment by thurka** [comment]
VisualVM needs to run on OpenJDK/OracleJDK. Running VisualVM on Eclipse OpenJ9 is not supported. VisualVM can find JDK, if such JDK is correctly installed on MacOS. To see correctly installed JDKs use `/usr/libexec/java_home -V`.

**Comment by kaeawc** [comment]
For anyone else coming across this who uses SDKMAN, the [solution posted here](https://stackoverflow.com/questions/76523553/how-to-make-usr-libexec-java-home-find-jdk-installed-using-sdkman-on-macos) makes such JDKs recognizable to `/usr/libexec/java_home`.

**Comment by niqdev** [comment]
thanks for sharing the solution! I created gist https://gist.github.com/niqdev/81672090a63196967e24eea93004d0fe
