### ISSUE TITLE
Feature request: Closing tabs with keyboard shortcut

### ISSUE THREAD

**Issue by perlun** [oracle/visualvm#153]
At the moment, closing tabs in the list of currently monitored applications can only be done using the mouse, by clicking on the upper-hand `x` or by right-clicking the tab and selecting one of the `Close` options (Close, Close All, Close Other).

It would be great if the `Close` option would be accessible via a keyboard shortcut as well. Preferably some default key used elsewhere, like Ctrl-W (Firefox/others?) or Ctrl-F4, but maybe it's best to make it configurable if it's reasonably easy.

Ideally, Close All and Close Other would also be accessible via the keyboard but since these are less commonly used (and pressing that key by mistake would be fatal), starting by making just the Close option accessible is perhaps best.

(Similar to #54 but for a different use case)

**Comment by jisedlac** [comment]
Thanks for the feedback! Slightly different than #54 because the window system including tabs is provided by the NetBeans Platform - not sure if we can add keyboard shortcuts on VisualVM side. Will investigate.

**Comment by jisedlac** [comment]
Used the shortcut from NetBeans - Ctrl+W.

Fixed in master.

**Comment by perlun** [comment]
Thanks @jisedlac, greatly appreciated. :+1:
