### ISSUE TITLE
Calibration should not hang on unknown/unsupported JDKs

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#155]
**Describe the bug**

**To Reproduce**
1. Start a profiling session against an application running JDK 13 
2. Visual VM will try calibrating the JDK
3. Calibration modal dialog box will hang forever.
4. Process must be killed.

**Expected behavior**
Calibration should succeed. Baring that, the process should fail, explaining what went wrong, and allow the user to close the dialog box.

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.
[messages.log](https://github.com/oracle/visualvm/files/3601099/messages.log)

**Desktop (please complete the following information):**
 - OS: `Microsoft Windows [Version 10.0.18362.295]`
 - JDK version: `JDK 13 13+33`
 - Version: `1.4.3`

**Comment by thurka** [comment]
This is regression introduced in VisualVM 1.4.2. Profiler tab should not be there for unsupported JDK.

**Comment by cowwoc** [comment]
That will lead to UX issues. I would prefer leaving the button there but showing an error message when pressed.

**Comment by thurka** [comment]
It was this way for years. I don't see a reason to change it now.

**Comment by cowwoc** [comment]
Can we ask a third person to break the tie? :)

**Comment by thurka** [comment]
This regression is fixed as side-effect of GH-143.

**Comment by thurka** [comment]
Fixed in VisualVM 1.4.4.
