### ISSUE TITLE
CPU Sampling disabled all the time

### ISSUE THREAD

**Issue by hakankarabulut** [oracle/visualvm#156]
Hi

As can be seen from the image below, the CPU button is disabled all the time. Google'd the issue but couldn't find anything useful.

![image](https://user-images.githubusercontent.com/20728430/64972635-4aaada00-d8b2-11e9-8d7a-4edd5a93e6be.png)

Hope that there already exists a solution to this issue.

Regards

**Comment by jisedlac** [comment]
Please open the Sampler tab with the disabled CPU button again and provide the full VisualVM screenshot, the reason should be displayed in the Summary section, "CPU sampling:".

Also please upload the VisualVM logfile to this bugreport (Help | About | Logfile) so we can start analyzing what's wrong.

**Comment by hakankarabulut** [comment]
Hi again

I've found a solution to the issue. Language settings (-Duser.language=tr) caused this problem. When I changed it as -Duser.language=en, the problem is solved. Probably, a string operation (toUpperCase/toLowerCase etc.) affected by language settings resulted in this issue.

Regards

**Comment by jisedlac** [comment]
OK, thanks for the update. Looks like a JDK bug:

  - https://bugs.openjdk.java.net/browse/JDK-7033678
  - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-7187703

Cannot be fixed on VisualVM side. Turkish locale cannot be used for JMX-based features on the monitored process side.
