### ISSUE TITLE
Does not show applications without reporting error

### ISSUE THREAD

**Issue by AL-Liang** [oracle/visualvm#157]
Hi,all.

VisualVM(version:1.4.3 and 1.4.4) worded properly before. However, it does not show applicaitons now and all options under applications are disabled. Some applicaitons are running locally. No error dialogs appeared.

![image](https://user-images.githubusercontent.com/9420231/65750015-fa493d00-e139-11e9-9811-6b46c1ba9fd9.png)

What is the solution to this?

Thanks a lot!

**Comment by jisedlac** [comment]
Looks like you've closed the Applications pane. Use Window | Applications or Window | Reset Windows in the menu bar to open it again.

**Comment by AL-Liang** [comment]
I found out "Window -> applicaitons" can show the "application view". Now close this issue. Thanks, @jisedlac .
