### ISSUE TITLE
Option to change the colors of thread states

### ISSUE THREAD

**Issue by shivsepra** [oracle/visualvm#16]
Cant find monitor state of a thread when its in park state, see the following example

![image](https://cloud.githubusercontent.com/assets/14000849/23492800/fde65048-ff2c-11e6-90e0-ce8ee1b7313c.png)

**Comment by rofreytag** [comment]
+1 

Please do this. It is really hard to find monitor vs parked.
Let me do it via config file, if need-be.

**Comment by jisedlac** [comment]
Changed the Monitor state color.

Colors can be tweaked manually by setting these system properties:
```
org.graalvm.visualvm.ThreadColorRunning
org.graalvm.visualvm.ThreadColorSleeping
org.graalvm.visualvm.ThreadColorMonitor
org.graalvm.visualvm.ThreadColorWait
org.graalvm.visualvm.ThreadColorPark
```
Sample usage:
```
./visualvm -J-Dorg.graalvm.visualvm.ThreadColorRunning=#00FF00
```


Fixed in master.

**Comment by rofreytag** [comment]
Awesome, thank you!

**Comment by shivsepra** [comment]
Thank you
