### ISSUE TITLE
Add unsupported JDK version override

### ISSUE THREAD

**Issue by BlueGoliath** [oracle/visualvm#160]
**Is your feature request related to a problem? Please describe.**

Attempting to run visualvm on Panama EA builds(reportedly JDK 14) results in an error about the JDK version being unsupported.

**Describe the solution you'd like**

Add an "ignore" button for unsupported JDK versions.

**Comment by jisedlac** [comment]
You can start VisualVM using `visualvm -J-Dcom.sun.tools.visualvm.modules.startup.DisableStartupCheck=true` to disable the JDK version check on startup.

Just wondering - what is your use case for running VisualVM using JDK 14?

**Comment by BlueGoliath** [comment]
It's just what Project Panama is built on. I think the actual code is JDK13 since JDK 13 hadn't even been released at the time the EA build was made.

**Comment by jisedlac** [comment]
I'm wondering why do you need to run VisualVM on an unsupported Java.

**Comment by BlueGoliath** [comment]
Does there need to be a super important reason? It's a tool for monitoring running JVMs and is therefore useful even on unsupported JDK versions. The check for unsupported JDK versions seems really unnecessary.

**Comment by jisedlac** [comment]
The JDK check is neccessary. VisualVM depends on various internals of the JDK which runs it and running on an unsupported JDK may break (and often breaks) VisualVM functionality. Thus we only support running VisualVM on defined & tested JDKs by default, and provide the above mentioned system property for skipping this check for testing purposes.

In case you need to monitor an unsupported Java instance, you can still do it from VisualVM running on a supported JDK. In your case, to monitor a JDK 14 process you can use VisualVM running on JDK 13. Please let us know in case this setup doesn't work for you.

**Comment by thurka** [comment]
As mentioned above you can use `-J-Dcom.sun.tools.visualvm.modules.startup.DisableStartupCheck=true` to disable the JDK version check.
