### ISSUE TITLE
Could the JMXMP optional jar be included in the visualvm distribution?

### ISSUE THREAD

**Issue by m86194** [oracle/visualvm#165]
The RMI connection is a bit painful in Docker environments.   JMXMP is an interesting alternative but require an optional jar to be added to visualvm.

If visualvm by default included the required JMXMP jar it would be easier to adopt JMXMP in deployments as it would only require adding the maven artifact to the program to connect to.

**Comment by thurka** [comment]
There is a similar issue - GH-162. Closing as duplicate.

**Comment by m86194** [comment]
@thurka I think that this is different.  I would just like the jar to be a part of the official binary download.  The similar issue refers to creating a new plugin requiring postinstall configuration which is what I think should be avoided.  Please reconsider.

**Comment by jmborer** [comment]
I have a plugin that does that. Currently I am trying to improve it to support additional settings.
