### ISSUE TITLE
Back traces no longer available since 1.4

### ISSUE THREAD

**Issue by heli80** [oracle/visualvm#166]
Hi,
since visualvm 1.4 it seems there is no longer a way to get a "back traces" view (e.g. for a hot method) from a snapshot taken from a CPU sampling session. This was very helpful to find out which code actually contributed to calling this method to what extend.

Any plans to add this feature again?
Thx!

**Comment by jisedlac** [comment]
The view is still available, can be accessed using the "Reverse calls" icon in live results/snapshot toolbar, the "View:" section.

You can access it also from the Forward calls/Hot spots view using the context menu, action "Find in reverse Calls".

**Comment by heli80** [comment]
Yes "Find in Reverse Calls" almost provides the functionality as the previous "Find Back Traces" despite the fact, that threads show up separately (i.e. not combined) in this view. It's thus harder to get an overview what code paths contributed to calling a hot method.

I know there is the "Select threads" button in the "View:" section that allows me to combine threads (which gives the exact result i want), but only if i select all threads individually. The problem is i have >100 threads that are interesting for me...

If i click "Show all threads" the "Merge selected threads" checkbox is unfortunately disabled. Is there a reason why merging all threads is prohibited?
Thx!

**Comment by jisedlac** [comment]
Merging all threads is disabled because of performance reasons when displaying live results. For a snapshot there's probably no reason to have this option disabled.

As a workaround for now, you can click "Show all threads" and unselect one of the threads you're not interested in - "Merge selected threads" becomes enabled.

**Comment by heli80** [comment]
Nice, your suggested workaround works indeed very well on a snapshot!

Doing the same thing on live results (even when already stopped) ultimately ended in an OOMException. So don't try this at home!

Thx for your help!
