### ISSUE TITLE
VisualVM-BufferMonitor plugin failed to monitor direct buffer of remote process

### ISSUE THREAD

**Issue by cfangplus** [oracle/visualvm#167]
I used VisualVM1.4.4 and installed VisualVM-BufferMonitor1.5 plugin to monitor direct buffers created by ByteBuffer.allocateDirect. The Buffer Pools tab and its direct buffer memory is shown for some remote process while that for some other remote process does not.

**Comment by cfangplus** [comment]
![1](https://user-images.githubusercontent.com/42287875/68356420-46ca6400-014d-11ea-9ba9-fd6b202553f7.png)
![Uploading 1.png…]()

**Comment by cfangplus** [comment]
![1](https://user-images.githubusercontent.com/42287875/68356463-5ea1e800-014d-11ea-85f7-1bf105c27d7b.png)
![Uploading 2.png…]()

**Comment by cfangplus** [comment]
![2](https://user-images.githubusercontent.com/42287875/68356542-8729e200-014d-11ea-9f57-f3f82596a8c1.png)

**Comment by thurka** [comment]
You need to enable JMX in remote process.

**Comment by cfangplus** [comment]
> You need to enable JMX in remote process.

Oh, yea, u're right, great thanks.

**Comment by thurka** [comment]
> Oh, yea, u're right, great thanks.

You are welcome.
