### ISSUE TITLE
 jvmstat and JMX info does not displayed in one place

### ISSUE THREAD

**Issue by cfangplus** [oracle/visualvm#170]
**Describe the bug**
Today I runned a Spark application which is based on jvm enviroment and I used VisualVM to monitor the remote executor process.
I run the jstatd command and the memory and thread info are correctly showed on the VisualVM dashboard while the MBeans tab and CPU info does not, please see the follow screenshot,
![1](https://user-images.githubusercontent.com/42287875/71708647-cadb5800-2e2d-11ea-80d5-1a27568341c7.png)

I know jstatd has nothing to do with jmx. So I set the jmx port using -Dcom.sun.management.jmxremote.port=8711 to enable JMX for the remote executor process.
Now I opened a JMX connection under the VisualVM and the MBeans tab and CPUinfo are correctly showed, please see the follow screenshot,
![2](https://user-images.githubusercontent.com/42287875/71708668-da5aa100-2e2d-11ea-9c80-4763841b7390.png)

Now I have a quesiton, there are two items on the VisualVM for the remote executor with same proecess id 169896. One item is setup by jstatd and lack of CPU info, while the other is setup by JMX with CPU and MBeans info.
I found a page from stackoverflow https://stackoverflow.com/questions/9319646/viewing-mbeans-through-jstatd which shows that jvmstat and JMX could be displayed in one place.
So is there a bug or does I miss something?

**Comment by thurka** [comment]
This should work fine. Can you, please, provide exact steps (namely commandline for remote application) and attach messages.log from VisualVM. Thanks.

**Comment by thurka** [comment]
Closing until more info is available.
