### ISSUE TITLE
CPU Monitor does not reflect CPU percentage of Java process being monitored

### ISSUE THREAD

**Issue by mondain** [oracle/visualvm#171]
This issue occurs on Ubuntu 18 with Amazon Corretto JDK 8 and VisualVM 1.4.4. The issue is that the CPU percentage reported in the monitor tab isn't even close to the actual CPU percentage in-use by the Java process being monitored.

**To Reproduce**
1. Start your Java application
2. Open a terminal
3. Execute `jps` to collect your Java application's process id (ex. 17716)
4. Execute `top` and observe the `%CPU` for the Java process id (from step 3)
5. Start VisualVM and attach to your Java application
6. Click on the monitor tab
7. Note the difference between VisualVM and `top` for the CPU percentage field 

**Expected behavior**
An accurate percentage of CPU in-use for the attached Java application / process. In my testing, the difference can be as low as 0.3% to as much as 90.0% or more depending upon CPU count.

**VisualVM log**
I have no log

**Screenshots**
![Screenshot from 2020-01-21 07-28-05](https://user-images.githubusercontent.com/510557/72818593-95ea4600-3c20-11ea-8c02-2808641daea3.png)
![Screenshot from 2020-01-21 07-28-02](https://user-images.githubusercontent.com/510557/72818600-9a166380-3c20-11ea-91ab-e1f4c51c39c1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - JDK version: 
```openjdk version "1.8.0_232"
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)
```
 - Version: 1.4.4

**Comment by thurka** [comment]
There is a difference between Linux top and VisualVM. For Linux maximum CPU usage is `number of CPUs * 100`, while VisualVM has always `100` as maximum CPU usage. So if you divide Linux CPU usage by number of CPUs, you should get the same numbers.

**Comment by mondain** [comment]
@thurka that would be misleading, if it were the case and it also doesn't fit. My machine has 8 cores and top reported 90.7% which yields 11.3%

**Comment by thurka** [comment]
What is misleading?

**Comment by mondain** [comment]
@thurka first off the math is wrong based on your explanation 11.3% != 1.7%

**Comment by broneill** [comment]
Top is reporting that the CPU is 12.3% for the Java process. Divided by 8 is: 1.5%. The process at 90.7% is something completely different.

**Comment by mondain** [comment]
@broneill that makes sense for the `java` process itself. Thanks for your time, I'm closing this.
