### ISSUE TITLE
A blank line added in the top tool bar

### ISSUE THREAD

**Issue by AL-Liang** [oracle/visualvm#174]
![blankLine](https://user-images.githubusercontent.com/9420231/74523897-ff781e80-4f58-11ea-8b39-ef6c498d4bf3.png)
I am not sure if it is a bug.

**Describe the bug**
A blank line added in the top tool bar.

**To Reproduce**
The screen recording file shows it.

**Expected behavior**
Not having the blank line in the top tool bar.

 - MacOS 10.15.3
 - Version 1.4.4
[屏幕录制2020-02-1417.31.34.zip](https://github.com/oracle/visualvm/files/4203826/2020-02-1417.31.34.zip)

**Comment by thurka** [comment]
Try to right-click on toolbar and invoke 'Reset Toolbars'. Does it fix your problem?

**Comment by thurka** [comment]
Closing until more info is available.
