### ISSUE TITLE
Bug: valid profiler calibration input gets rejected as invalid

### ISSUE THREAD

**Issue by azolotko** [oracle/visualvm#175]
**Describe the bug**
During refactoring in https://github.com/oracle/visualvm/commit/4a4381235c455f4a044268796f06b4987adbbaa4#diff-dd77b6a74da25abd7eb268c0c2d42089L190-R191 a bug was introduced: only a `javaVersionString` that equals to `CommonConstants.JDK_CVM_STRING` will be considered as a valid calibration input. Most likely, it should be the other way around. 

**To Reproduce**
1. Go to Application/Profile Startup
2. Choose desired settings and press the Profile button. 
3. A "Calibration data missing" dialog appears stating that "Profiling cannot be started on this JDK" despite the profiling data being present and absolutely valid.

**Expected behavior**
Profiling should work on supported JVMs.

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/4240061/messages.log)

**Screenshots**
<img width="760" alt="Screenshot 2020-02-22 at 22 50 53" src="https://user-images.githubusercontent.com/110424/75099779-e52be980-55c5-11ea-9c2d-ed2ed91b557a.png">
<img width="541" alt="Screenshot 2020-02-22 at 22 51 22" src="https://user-images.githubusercontent.com/110424/75099780-e6f5ad00-55c5-11ea-8127-502fbc1d7ede.png">
<img width="538" alt="Screenshot 2020-02-22 at 22 51 27" src="https://user-images.githubusercontent.com/110424/75099781-e9f09d80-55c5-11ea-9f96-195cd84b1525.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3 (19D76)
 - JDK version [11.0.6; OpenJDK 64-Bit Server VM (11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)]
 - Version [2.0 (Build 200206); platform 20191008-unknown-revn]
 - target JDK version [1.8.0_222; OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)]

**Comment by jisedlac** [comment]
Thanks for the report!

Seems to only affect the Startup Profiler plugin, the built-in Profiler works fine.

**Comment by azolotko** [comment]
@thurka should I close PR #176 ?

**Comment by thurka** [comment]
> @thurka should I close PR #176 ?

We are working on fix for 2.0. Unfortunately the fix in master cannot be used. Once it is ready, we will close this issue.

**Comment by thurka** [comment]
> @thurka should I close PR #176 ?

Yes, you can close PR #176.

**Comment by thurka** [comment]
Fixed in master, workaround also added to startup profiler in VisualVM 2.0.
