### ISSUE TITLE
Use Maven to build VisualVM

### ISSUE THREAD

**Issue by jmborer** [oracle/visualvm#181]
1) IMHO, Maven is much easier to use and build a Netbeans Platform based application such as VisualVM. Ant is more flexible but NB projects are more complexe to understand and therefore to build. It would for example no longer be required to copy the Netbeans sources into the VisualVM project.

2) Publish Maven artifacts to a repo is just straightforward and would avoid any additional steps by using Maven Nb plugins to publish the artifacts of the Ant project.

3) When people like me want to re-use or build their own app/plugin relying on VisualVM artifacts/modules, it is much easier as well

It is probably possible to maintain both Ant and Maven in parallel in a first step.

**Comment by ianbrandt** [comment]
Or Gradle.

**Comment by thurka** [comment]
[VisualVM artifacts](https://twitter.com/visualvm/status/1424661070715703300) are available on Maven Central since VisualVM 2.1. This should solve your requests.
