### ISSUE TITLE
Cannot launch on OpenJDK 14

### ISSUE THREAD

**Issue by mr-git** [oracle/visualvm#184]
**Describe the bug**
VisualVM doesn't start when OpenJDK 14 is used

**To Reproduce**
1. Install Open JDK 14 on macOS
2. Download VisualVM 2.0
3. Attempt to start it

**Expected behavior**
VisualVM starts normaly

**Screenshots**
<img width="599" alt="Screenshot 2020-03-18 at 23 43 39" src="https://user-images.githubusercontent.com/8796159/77010461-79ddf900-6972-11ea-811d-3e210d233c83.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version: OpenJDK 14
 - Versio: 2.0

**Comment by thurka** [comment]
You can start VisualVM 2.0 on OpenJDK 14 using 
`visualvm -J-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true` 
This disables the JDK version check for unsupported JDK.

**Comment by thurka** [comment]
We plan to add support for JDK 14 in the near future.

**Comment by mr-git** [comment]
Thank you for workaround!
Is there a way to apply this workaround so that it would be possible to launch VisualVM as an app from Finder, not as process from Terminal?

**Comment by ryenus** [comment]
VisualVM on macOS can be launched via `open` with custom options, e.g.:

    open -a /Applications/VisualVM.app --args -J-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true

**Comment by mr-git** [comment]
Partially related to issue #160

**Comment by thurka** [comment]
> Is there a way to apply this workaround so that it would be possible to launch VisualVM as an app from Finder, not as process from Terminal?

You can create `<your_user_directory>/etc/visualvm.conf` file with the following content: 
```
visualvm_default_options="-J-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true ${visualvm_default_options}"
```

Your user directory is available via VisualVM->About VisualVM->Details.

**Comment by mr-git** [comment]
Sadly, it didn't work for me...
May I suggest a small UX enhancement? Maybe in the "Error Starting VIsualVM" dialog there could be second button "Ignore and start" - which would rerun startup logic while ignoring JDK check?

**Comment by ryenus** [comment]
Or just use a supported jdk version, example:

```sh
# ~/Library/Application Support/VisualVM/2.0/etc/visualvm.conf
visualvm_jdkhome=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
```

And make sure to point it to the version you have installed.

**Comment by thurka** [comment]
VisualVM 2.0.1 (with JDK 14 support) was just released. Closing.
