### ISSUE TITLE
Choose the Theme manually

### ISSUE THREAD

**Issue by MahatmaFatalError** [oracle/visualvm#186]
**Is your feature request related to a problem? Please describe.**
Dark theme has some quirks, black text on dark-grey background is unreadable, especially for some plugins, but also in the regular bar at the bottom. Unfortunately, there is no configuration settings so set the theme.

**Describe the solution you'd like**
A switch in the Preferences to choose the theme manually. (and fix the dark theme)

Mac OS Catalina,
VisualVM 2.0.1

**Comment by jisedlac** [comment]
Similar to #124.

Dark theme cannot be enabled/disabled manually in VisualVM. It's a regular Swing application which consumes the actual OS settings.

Please attach screenshots of the concrete problems and eventually provide a short description if not immediately clear from the images. We'll try to address the quirks.

As a workaround until fixed, you can run VisualVM with a cross-platform LaF - Metal or Nimbus. Either use `visualvm --laf Metal` or `visualvm --laf Nimbus` or add the `--laf <LAF_NAME>` switch to the `visualvm_default_options` parameter in `visualvm.conf` configuration file.

**Comment by MahatmaFatalError** [comment]
See these two screenshots:
![image](https://user-images.githubusercontent.com/776825/77951427-5730d600-72ca-11ea-981d-6f2f2e5eb5f1.png)
(Find the label of the progress bar at the bottom)

![image](https://user-images.githubusercontent.com/776825/77951537-821b2a00-72ca-11ea-9841-fe9a15495c73.png)

**Comment by jisedlac** [comment]
Thanks for the screenshots! Can you please specify which JDK version runs the VisualVM? Also, to verify that this is not a problem on JDK side, could you please provide a screenshot of the [JConsole tool](https://docs.oracle.com/javase/8/docs/technotes/guides/management/jconsole.html) on your system?

**Comment by jisedlac** [comment]
Might be related to this JDK bug: https://bugs.openjdk.java.net/browse/JDK-8231438.

Should be fixed in JDK 14 released recently and already supported by VisualVM 2.0.1.

**Comment by MahatmaFatalError** [comment]
> Thanks for the screenshots! Can you please specify which JDK version runs the VisualVM? Also, to verify that this is not a problem on JDK side, could you please provide a screenshot of the [JConsole tool](https://docs.oracle.com/javase/8/docs/technotes/guides/management/jconsole.html) on your system?

I'm running on SapMachine 11.0.6.0.1+10-LTS.

JConsole (from adoptopenjdk8) looks like this 
![image](https://user-images.githubusercontent.com/776825/78003445-ec6ab380-7338-11ea-9f7e-bd8d0aa213f0.png)

**Comment by jisedlac** [comment]
OK, the JConsole screenshot shows that Swing applications (including VisualVM) should be usable with the Catalina dark theme when running on AdoptOpenJDK8 (and likely any other JDK 8), except that still appearing with light colors.

To verify the possible dark theme bug in JDK the JConsole must be running on the same JDK which ran the originally reported VisualVM - SapMachine 11.0.6.0.1+10-LTS according to your info. Please try to run JConsole from this JDK.

**Comment by MahatmaFatalError** [comment]
> OK, the JConsole screenshot shows that Swing applications (including VisualVM) should be usable with the Catalina dark theme when running on AdoptOpenJDK8 (and likely any other JDK 8), except that still appearing with light colors.
> 
> To verify the possible dark theme bug in JDK the JConsole must be running on the same JDK which ran the originally reported VisualVM - SapMachine 11.0.6.0.1+10-LTS according to your info. Please try to run JConsole from this JDK.

Looks similar, however, notice the macOS window frame color. Seems with JDK11 is adheres to the global dark theme.
![image](https://user-images.githubusercontent.com/776825/78029816-7890d100-7361-11ea-8c62-f3cb0cffd4b0.png)

**Comment by jisedlac** [comment]
Based on the screenshot I can see that the JConsole itself still uses light theme. AFAIK the window frame is a native OS component unrelated to Swing.

Definitely there's some difference between the JConsole and VisualVM appearance - JConsole is fully displayed using the light theme, VisualVM seems to partially apply dark theme to some components (panels).

Not sure if the problem is in the JDK itself (have you tried the suggested JDK 14?) or the underlying NetBeans platform, will try to investigate. Either way, this doesn't seem to be fixable on VisualVM side.

For now there are at least two workarounds available until addressed - either use JDK 8 to run VisualVM or switch to a cross-platform Look'n'Feel as suggested above.

**Comment by MahatmaFatalError** [comment]
Thanks for pointing out to JDK14. I tried JDK build 14+36-sapmachine and it seems the issue is fixed:
![image](https://user-images.githubusercontent.com/776825/78057273-bf44f200-7386-11ea-964e-8f8105eaea42.png)
![image](https://user-images.githubusercontent.com/776825/78057293-c8ce5a00-7386-11ea-89dc-b302f8db8dd7.png)

Nevertheless, it would have been nice to at least have a LaF switcher in the UI settings to make this more obvious.
