### ISSUE TITLE
VisualVM unix like launcher typo preventing loading of extra clusters

### ISSUE THREAD

**Issue by jmborer** [oracle/visualvm#190]
There is a typo in in the linux/MacOS launcher `visualvm/launcher/visualvm`

On line 135, it reads:

```
if [ ! -z "$visualvm_extraclusters" ] ; then
    visualvm_clusters ="$visualvm_clusters:$visualvm_extraclusters"
fi
```

The extra space before the "=" on line 135, breaks the script ("command not found" error) and prevents therefore the loading of extra modules which is annoying during development of a new module for VisualVM.

It shall read:

```
if [ ! -z "$visualvm_extraclusters" ] ; then
    visualvm_clusters="$visualvm_clusters:$visualvm_extraclusters"
fi
```

**Comment by thurka** [comment]
Fixed in master.
