### ISSUE TITLE
Profiler calibration hangs "Connecting to target VM..."

### ISSUE THREAD

**Issue by ewingrj** [oracle/visualvm#193]
**Describe the bug**

I am attempting to profile an application, however the profiler hangs and never finishes calibrating.

**To Reproduce**
1. Start the CPU profiler for the first time

**Log File**
[messages.log](https://github.com/oracle/visualvm/files/4558720/messages.log)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS] MacOS 10.15.3
 - JDK version [JDK 1.8.0_181]  open JDK 11.0.6+10
 - Version [e.g. 1.4] 2.0.1

**Comment by thurka** [comment]
Can you provide exact steps, how to reproduce it? I can see you are running VisualVM on `/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home` and not on open JDK 11.0.6+10 mentioned in the bug report.

**Comment by thurka** [comment]
Closing until more info is available.
