### ISSUE TITLE
Truffle optimisation thermometer

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#198]
**Is your feature request related to a problem? Please describe.**
I want to know what Truffle is doing to optimise my code when I'm working on a Truffle language or an application running on Truffle.

**Describe the solution you'd like**
I'd like to be able to see graphs for some metrics I've developed which have been helpful to me.

**Describe alternatives you've considered**
I'm working on a tool that does it at the command line https://github.com/oracle/graal/pull/2091, but being able to attach to a running JVM and seeing it graphically in real-time as well would be useful.

**Additional context**
The metrics are:
* proportion of time spent in compiled code compared to time spent in interpreted code over time, could also separate out time spent in runtime code
* iterations-per-second or requests-per-second being handled by your application
* size of loaded Truffle code
* compilations queued
* compilations running
* compilations finished
* compilations failed
* compilations dequeud
* deoptimisations

These graphs look something like these - my idea is there would be a 'Truffle Monitor' tab next to the 'Monitor' tab to show them.

![72995508-f4661e80-3df0-11ea-9b27-6d8aef7bb9a7](https://user-images.githubusercontent.com/341094/81875987-839e6a00-9579-11ea-897f-55bde3991f9c.png)

As a concrete example, this would allow a user to use VisualVM to see if there is a deoptimisation loop going on, which is a common starting point diagnostic.

**Comment by thurka** [comment]
Closing old issue.
