### ISSUE TITLE
VisualVM does not detect truffle processes (does not display Graal Sampler tab)

### ISSUE THREAD

**Issue by a701440** [oracle/visualvm#199]
I am running Tomcat on GraalVM 20.0 on MacOS and that process is using polyglot to embed javascript in java.
According to the GraalVM documentation VisualVM should show Graal Sampler tab in addition to the regular Sampler. However this UI is not shown. It appears that for it to show the process needs to be detected as "truffle process" (holy grail icon?), however my process is detected as regular Tomcat (tomcat icon). Is there a way to force it to show the "Graal Sampler" tab?

**Comment by thurka** [comment]
If you can rebuild visualvm from sources, the following diff will enable "Graal Sampler" for every local java application.
```
diff --git a/visualvm/sampler.truffle/src/org/graalvm/visualvm/sampler/truffle/SamplerSupport.java b/visualvm/sampler.truffle/src/org/graalvm/visualvm/sampler/truffle/SamplerSupport.java
index 9d8d7455a..e8f22c2d2 100644
--- a/visualvm/sampler.truffle/src/org/graalvm/visualvm/sampler/truffle/SamplerSupport.java
+++ b/visualvm/sampler.truffle/src/org/graalvm/visualvm/sampler/truffle/SamplerSupport.java
@@ -56,7 +56,7 @@ public final class SamplerSupport {
         Jvm jvm = JvmFactory.getJVMFor(application);
         if (!jvm.isBasicInfoSupported() || !jvm.isAttachable()) return false;
         ApplicationType appType = ApplicationTypeFactory.getApplicationTypeFor(application);
-        return appType.getClass().getName().contains("GraalVMApplicationType");
+        return true;
     }
     
     void selectSamplerView(Application application) {
```

**Comment by a701440** [comment]
Actually having some issues building from sources:

/visualvm/core/src/org/graalvm/visualvm/core/explorer/ExplorerNode.java:186: error: no suitable method found for sort(Vector<TreeNode>,ExplorerNodesComparator)

**Comment by a701440** [comment]
In addition a number of steps complained about unsupported javac source and target option 1.5 ( minimum was 1.6).

**Comment by thurka** [comment]
You need to build VisualVM with JDK 8 as stated in readme file.

**Comment by thurka** [comment]
Fixed in master.
