### ISSUE TITLE
macOS application bundle fails to start

### ISSUE THREAD

**Issue by cbfiddle** [oracle/visualvm#20]
Two dialogs are displayed:

(1) Cannot load window system persistent data, user directory content is broken...

(2) Cannot load even default layout, using internally predefined configuration.

After these dialogs are closed, I can display an unhandled exception. Unfortunately, copy does not work, so I will attach a screen shot.

<img width="1079" alt="screen shot 2017-04-11 at 5 31 19 pm" src="https://cloud.githubusercontent.com/assets/6628505/24936280/bde99b60-1edc-11e7-9099-3e0edec02467.png">

**Comment by thurka** [comment]
You are running VisualVM on JDK 9. Please use JDK 8 to run VisualVM or for the latest JDK 9, you need to use the following commandline:

`./visualvm -J--add-opens=java.base/java.net=ALL-UNNAMED -J--add-opens=java.base/java.lang.ref=ALL-UNNAMED -J--add-opens=java.base/java.lang=ALL-UNNAMED -J--add-opens=java.desktop/javax.swing=ALL-UNNAMED -J--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED -J--add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor.event=ALL-UNNAMED`

**Comment by thurka** [comment]
See also #13.

**Comment by cbfiddle** [comment]
I am using a bundled app. Strictly speaking, a bundled app should contain its own JRE.

Otherwise, if it is using java_home, it should specify a parameter to require JDK 8.

Meanwhile, how do I change which JDK it uses without deleting my JDK 9?

**Comment by thurka** [comment]
>Meanwhile, how do I change which JDK it uses without deleting my JDK 9?

See my comment in #13.

**Comment by cbfiddle** [comment]
Thank you. I removed the “~” from the JDK path.

**Comment by cbfiddle** [comment]
Do you already know that CPU sampling and profiling are not working on the latest JDK 9?
CPU sampling not available - cannot access threads.
CPU profiling - crashes at JvmtiConstantPoolReconstituter::JvmtiConstantPoolReconstituter(instanceKlassHandle) + 226
