### ISSUE TITLE
 VisualVM goes into 'computing description' loop if IntelliJ is running

### ISSUE THREAD

**Issue by reuschling** [oracle/visualvm#200]
What steps will reproduce the issue?

    start IntelliJ
    start visualvm afterwards

What is the expected result?
IntelliJ is just shown in the list of local processes in visualvm without going to a long (10minutes?) 'computing description' loop.

What happens instead?
visualvm shows 'computing description' and doesn't show up any local vm processes. If I stop intellij and try again, all other java vms will be displayed in visualvm. One interesting thing is, if I disable my network connection, it works.

Tried with several visualvm versions and plenty of java versions.

IC-201.7223.91, JRE 11.0.6+8-b765.40x64

**Comment by reuschling** [comment]
I've also written an issue to the intellij developers, but they said it is not at their side:
https://youtrack.jetbrains.com/issue/IDEA-240991

**Comment by thurka** [comment]
I just tried your steps to reproduce, but I not able to reproduce it. I guess that there are more things involved that just: 
```
start IntelliJ
start visualvm afterwards
```

**Comment by reuschling** [comment]
So, I proceed checking out, sadly I still can not tell you a way how to reproduce it. I asked three colleagues, two of them have no problems, one of them has the same behavior. The new hints:
1. Independent from intellij, I found out that I am not able to connect to any java process in the process list - rmi connection ist not possible
2. We found a workaround. If I explicitly set -Djava.rmi.server.hostname=localhost  or
-Djava.rmi.server.hostname=127.0.0.1 to the process I want to connect to, it works.

Maybe this hint is enough for an idea what the problem could be?

**Comment by thurka** [comment]
Thanks for the investigation. From your findings, it looks like the problem is interaction between network setup of your computer and JMX. For some reason JMX is not able to setup connection to local java applications. Maybe there is a firewall blocking such connections.

**Comment by reuschling** [comment]
Definitely no firewall, I have double checked. Also, in such a case, it would not starting to work when I set the -Djava.rmi.server.hostname simply to localhost or 127.0.0.1, what should be the default anyway according to the [documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/rmi/javarmiproperties.html).
I now just have set the environment variable 'JAVA_TOOL_OPTIONS=-Djava.rmi.server.hostname=127.0.0.1' that all VMs have this setting that they should have anyway, and all problems disappeared.
This is a good workaround, but it still smells like a bug.

**Comment by thurka** [comment]
> Also, in such a case, it would not starting to work when I set the -Djava.rmi.server.hostname simply to localhost or 127.0.0.1

If you need to set `java.rmi.server.hostname` property to `localhost`, it means that its value computed by JVM is something different and it can be real IP address of your computer. This  address can be blocked by firewall. I am not saying that this is your case, but this can be possible explanation based your information.

**Comment by reuschling** [comment]
Interesting. I had a look: It works also if I set ```java.rmi.server.hostname``` to the pc's ip address instead of localhost.
If I read out this property in java code (```System.getProperty("java.rmi.server.hostname")```), and if I don't specify anything on my own, it's value is ```null```

**Comment by thurka** [comment]
`java.rmi.server.hostname` is used as hint to find host name of local machine. If it is not set, host name of local machine is computed in `sun.rmi.transport.tcp.TCPEndpoint`. To see computed value run VisualVM with `-J-Dsun.rmi.transport.tcp.logLevel=BRIEF -J-Dnetbeans.logger.console=true` and look for
```
localHostKnown = <true/false>, localHost = <localhost_name>
```
If you specify `java.rmi.server.hostname`, `localHostKnown` should be true, `localHost` should be value of `java.rmi.server.hostname`. You can see, what it reports when you don't specify the property and it would be also useful to see, what are the values for your colleagues. Maybe this can give us more infomation to find out, what is going on.

**Comment by reuschling** [comment]
Thanks a lot for the logging flags!
Indeed, VisualVm found somewhere in the system an outdated IP address that was not valid anymore. Nevertheless the network in general worked, the only side effect was on the rmi connection. Due to this hint in the VisualVm logging our network administrator was able to find the broken/outdated config, VisualVm is working now as expected.

**Comment by thurka** [comment]
We know that VisualVM is a useful monitoring tool, but till today I was not aware that it can help debug network problems. :-) Thanks for sharing this interesting story.
