### ISSUE TITLE
How to integrate startup profiler for Wildfly 19

### ISSUE THREAD

**Issue by JohannesMayrRSG** [oracle/visualvm#204]
For startup profiling a **Wildfly-19** via **VisualVM** and **StartupProfiler-plugin** there is no documentation available. I spent many hours to do this and now it's running - please update your documentation.

**Solution (Windows10-x64)**
First, add following 2 lines at bottom of _<WILDFLY_HOME>/bin/standalone.conf.bat_

- set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.logmanager,org.graalvm.visualvm.lib.jfluid.server -Xbootclasspath/a:%JBOSS_HOME%/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-2.1.14.Final.jar;%JBOSS_HOME%/modules/system/layers/base/org/wildfly/common/main/wildfly-common-1.5.2.Final.jar;%JBOSS_HOME%/standalone/lib/ext/jfluid-server.jar -Dsun.util.logging.disableCallerCheck=true -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

- set "JAVA_OPTS=%JAVA_OPTS% -agentpath:**<VISUALVM_HOME>**/visualvm/lib/deployed/jdk16/windows-amd64/profilerinterface.dll=**<VISUALVM_HOME>**/visualvm/lib,5148"

(!) replace **<VISUALVM_HOME>** with corresponding installation path of **VisualVM** (!)

Finally, copy _**<VISUALVM_HOME>**/visualvm/lib/jfluid-server.jar_ into _<WILDFLY_HOME>/standalone/lib/ext_

**Comment by jisedlac** [comment]
Hi, thanks for letting us know! We only provide generic instructions on how to configure the profiled application. Dedicated documentation of each concrete product must be followed to implement our configuration.
