### ISSUE TITLE
Make an option to use regular expression in Class Filter

### ISSUE THREAD

**Issue by pflaska** [oracle/visualvm#205]
When searching classes, usually I remember either part of package and class name or some words from class name, e.g. JDBC and Info in package ucp:
oracle/ucp/jdbc/JDBCConnectionRetrievalInfo.java
oracle/ucp/jdbc/oracle/OracleJDBCConnectionRetrievalInfo.java
oracle/ucp/jdbc/oracle/rlb/OracleDatabaseInstanceInfo.java

Provide an class filter option to use regular expression in the field.

**Comment by jisedlac** [comment]
Related to the heap viewer, Regular Expression filter is available in profiler results/snapshots.

**Comment by jisedlac** [comment]
Heap viewer now provides Regular Expression filter in Java Objects, OQL results and Truffle Objects.

Fixed in master.
