### ISSUE TITLE
Local Java Applications cannot be detected

### ISSUE THREAD

**Issue by sairaghavak** [oracle/visualvm#206]
Hi 

I am using **adopt-openjdk-11-with-openj9-jvm\jdk-11.0.7+10**

Steps to reproduce the issue
1. Download the latest [Visual VM zip](https://visualvm.github.io/download.html)
2. Unzip 
3. Goto bin folder
4. CMD into folder and run `visualvm.exe --jdkhome "<your jdk home path here>"`
5. Once it is launched, at it's startup in the UI, it threw error **Local Java applications cannot be detected**

As mentioned here in this link: https://visualvm.github.io/troubleshooting.html
Tried to update this value **PerfBypassFileSystemCheck**  in **visualvm.conf** still the same.

Am I missing something, please let me know.
Same problem: https://stackoverflow.com/questions/49160051/visualvm-local-java-applications-cannot-be-detected
But that answer didn't work for me.

**Comment by jisedlac** [comment]
The problem seems to be in the implementation of how OpenJ9 detects running Java processes. It doesn't seem to be compatible with the standard jvmstat used by VisualVM.

Not a bug on VisualVM side, OpenJ9 is not a supported Java platform.

**Comment by thurka** [comment]
Running VisualVM on OpenJ9 is not supported. If want to monitor OpenJ9, you have to use JMX. See [this stackoverflow](https://stackoverflow.com/questions/57473025/using-visualvm-with-adoptopenjdk-and-openj9/57489335#57489335) question for more details.
