### ISSUE TITLE
Add invocation count to remote profiling/sampling

### ISSUE THREAD

**Issue by quazgar** [oracle/visualvm#207]
**Is your feature request related to a problem? Please describe.**
When remotely profiling a Java program via JMX, one method consumes a lot of time.  It would be extremely helpful to me if I saw how often this method is being called.

**Describe the solution you'd like**
There should be an additional column with the number of invocations

**Describe alternatives you've considered**
So far, I've only worked with attaching a debugger to the method.

**Comment by jisedlac** [comment]
VisualVM only supports remote sampling, not profiling. When sampling CPU, there's no exact information about the invocation counts available by nature of the approach.

You can display the Hits column which is already available and hidden by default to see the how many times the method has been seen on the stack when sampling.

**Comment by top-logic** [comment]
How can I unhide the "Hits" column. I do not found any setup for this.

**Comment by thurka** [comment]
> How can I unhide the "Hits" column. I do not found any setup for this.

Click on the triangle on the right side of the table and select the appropriate column. See attached picture:
![hits](https://user-images.githubusercontent.com/22048069/135599947-352c7cc2-9ccc-448f-8415-8e4ff82b52fe.png)
