### ISSUE TITLE
java.lang.NoClassDefFoundError: org/graalvm/visualvm/lib/jfluid/server/ProfilerRuntimeCPUFullInstr

### ISSUE THREAD

**Issue by ram3shpala** [oracle/visualvm#209]
**Describe the bug**
Throws class not found exception WAS Liberty App Server, while CPU Profiling
ERROR Bundle:com.ibm.ws.event(id=13) java.lang.NoClassDefFoundError: org/graalvm/visualvm/lib/jfluid/server/ProfilerRuntimeCPUFullInstr

**To Reproduce**
Open VisualVM
1. Go to '**Profiler**' tab
2. Click on 'CPU'
3. Navigate back to the application deployed on WAS Liberty App Server, Click on a link to fetch data
4. The application is crached and throws exception :
ERROR Bundle:com.ibm.ws.event(id=13) java.lang.NoClassDefFoundError: org/graalvm/visualvm/lib/jfluid/server/ProfilerRuntimeCPUFullInstr

**Expected behavior**
Application shouldn't be crashed while CPU profiling

**VisualVM log**
This message is thrown by the Application Server Liberty:
ERROR Bundle:com.ibm.ws.event(id=13) java.lang.NoClassDefFoundError: org/graalvm/visualvm/lib/jfluid/server/ProfilerRuntimeCPUFullInstr

**Screenshots**

**Desktop (please complete the following information):**
   -visualvm_202
 - OS: [Windows 10]
 - JDK version [JDK 1.8.0_121]
 

**Additional context**

**Comment by thurka** [comment]
What is "WAS Liberty App Server"? Does it have some connection to JBoss/WildFly?

**Comment by thurka** [comment]
The error looks very similar to JBoss/WildFly. JBoss has to be started with "-Djboss.modules.system.pkgs=org.jboss.byteman,org.graalvm.visualvm.lib.jfluid.server" system property to allow loading of profiler classes from `org.graalvm.visualvm.lib.jfluid.server` package. Maybe something similar can be done for WebSphere Liberty because it also uses OSGI framerowk with boot delegation.

**Comment by ram3shpala** [comment]
Thanks for update. Appreciate quick response.
Added  -Dorg.osgi.framework.bootdelegation=org.graalvm.* to Liberty Server its working now.

**Comment by rjdkolb** [comment]
The only way this `-Dorg.osgi.framework.bootdelegation=org.graalvm.*` worked is by added this to my bootstrap.properties. It did not work when I made this a JVM arg when running the jar or adding it to my jvm.options file

**Comment by aIbrahiim** [comment]
I got the same error but with wildfly

**Comment by srl295** [comment]
> The only way this `-Dorg.osgi.framework.bootdelegation=org.graalvm.*` worked is by added this to my bootstrap.properties. It did not work when I made this a JVM arg when running the jar or adding it to my jvm.options file

To be precise, adding the following to `bootstrap.properties` works for OpenLiberty.

```
org.osgi.framework.bootdelegation=org.graalvm.*
```
