### ISSUE TITLE
Tracking VMs started by other users

### ISSUE THREAD

**Issue by ir0kez** [oracle/visualvm#211]
Most of the time I start jar files with "runas" (win10 cmd line feature).
There's no way of tracking such created VMs in current version of VisualVM (they just don't exist).
Would be nice to have such feature, since I bound to start my JARs under different users.

**Comment by thurka** [comment]
You have several options:

1. you can start VisualVM with "runas" the same way as your jar.
2. you can run `jstatd` with "runas" and then add `Jstatd connection` via context menu on "Local" node
3. you can monitor your jar using JMX. You need to explicitly enable JMX monitoring when starting your jar and then add `JMX connection` via context menu on "Local" node
