### ISSUE TITLE
CPU load, Threads and Sampling are not available on AdoptOpenJDK 1.8.0_232

### ISSUE THREAD

**Issue by VGoudkov** [oracle/visualvm#212]
**Describe the bug**
CPU load view, Threads are not available on AdoptOpenJDK 1.8.0_232, AdoptOpenJDK 11 for my apps, but are available for (example) IDEA and VisualVM itself. Not available for some 3rd party software.
Sampler tab Summary:
CPU sampling: Not available. Failed to create JMX connection to target application. Use 'Add JMX Connection' action to attach to the application.
Memory sampling: Available (perform GC not supported, thread memory allocation not supported). Press the 'Memory' button to start collecting memory data.

**To Reproduce**
1. Create a simple app like 
public class Aaa {
    public static void main(String[] args) throws InterruptedException {
        long l = 0;
        while (true){
            Thread.sleep(2_000);
            System.out.println(++l);
        }
    }
}
2. Run it with IDEA or separately
3. Open it with VisualVM
4. See  "Not supported for this JVM" in Monitor/CPU view, no Threads tab displayed. 

**Expected behavior**
A "normal" CPU, Threads and Sampler / Profiler behavior

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

**Desktop (please complete the following information):**
 - OS: [Windows 10.0.18363]
 - JDK version [AdoptOpenJDK 1.8.0_232]
 - Version [e.g. 1.8]

**Comment by thurka** [comment]
Please attach VisualVM messages.log file to help diagnose your problem.

**Comment by VGoudkov** [comment]
Here it is
[logfile.txt](https://github.com/oracle/visualvm/files/4850825/logfile.txt)
![forSQLWB](https://user-images.githubusercontent.com/19290633/86110602-72300380-bace-11ea-8bb6-064fdccd9068.png)

**Comment by thurka** [comment]
Thanks, I assume that the messages.log file was taken after you opened `SQLWorkbench` application. Am I right?
Since the messages.log file does not contain anything suspicions, can you please take an application snapshot of `SQLWorkbench` application and attach it to this issue. Thanks.

**Comment by VGoudkov** [comment]
I hope this is is one you asked for...
[application-1593553258620.zip](https://github.com/oracle/visualvm/files/4854551/application-1593553258620.zip)

**Comment by VGoudkov** [comment]
Another app snapshot
[application-1593555791346.zip](https://github.com/oracle/visualvm/files/4854669/application-1593555791346.zip)

**Comment by thurka** [comment]
> I hope this is is one you asked

Yes, thanks. Unfortunately it is still unclear, what is going on. So I have more questions.

What is the difference between those apps which are OK and those, which does not work?
Is `jconsole` able to connect to application, where "CPU load view" is not available?
Are you using 3rd-party firewall, which can block connection between VisualVM and monitored application?
Can you please start VisualVM from console using the following command:
```
C:\opt\visualvm_202\bin\visualvm.exe --jdkhome C:\opt\jdk-8.0.232.09-hotspot -J-Dnetbeans.logger.console=true -J-ea -J-Dorg.graalvm.visualvm.level=100
```
After VisualVM starts, start your test application and open it in VisualVM. Quit VisualVM and attach the full output from console. Thanks.

**Comment by jisedlac** [comment]
Tested using the provided simple app Aaa on Windows 10 and AdoptOpenJDK 1.8.0_232 installed using the .msi installer. Tried to mimic the Russian environment. Ran using both the main class and a .jar file. Everything worked as expected on my side.

**Comment by VGoudkov** [comment]
I found that the problem disappeared when the Cisco Anyconnect VPN was switched off after restart. When it was  ON again - the problem returned.
Here is a log of the "problem" run. 
[run-vpn.log](https://github.com/oracle/visualvm/files/4858653/run-vpn.log)

Unfortunately when I tried to run in again without VPN to collect another log - Windows displayed me the message "This app can't run on your PC". Why?

**Comment by VGoudkov** [comment]
> Unfortunately when I tried to run in again without VPN to collect another log - Windows displayed me the message "This app can't run on your PC".
Fixed by unpacking whole folder from zip archive

**Comment by VGoudkov** [comment]
More answers:

> What is the difference between those apps which are OK and those, which does not work?

I don't know. The VisualVM itself, IntelliJ IDEA are opened correctly, with and without activated VPN. The same time other apps are displayed in "reduced" mode

> Is `jconsole` able to connect to application, where "CPU load view" is not available?

No.

> Are you using 3rd-party firewall, which can block connection between VisualVM and monitored application?

No. But the problem exists when I'm using a VPN connection to my office. Unfortunately, the DB server to work with is located there, so I can't close the connection and profile my DB utility

**Comment by thurka** [comment]
> I found that the problem disappeared when the Cisco Anyconnect VPN was switched off after restart. When it was ON again - the problem returned.

With Cisco Anyconnect VPN, you cannot mix application started before VPN connection with those started after VPN was connected. So quit all java application, start Cisco Anyconnect and connect to VPN, start java applications.

**Comment by VGoudkov** [comment]
No, the "program to monitor" and JVM are started after the VPN
Have created another test with my first "Aaa" class.
![image](https://user-images.githubusercontent.com/19290633/86345035-aee13380-bc63-11ea-8449-26c0f354be91.png)
At the same time IDEA, VisualVM are monitored normally.
![image](https://user-images.githubusercontent.com/19290633/86345509-4a72a400-bc64-11ea-8a37-e17317ef65d4.png)
So there is some difference but I can't find it.

**Comment by thurka** [comment]
> No, the "program to monitor" and JVM are started after the VPN

What do you mean by 'JVM are started after the VPN'? What kind of Java Virtual Machine did you start?

**Comment by VGoudkov** [comment]
>With Cisco Anyconnect VPN, you cannot mix application started before VPN connection with those started after VPN was connected. So quit all java application, start Cisco Anyconnect and connect to VPN, start java applications.
> What do you mean by 'JVM are started after the VPN'? What kind of Java Virtual Machine did you start?

Both applications ( VisualVM and JVM with my test app) were started after the VPN

**Comment by thurka** [comment]
Can you try to run your test app with `-Djava.net.preferIPv4Stack=true`?  IDEA is using it too and maybe this the reason why IDEA can be monitored and your test app cannot.

**Comment by VGoudkov** [comment]
>Can you try to run your test app with -Djava.net.preferIPv4Stack=true

No, it doesn't help. 
Another hint: my local printer (in the home WiFi net) is not available while VPN is on.

**Comment by VGoudkov** [comment]
I see. What is the difference between the CPU view (which is not displayed) and the Heap view (which is displayed)? Does this CPU connector use additional ports and/or network options? Maybe the monitored app opens additional sockets (something provided by VisualVM, or uses different protocols)?

**Comment by thurka** [comment]
CPU view uses JMX, Heap view uses Jvmstat.

**Comment by VGoudkov** [comment]
Should I change the bug description? From AdoptOpenJDK to Cisco AnyConnect problem?

**Comment by VGoudkov** [comment]
Some network research:
**Without VPN**
```
netstat -a -n -o | find "10428" (10428 - PID of the monored app)
  TCP    0.0.0.0:56066          0.0.0.0:0              LISTENING       10428
  TCP    192.168.175.1:56066    192.168.175.1:56067    ESTABLISHED     10428
  TCP    [::]:56066             [::]:0                 LISTENING       10428
```
where 192.168.175.1 - the address of VMWare player VMNet8 adapter (not my local IP address)

**With VPN**
```
netstat -a -n -o | find "28300" (28300 - PID of the same app, started after VPN connection)
  TCP    0.0.0.0:56268          0.0.0.0:0              LISTENING       28300
  TCP    [::]:56268             [::]:0                 LISTENING       28300
```

**Comment by thurka** [comment]
I think you have take advantage of the fact that IDEA works. So why not run your test application on the same JDK as IDEA and with the same JVM options as IDEA?

**Comment by VGoudkov** [comment]
A solution found: adding `-Djava.rmi.server.hostname=127.0.0.1` for local run / monitoring solves the problem. This argument is not required without AnyConnect VPN

**Comment by thurka** [comment]
Ok, thanks for info.

**Comment by dennis-sig** [comment]
@VGoudkov Sorry for asking a maybe obvious question, but do you add the system property for your own application or for VisualVM?

**Comment by VGoudkoff** [comment]
> @VGoudkov Sorry for asking a maybe obvious question, but do you add the system property for your own application or for VisualVM?

Hi! For my own application. 

On our pre-production we are using the following set of properties to run the app:
```
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 \
        -Dfile.encoding=utf-8 \
        -Dcom.sun.management.jmxremote \
        -Dcom.sun.management.jmxremote.port=9010 \
        -Dcom.sun.management.jmxremote.local.only=false \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false\
	-Djava.rmi.server.hostname=<server_ip_address>
```
These allow us  to connect via IDEA's debugger and/or VisualVM remotely
