### ISSUE TITLE
visualvm --locale zh:CN is not work in 2.0.3 on macos

### ISSUE THREAD

**Issue by DalianRollingKing** [oracle/visualvm#217]
when i  open application visualvm  it is show in english ,so i use ./visulavm --locale zh:CN ,it also show english .how can i use it in chinese.

**Comment by thurka** [comment]
VisualVM is no longer releases with localisation. The last localised version is 1.3.9. You can download VisualVM 1.3.9 ML here: https://visualvm.github.io/releases.html
