### ISSUE TITLE
Local Java applications cannot be detected

### ISSUE THREAD

**Issue by elmsleypass** [oracle/visualvm#219]
**Describe the bug**
When starting up the tool it says that

**Expected behavior**
It detects my applications.

**VisualVM log**
no logs.

**Screenshots**
<img width="919" alt="image" src="https://user-images.githubusercontent.com/27940209/88289867-e3c13300-ccc3-11ea-909f-1e2e4629f63a.png">

**Desktop (please complete the following information):**
 - OS: [MacOS 10.15.5]
 - JDK version [JDK 1.8.0_181]
 - Version [2.0.3]

**Additional context**

**Comment by thurka** [comment]
Please attach VisualVM log. Thanks.

**Comment by thurka** [comment]
Closing until more information is available from reporter.
