### ISSUE TITLE
Cannot select any option in visualvm

### ISSUE THREAD

**Issue by pratts** [oracle/visualvm#22]
Hello,
I recently download the visualvm 1.3.8. But after starting the application, I can choose the application to monitor but unable to select any of the options in the menu bar. Menu buttons are clickable but the menu closes the moment I try to select any option.

java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

OS : Centos 7

**Comment by jisedlac** [comment]
Hello, could you please run another Swing application using your Java 1.7.0_60 to see whether it suffers from the same bug? For example <1.7.0_60_home>/bin/jconsole . I suspect this won't be related to just VisualVM.

Another tip is to try running the VisualVM from your JDK - <1.7.0_60_home>/bin/jvisualvm.

Is there any way you could use the latest JDK 8 Update 121 and VisualVM 1.3.9?

**Comment by pratts** [comment]
The same thing is happening with both jconsole and jvisualvm.
When the above mentioned apps start, I can select the options for sometime, but it stop working after a few minutes.
Do you have any idea about the problem ?

**Comment by jisedlac** [comment]
I assume this is caused by some incompatibility between the Java AWT and OS window manager. I'd suggest to check for OS updates and try using the latest Java 8. Other than that, I won't be of any assistance, I'm sorry.
