### ISSUE TITLE
TDA plugin for VisualVM 2.0

### ISSUE THREAD

**Issue by irockel** [oracle/visualvm#224]
I finally managed to adjust TDA plugin to work with VisualVM 2.0, find updated packages here:

https://github.com/irockel/tda/releases/tag/2.4

**Comment by jisedlac** [comment]
Minor updates to the TDA modules requested in https://github.com/irockel/tda/issues/20.

**Comment by thurka** [comment]
TDA plugin was added to VisualVM 2.0.4 plugin center.
