### ISSUE TITLE
No JMX connection with jstatd and Java 11

### ISSUE THREAD

**Issue by Verdoso** [oracle/visualvm#225]
**Describe the bug**
When I connect to a host that has jstatd installed, VisualVM is able to connec to the applications running there with Java 8 through JMX and display the CPU usage, MBeans etc. The applications running Java 11 with the same properties are displayed but the CPU panel shows the "Not supported for this JVM" message.
If I add manually a JMX connection to the Java 11 running application, the CPU/MBeans panels are displayed correctly.

**To Reproduce**
Set up a host with two applications, one running under Java 8 and another running under Java 11 and run them with the following properties:
```
-Djava.rmi.server.hostname=`hostname -f`
-Dcom.sun.management.jmxremote=true
-Dcom.sun.management.jmxremote.port=0
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
-Djava.net.preferIPv4Stack=true
```
Start jstatd in the host. Connect to the host using VMConsole. The Java 8 applications is able to display the CPU panel, the Java 11 is not.

**Expected behavior**
I would expect jstatd to be able to connect with JMX automatically to the Java 11 application, the same way it does to the application running under Java 8.

**VisualVM log**
No error or warning whatsoever in the message.log, I can attach a sample later if needed.

**Desktop (please complete the following information):**
 - OS: VisualVM running in W10, hosts running Linux
 - JDK version: VisualVM tested with Java 8 and 11, applications running 1.8.0_222/11.0.4 AdoptOpenJDK 
 - Version: Tested with 1.4.4, 2.0.4 and master

**Additional context**
The same applications were working fine before being recompiled and run with Java 11.

I searched for new properties or differences in JDK11 vs JDK8 regarding jstatd, JMX properties etc. and found nothing that might explain that.

Edited to change local.only to prevent confusions.

**Comment by thurka** [comment]
This:
```
-Dcom.sun.management.jmxremote.local.only=true
```
looks suspicious to me. Why it is set to true?

**Comment by Verdoso** [comment]
Sorry, those are the settings I tried in a test. I tested with both that set to true and false, no change.
It is set to false

**Comment by thurka** [comment]
There seems to be another bug in JDK. On JDK 11 JMX connection exported via jvmstat uses simple name of remote host, while JDK 8 uses a fully qualified domain name. So once your local host (Window?) is able to resolve remote host (Linux?) using simple name of remote host, JMX will work again in JDK 11.

Side note:
both `-Dcom.sun.management.jmxremote=true` and `-Dcom.sun.management.jmxremote.local.only=false` are unnecessary.

**Comment by Verdoso** [comment]
Can that exported name be influenced by java.rmi.server.hostname or any other property?

**Comment by thurka** [comment]
It looks like it it is Linux specific and also depends on Linux network configuration. If `hostname` returns fully qualified domain name, it works fine.

**Comment by Verdoso** [comment]
Great, thanks, I'll try to configure the hosts so hostname returns the FQN and see if that solves it.
Many thanks for traking it.

**Comment by Verdoso** [comment]
Looking into it, hostname seems to be expected to return the simple name and return the FQDN when called with hostname --fqdn so changing it might break other software... there should be some other way to export the "public name" that should be used by jvmstat.
That reminds me of the typical issues with RMI and public/private names...

**Comment by thurka** [comment]
> Looking into it, hostname seems to be expected to return the simple name and return the FQDN when called with hostname --fqdn

Yes, I know, I am just telling how the current implementation in JDK 11 probably works. If you are afraid to change output of `hostname`, configure your Windows to resolve your Linux short name. This definitely does not break anything.

**Comment by Verdoso** [comment]
Yeah, I was just trying to come up with something in the server not to have to change things in each client... but as a workaraound, it will do. Have you filed a bug/enhancement in the JDK that I can follow? Using java.rmi.server.hostname if set would be coherent with other parts of the JDK and would be a nice enhancement, IMHO.

**Comment by thurka** [comment]
> Yeah, I was just trying to come up with something in the server not to have to change things in each client

It turns out that you can use system property `com.sun.management.jmxremote.host` to set hostname for exported JMX connection.

**Comment by thurka** [comment]
Both system properties are probably needed (depending on your Linux machine setup).

**Comment by Verdoso** [comment]
I have added the `com.sun.management.jmxremote.host` property to to the applications and I can see the CPU panels again with Java 11.
Great!
Many thanks!

**Comment by thurka** [comment]
You are welcome. :-)

**Comment by Gulats** [comment]
@Verdoso could you please share the final jmx configs that worked for you..?

**Comment by Gulats** [comment]
actually ignore, got it working with 😅 
```-Dcom.sun.management.jmxremote.host=localhost -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=7878 -Dcom.sun.management.jmxremote.port=7878 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false```
