### ISSUE TITLE
Loosing all remembered connections on upgrade.

### ISSUE THREAD

**Issue by mihxil** [oracle/visualvm#229]
**Describe the bug**
Everytime I install a new version of visual vm, I have to recreate all jmx connections (which is btw still a bit of cumbersome process)

**To Reproduce**
1. Add a service:jmx... connection, and make sure it works.
2. You can now stop and start visualvm, and it will appear again and you can open it.
3. Now upgrade e.g. from 2.0.3 to 2.0.4 and all these 'bookmarks' disappeared

**Comment by jisedlac** [comment]
You are right, re-creating the settings with each VisualVM update is annoying. Should be addressed by some kind of settings migration.

As a workaround until available, you can easily migrate your JMX connections (and hosts, application snapshots etc.) manually: use Help | About | Details in the old VisualVM version to see where its User directory is. Find the "repository" folder in this directory and copy it to the User directory of the new VisualVM.

**Comment by thurka** [comment]
Fixed in master.

**Comment by manueljordan** [comment]
Excellent news, it must close my issue too:

* https://github.com/oracle/visualvm/issues/239
