### ISSUE TITLE
Any way we can use command line for visualVM?

### ISSUE THREAD

**Issue by sampalomad** [oracle/visualvm#230]
Hi developers of visualVM,

**Background:**
It is a great piece of tool! But we want to do CPU time profiling for thousands of java classes in a software.

It is very time-consuming and laborious to put a class or a method to be profiled in the GUI and monitor it, and continue doing this for thousands of times.

**Question:**

Is there a programmable way we can automatically feed the classes we want to profile one by one into the visualVM and extract the profiling information? Such as using a pure command line or some kind of API?

Thank you very very much!!!

**Comment by jisedlac** [comment]
There's no command line support to configure a profiling session.

You can use Tools | Options | Profiling to define a profiling preset and select it later for a profiling session so you don't have to repeat it thousands of times.

**Comment by sampalomad** [comment]
Thanks! @jisedlac sadly I didn't find tutorial to do that.

So should I just put all the classes I want to profiling in there to start?

Where can I start if I want to add command line support to configure a profiling session? (sadly I didn't find much documentation)
