### ISSUE TITLE
Can I ship plugins by default?

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#232]
I ship a build of VisualVM within my company as part of a GraalVM build.

Is it possible to ship it with some plugins already installed somehow? I want to ship the go-to-source plugin available by default.

**Comment by thurka** [comment]
You can manually install the plugin into VisualVM, which is part of GraalVM. To do so follow these steps:

1. go to https://visualvm.github.io/pluginscenters.html
2. download plugin nbm file `org-graalvm-visualvm-sources.nbm` for off-line installation
3. extract the nbm file somewhere (nbm is a zip archive)
4. copy `netbeans/config/Modules/org-graalvm-visualvm-sources.xml` to `lib/visualvm/visualvm/config/Modules/` in GraalVM installation
5. copy `netbeans/modules/org-graalvm-visualvm-sources.jar` to `lib/visualvm/visualvm/modules/` in GraalVM installation
6. start VisualVM from `bin/jvisualvm` and it should have go-to-source plugin available by default.
