### ISSUE TITLE
Struggling to get go-to-source working

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#233]
I'm struggling to get go-to-source working with a TruffleRuby app. Everything comes out like

<img width="567" alt="Screenshot 2020-09-01 at 23 30 57" src="https://user-images.githubusercontent.com/341094/91912511-3589af80-ecab-11ea-8a7d-91790ac69698.png">

I must not have the sources attached at the right root. Can I get VisualVM to show me what it thinks the source location is, and what options it tried to open it, so I can figure it out?

**Comment by chrisseaton** [comment]
I can get it to work with a simple single file in the working directory.

**Comment by jisedlac** [comment]
Could you please provide a sample application and steps to reproduce the problem? Support for the Truffle languages is experimental and bugs are expected to exist.

**Comment by thurka** [comment]
Any update on how to reproduce the problem?

**Comment by thurka** [comment]
Closing old issue.
