### ISSUE TITLE
Incorrect CPU usage reported

### ISSUE THREAD

**Issue by keithc-ca** [oracle/visualvm#235]
**Describe the bug**
CPU usage values are scaled by `OperatingSystemMXBean.ProcessingCapacity` (when that attribute is present).
Instead, average increases of `OperatingSystemMXBean.ProcessCpuTime` per second should be expected to be between
0 and `OperatingSystemMXBean.ProcessingCapacity`.

**To Reproduce**
1. Using an OpenJ9 JVM, start a Java application, enabling JMX access via the normal system properties.
2. Start VisualVM and connect via JMX to that application.
3. Observe the CPU usage graph which shows 100% even when the application is idle.

This problem is not seen with Hotspot because it does not provide the `OperatingSystemMXBean.ProcessingCapacity` attribute.

**Expected behavior**
The CPU usage graph should reflect actual use.

**Desktop (please complete the following information):**
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200728_727 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
```

**Proposed solution**
https://github.com/oracle/visualvm/compare/master...keithc-ca:capacity

**Comment by thurka** [comment]
Thanks for the report. This was working fine for OpenJ9 before. What is different now?

**Comment by keithc-ca** [comment]
I can't find any changes related to the value returned for `OperatingSystemMXBean.ProcessingCapacity` since OpenJ9 was first open-sourced (three years ago). When was 'before'?

**Comment by thurka** [comment]
Support for CPU monitoring of IBM JDK was added 10 years ago: [bugfix #386, process cpu time extracted from IBM JDK ](https://github.com/oracle/visualvm/commit/700f2b593834b0e5cda60c989bbda54a2b5b6590)

**Comment by thurka** [comment]
Ok, found it - `OperatingSystemMXBean.ProcessCpuTime` was not returning time in nano-seconds. To fix I need to also use `OperatingSystemMXBean.ProcessCpuTimeByNS`.

**Comment by keithc-ca** [comment]
There was a time that `OperatingSystemMXBean.ProcessCpuTime` was reported in units of 100ns (and can still be arranged by using `-Dcom.ibm.lang.management.OperatingSystemMXBean.isCpuTime100ns=true`). That changed ~3.5 years ago for compatibility with Hotspot. The `ProcessingCapacity` value is `(100 * #processors)` so on a machine with one CPU that would work, but it's still not right in general.

`ProcessCpuTimeByNS` is deprecated (forRemoval=true); I think just removing the multiplier should work on all (current) JVMs.

**Comment by keithc-ca** [comment]
I don't believe the fix is correct: see https://github.com/oracle/visualvm/commit/644cfe3295e12f23e70d64c3b13ec6c473553664#r42075405.

**Comment by thurka** [comment]
The code is based on the documentation of `PROCESSING_CAPACITY_ATTR` and I believe it is correct. Note that scaling is only active when `PROCESSING_CAPACITY_ATTR` is not CPUs * 100.

**Comment by keithc-ca** [comment]
Under what circumstances would `processingCapacity` be different from 1.0 (on any VM of any vintage)?
If the answer is 'never', I don't see the point of that field.
