### ISSUE TITLE
When a remote application is available, the GUI just hangs if I click on anything in the remote tree icons

### ISSUE THREAD

**Issue by hanzo2001** [oracle/visualvm#245]
**Description**
VisualVM completely hangs when I click on any element of the remote branch on the Applications panel, but only if I am running a remote application.

**To Reproduce**
1. Start VisualVM, configure the SOCKS proxy as indicated in [https://ericdraken.com/profile-remote-java-apps-jdk-11-visualvm/](https://ericdraken.com/profile-remote-java-apps-jdk-11-visualvm/)
2. The remote branch is populated with Jstatd
3. Start the remote application
4. Try to click on anything regarding the Remote branch

_Extra info_
- The entire application hangs: I cannot even close the window (I can stop visualvm by interrupting from the terminal).
- If I kill the remote application, after a few minutes visualvm comes back to life.

**Expected behavior**
Either that visualvm should start working as expected or the application shouldn't hang completely and an error message might be prudent.

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.
[messages.log](https://github.com/oracle/visualvm/files/5395514/messages.log)

**Screenshots**
Just one image that shows the Application tree and the Remote branch. Any click in that area while the remote application is available will cause the hang.
![Screenshot at 2020-10-15 20-16-11](https://user-images.githubusercontent.com/2978880/96179351-a7028200-0f28-11eb-9a0b-81ac72465bad.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3 Sylvia
 - openjdk version "11.0.5" 2019-10-15
 - OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-2ubuntu116.04)
 - VisualVM Version 2.0.4

**Additional context**
- The provided link in step one explains that connectivity can be achieved through a SOCKS proxy and I was successful in setting that up. My remote application runs inside a cloud provided instance. The java version is virtually the same (openjdk version "11.0.8" 2020-07-14)
- This looks like some kind of connectivity problem. The hanging looks like some process is waiting for some kind of network timeout.
- The SOCKS proxy was set up with `ssh -v -D 9000 remote-ip`.
- I don't know how to debug any connectivity issues between VisualVM and my remote application, the error messages aren't helping either. Is there any way to diagnose such issues?

**Comment by thurka** [comment]
[messages.log](https://github.com/oracle/visualvm/files/5395514/messages.log)

**Comment by thurka** [comment]
> I don't know how to debug any connectivity issues between VisualVM and my remote application, the error messages aren't helping either. Is there any way to diagnose such issues?

Please take a thread dump of the hung visualvm process and attach it to this issue.

**Comment by thurka** [comment]
Please take a thread dump of the hung visualvm process and attach it to this issue, so we can investigate this issue. Thanks.

**Comment by hanzo2001** [comment]
Sorry. I think this issue should be closed. I do not have access to that project anymore. I also believe from acquired experience that there must be something in the network that is dropping packets (some firewall).

The only thing that is strange is the fact that the app does not show some kind of visual feedback of the delay and that it should in fact timeout.
