### ISSUE TITLE
VisualVM does not support OpenJDK 15

### ISSUE THREAD

**Issue by triceo** [oracle/visualvm#246]
**Is your feature request related to a problem? Please describe.**
VisualVM 2.0.4 can not be used with OpenJDK 15 which has already been out for more than a month.

**Describe the solution you'd like**
The OpenJDK 15 switch is flipped somewhere in the codebase.

**Describe alternatives you've considered**
Disable JDK version checking altogether. Warn of using an unsupported version, but make it possible.

**Comment by thurka** [comment]
You can start VisualVM 2.0.4 on OpenJDK 15 using
`visualvm -J-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true`
This disables the JDK version check for unsupported JDK.
Note that VisualVM 2.0.4 does not need to be running on OpenJDK 15 to be able to monitor OpenJDK 15  processes.
JDK 15 will be supported by next VisualVM version. See GH-220.
