### ISSUE TITLE
ClassCastException when profiling SQL

### ISSUE THREAD

**Issue by leonardobsjr** [oracle/visualvm#247]
**Describe the bug**
When profiling JDBC connections, sometimes i get a ClassCastException.

**To Reproduce**
1. Start VisualVM
2. Click on PID
3. Profile the JDBC connections on the application

**Expected behavior**
Expected to see SQL's showing, but VisualVM freezes and my application Freezes too.

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your [problem.]
[messages.zip](https://github.com/oracle/visualvm/files/5431594/messages.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10.1
 - JDK version AdoptOpenJDK 11.0.8
 - Version 2.0.4

**Additional context**
- The application being profiled is a Java7 JBoss 5.1 application.
- VisualVM gives this errors for some parts of the Application, but not for all of them.
- I traced this error to a Netbeans Jira: https://issues.apache.org/jira/browse/NETBEANS-402
- Log of JBoss Attached - [jboss.tar.gz](https://github.com/oracle/visualvm/files/5438532/jboss.tar.gz).

**Comment by thurka** [comment]
Thanks for the report. If this is similar to netbeans bug, can you please attach the ClassCastException from your JBoss 5.1 server?

**Comment by leonardobsjr** [comment]
> Thanks for the report. If this is similar to netbeans bug, can you please attach the ClassCastException from your JBoss 5.1 server?

Sure @thurka . I edited the bug report, thank you for the fast report. If you can answer: there is a lot of "Profiler Agent Warning" on the log. What are those?

**Comment by thurka** [comment]
Thanks for log from JBoss. "Profiler Agent Warning" are unrelated and shows that some of the frames in stacktraces for SQL commands are missing. This should be filed as separate issue.

**Comment by leonardobsjr** [comment]
> "Profiler Agent Warning" are unrelated and shows that some of the frames in stacktraces for SQL commands are missing. 

Can i just ignore it? Can i disable the warning?

**Comment by thurka** [comment]
> Can i just ignore it?

Yes, you can safely ignore it.

**Comment by thurka** [comment]
Fixed in master.
