### ISSUE TITLE
Panels doesn't display in macOS Big Sur 11.0.1 (20B29)

### ISSUE THREAD

**Issue by quaff** [oracle/visualvm#251]
**Describe the bug**
Please check screenshot

**To Reproduce**
1. open VisualVM

**Expected behavior**
"Applications" and "Start Page" panels should be there

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/5557016/messages.log)

**Screenshots**
<img width="2048" alt="VisualVM" src="https://user-images.githubusercontent.com/143040/99467216-e7667d00-2978-11eb-858a-c115150f887c.png">

**Desktop (please complete the following information):**
 - OS: [Big Sur 11.0.1 (20B29)]
 - JDK version [JDK 1.8.0_271]
 - Version [e.g. 2.0.4]

**Comment by thurka** [comment]
Can you please try to reset VisualVM UI? Invoke Window->Reset Windows from menu. Does it help?

**Comment by quaff** [comment]
> Can you please try to reset VisualVM UI? Invoke Window->Reset Windows from menu. Does it help?

It doesn't work, I think Big Sur break compatibility, NetBeans should adapt it, Eclipse SWT has a lots issues with Big Sur too.

**Comment by quaff** [comment]
It caused by "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" deleted, solved by creating symbol link
`ln -s /Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin"`

**Comment by thurka** [comment]
I have no problem running VisualVM 2.0.5 on Big Sur with JDK 15. So can you try JDK 15 and VisualVM 2.0.5?

**Comment by quaff** [comment]
> I have no problem running VisualVM 2.0.5 on Big Sur with JDK 15. So can you try JDK 15 and VisualVM 2.0.5?

I believe it caused by "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin" deleted accidentally, I don't understand why VisualVM depends on this, eclipse works fine without it.

**Comment by thurka** [comment]
> I don't understand why VisualVM depends on this

VisualVM does not depend on it.

**Comment by quaff** [comment]
> > I don't understand why VisualVM depends on this
> 
> VisualVM does not depend on it.

Thanks for your clarification, I can't reproduce it.
