### ISSUE TITLE
Branding of updater splash

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#254]
Updater splash is currently taken from netbeans platform. It would be nice to have VisualVM version of updater splash. 

Steps to reproduce:
1. Launch VisualVM
2. Go to plugins and install several plugins.
3. If the installation of the new plugins takes enough time, updater splash is displayed.

**Comment by thurka** [comment]
http://wiki.netbeans.org/BrandingUpdaterSplash contains guidelines for updater splash branding.

**Comment by jisedlac** [comment]
Addressed in master: https://ol-bitbucket.us.oracle.com/projects/G/repos/visualvm/commits/2a374d89d5a2537f01f40c29f0d8d33e5fb90e5f .

**Comment by thurka** [comment]
Done in trunk.
