### ISSUE TITLE
Empty Lines in Heap Viewer - GC Roots

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#255]
See the screenshot from VisualVM 2.0.5 - there are duplicated nodes in the GC Roots view, most likely having the same hashcode/equals. This is the probable reason for the empty lines being displayed.

![gcroots](https://user-images.githubusercontent.com/22048050/102517142-f92e6380-408f-11eb-844f-d868d69016ce.png)

**Comment by thurka** [comment]
Fixed in master.
