### ISSUE TITLE
openjdk12 cannot run visualvm

### ISSUE THREAD

**Issue by h928725721** [oracle/visualvm#256]
I downloaded visualvm from the official website and modified the jdk path in visualvm.conf. When I run visualvm.exe, nothing happens. When I run through cmd, it shows an error message, as follows:

`The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
WARNING: Unknown module: jdk.attach specified to --add-exports
WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException
        at org.netbeans.MainImpl.execute(MainImpl.java:153)
        at org.netbeans.MainImpl.main(MainImpl.java:60)
        at org.netbeans.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.IllegalClassFormatException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more`

Please tell me how to solve this problem, thanks a lot！！！

**Comment by h928725721** [comment]
My computer is windows system

**Comment by thurka** [comment]
You did not specify what exactly is `openjdk12`.
Please make sure that you are using Hotspot JDK (and not OpenJ9).

**Comment by h928725721** [comment]
> You did not specify what exactly is `openjdk12`.
> Please make sure that you are using Hotspot JDK (and not OpenJ9).

**Comment by h928725721** [comment]
Thank you for your answer.I used jdk15, but still can't run viusalvm.exe. Below is my jdk version information.
`java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
`
When I run visualvm.exe, the previous error will still be reported

`WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
WARNING: Unknown module: jdk.attach specified to --add-exports
WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException
        at org.netbeans.MainImpl.execute(MainImpl.java:153)
        at org.netbeans.MainImpl.main(MainImpl.java:60)
        at org.netbeans.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.IllegalClassFormatException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more`

**Comment by h928725721** [comment]
@thurka  Thank you for your answer.I used jdk15, but still can't run viusalvm.exe. Below is my jdk version information.
java version "15.0.1" 2020-10-20 Java(TM) SE Runtime Environment (build 15.0.1+9-18) Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
When I run visualvm.exe, the previous error will still be reported

WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports WARNING: Unknown module: jdk.attach specified to --add-exports WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/instrument/IllegalClassFormatException at org.netbeans.MainImpl.execute(MainImpl.java:153) at org.netbeans.MainImpl.main(MainImpl.java:60) at org.netbeans.Main.main(Main.java:58) Caused by: java.lang.ClassNotFoundException: java.lang.instrument.IllegalClassFormatException at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 3 more

**Comment by thurka** [comment]
Please run visualvm from `cmd` and use the following command:
```
visualvm.exe -J-Dnetbeans.logger.console=true -J-ea -J-verbose
```
and attach (as a file) the whole output from visualvm.
Thanks.

**Comment by h928725721** [comment]
[file.txt](https://github.com/oracle/visualvm/files/5728271/file.txt)
@thurka

**Comment by thurka** [comment]
Hmm, this is strange. This:
````
WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
WARNING: Unknown module: jdk.attach specified to --add-exports
WARNING: Unknown module: jdk.internal.jvmstat specified to --add-exports
```
together with `NoClassDefFoundError` shows that your JDK 15 is somehow incomplete. Where did you downloaded this JDK 15? Are you sure that this is full JDK (not JRE or some otherwise strip-down) 15?

**Comment by h928725721** [comment]
[](https://www.oracle.com/java/technologies/javase-jdk15-downloads.html)
I downloaded JDK 15 (Windows x64 Compressed Archive) from the Oracle website. Does visualVM support this version?

**Comment by h928725721** [comment]
[https://www.oracle.com/java/technologies/javase-jdk15-downloads.html](url)

**Comment by thurka** [comment]
Are you talking about `jdk-15.0.1_windows-x64_bin.zip`, which is 179.27 MB? This zip file does not not have `jre` directory, while your JDK on the disk have one - this is the first line form your file:
```
E:\java\jdk-15.0.1\jre\lib\modules
```
Please make sure that the content of the zip file exactly matches, what is on your disk. It looks to me that you have some extra files in `E:\java\jdk-15.0.1`.

**Comment by h928725721** [comment]
Oh, I was too careless. This is why I can't start visualVM, and it can run normally now. Thank you very much.

**Comment by thurka** [comment]
Ok, I am glad we were able to solve it. Just curious - how did `jre` directory ended up in `E:\java\jdk-15.0.1`?

**Comment by thurka** [comment]
There is probably same issue GH-128 - so you are not the only one, who had this problem.

**Comment by h928725721** [comment]
After downloading JDK15, I manually generated the jre directory through commands, 
`bin\jlink.exe --module-path jmods --add-modules java.desktop --output jre`
which caused this problem. I believe other people with the same problem as me did the same.

**Comment by thurka** [comment]
I see, interesting. The `jre` directory confuses JDK launcher, which uses it and VisualVM runs on this strip down java version created by jlink. It is better not to modify the JDK layout and put `jre` outside of  `E:\java\jdk-15.0.1` directory.
