### ISSUE TITLE
Can't view allocation stack traces in version 2.0.4

### ISSUE THREAD

**Issue by john01dav** [oracle/visualvm#258]
**Describe the bug**
I'm desperately trying to view allocation stack traces to hunt down a memory leak in visualvm 2.0.4, but not only is the UI not intuitive enough for me to figure this out, but it seems to have changed at some point since all the online guides that I can find refer to nonexistant components (mainly a checkbox to enable this feature in settings).

**To Reproduce**
1. Try to record allocation stack traces
2. Find that this is utterly undocumented
3. Fail

**Expected behavior**
Ideally, it would be intuitive enough that I can just look around the UI and easilty figure it out. Failing that, I should be able to instantly find a detailed and up-to-date guide from a web search. An hour or so of searching has found nothing useful.

**VisualVM log**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - JDK version Java 8
 - Version [e.g. 1.4] 2.0.4

**Additional context**
Is there some documentation somewhere that isn't coming up in search engines?

**Comment by jisedlac** [comment]
Thanks for your feedback! You're right that the memory profiler has changed during time and the guides available are often out of date. We're aware of this problem and plan to address it.

Still, getting the allocation stack traces should work OOTB without reading any documentation. Just open the process to be profiled, switch to the Profiler tab, define the classes to analyze in the Memory settings pane (see the tooltip for examples) and click the Memory button.

By default, the profiler is configured to display the allocation stack traces for live objects, up to 10 frames. If you need full stack traces, just unselect the "Limit allocations depth" option as suggested by the tooltip.

Please let us know whether this info helped you. Thanks!

**Comment by jisedlac** [comment]
Assuming the hint helped.
