### ISSUE TITLE
Program get unusable

### ISSUE THREAD

**Issue by lidiestera** [oracle/visualvm#259]
Hi and thank you for maintaining this project!
I have an issue with the Windows version of the tool. Somehow the window of the program get oversized and I'm not able any more to bring it again in an usable state.
With click right on the program in toolbar, there is available only the option "Close window". It can be added an option to make it in "centered as full screen", something like this?
The workaround for me was to download a previous version (204).
![image](https://user-images.githubusercontent.com/3852312/103201283-8908b480-48bd-11eb-9510-468685115f50.png)

Command to use the tool: C:\Program Files\Java\visualvm_205\bin>visualvm.exe --jdkhome "C:\Program Files\Java\jdk-11.0.2"

Regards,
Lidia

**Comment by jisedlac** [comment]
Thanks for your feedback! Please try to use the main menu action Window | Reset Windows using keyboard shortcuts: `Alt+W` (to enter the Window menu) followed by another `Alt+W` (to invoke the Reset Windows action).

Another possibility is to clear the UI state storage by deleting the `C:\Users\<account_name>\AppData\Roaming\VisualVM\2.0.5\config\Windows2Local` folder.

**Comment by lidiestera** [comment]
Thank you. This works. I'll close the issue.
