### ISSUE TITLE
Build instructions not clear. Build fails.

### ISSUE THREAD

**Issue by brunoborges** [oracle/visualvm#26]
So, couple things on building from the source:

1. the README says to download a file that is already contained within the repository. This step could be removed.
2. since the nb platform zip is already in it, build.xml could have the extracting as part of the build process

Last, while trying to build with `ant build-zip`, I got the following error:

[build.txt](https://github.com/oracle/visualvm/files/1037146/build.txt)

**Comment by thurka** [comment]
The build works fine for me. What JDK you use?

**Comment by brunoborges** [comment]
Java 8u131

**Comment by thurka** [comment]
VisualVM runs on JDK 7, so it should be build with JDK 7.

**Comment by bigianb** [comment]
I don't see how the JDK7 is relevant in this case because it looks like the ant build is not adding the required netbeans jar to the compile classpath. I'm having the exact same issue - I've not got netbeans installed due to corporate policy so am working with ant on the command line with JDK 8

**Comment by bigianb** [comment]
The problem is that you're missing a dependency on org.netbeans.lib.profiler.common in visualvm/core/nbproject/project.xml

you need this in that file:

```
               <dependency>
                    <code-name-base>org.netbeans.lib.profiler</code-name-base>
                    <build-prerequisite/>
                    <compile-dependency/>
                    <run-dependency>
                        <release-version>1</release-version>
                        <specification-version>1.10.1</specification-version>
                    </run-dependency>
                </dependency>
```

**Comment by jisedlac** [comment]
Please note that the README clearly states 'Use ... Oracle JDK 7 to build VisualVM ...'. Using JDK 7 the repository builds without errors and you don't need to change any dependencies.

In case you're using JDK 8 you have to update the dependencies, but you'll likely not be able to run the VisualVM using Java 7, which is a supported configuration - see https://visualvm.github.io/relnotes.html.

**Comment by bigianb** [comment]
The release notes say JDK7+ ... I would take the + to make 8 too. In any case, in my corporate environment I only have access to 8 as 7 is deprecated ... and my intent is to write a plugin for the visualVM which ships with the JDK8. Of course if I build with JDK 8 I don't expect to run with JDK 7.
I also don't really follow why JDK 7 can find the missing undeclared dependency when JDK 8 doesn't ... it would seem that JDK 8 is doing the right thing. But ... whatever, I was just trying to help the original poster :-/

**Comment by thurka** [comment]
We just upgraded VisualVM dev. version to be built on top of latest NetBeans platform and profiler. It is now required to build it with JDK 8.
