### ISSUE TITLE
Retained size calculated as negative

### ISSUE THREAD

**Issue by sadaaithal** [oracle/visualvm#263]
**Describe the bug**
A large object doesnt show up under "Dominators by retailed size" due to retained size calculation error.
IBM MAT tool doesn't have this problem

**To Reproduce**
I haven't found a way to generate a heapdump that causes visualvm to behave this way

**Expected behavior**
visualvm must be able to calculate the retainedsizes

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/5811183/messages.log)

**Screenshots**
This is how it looks in visualvm

![image](https://user-images.githubusercontent.com/30702253/104512713-7d96d800-55a3-11eb-9143-c859823c5d23.png)

And this is the same object in IBM MAT

![image](https://user-images.githubusercontent.com/30702253/104512741-8687a980-55a3-11eb-85c1-c983578309ff.png)

And because of the negative retained size calulation, ( i think) the DefaultTable object doesn't show as a Dominator

![image](https://user-images.githubusercontent.com/30702253/104512973-d2d2e980-55a3-11eb-9884-0c756ef7d311.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - JDK version - jdk-9.0.4
 - Version - 2.0.5

**Additional context**

**Comment by thurka** [comment]
Thanks for the report. I will try to reproduce it locally.

**Comment by thurka** [comment]
I am able to reproduce it with the following heap dump [heapdump-1610612692957.hprof.gz](https://github.com/oracle/visualvm/files/5813845/heapdump-1610612692957.hprof.gz).

**Comment by thurka** [comment]
Fixed in master.
