### ISSUE TITLE
Version 2.0.6 doesn't work on Windows 10

### ISSUE THREAD

**Issue by kamaloush** [oracle/visualvm#265]
Using JDK 11

Version 2.0.6 is broken on windows 10
![image](https://user-images.githubusercontent.com/26444823/106004347-6a136300-60b3-11eb-83ed-084abc9a02a7.png)

but 2.0.5 works just fine
![image](https://user-images.githubusercontent.com/26444823/106004434-81525080-60b3-11eb-8652-cd3f90a59ee6.png)

more, in IntelliJ Idea, the plugin fails to start both versions of visualvm
![Idea launchs VisualVM is broken](https://user-images.githubusercontent.com/26444823/106006568-a6e05980-60b5-11eb-9515-743a485b8c4f.gif)

Thanks in advance for you help

**Comment by jisedlac** [comment]
VisualVM 2.0.6 has been tested to work on Windows 10. There's some problem with how you start it on your side.

Please unzip the downloaded `visualvm_206.zip` archive again to a new directory (make sure you don't overwrite any previous installation) and start VisualVM with a custom user directory (for example `bin\visualvm.exe --userdir %TEMP%\visualvm_userdir`).

Skip the import settings on first startup to make sure you'll get a fresh VisualVM environment.

**Comment by kamaloush** [comment]
Thank you,

Your solution works.
![Idea launchs VisualVM is broken2](https://user-images.githubusercontent.com/26444823/106028553-62ac8380-60cc-11eb-8e70-54b57192d6d5.gif)

But it remains a problem with Idea :

![Idea launchs VisualVM is broken3](https://user-images.githubusercontent.com/26444823/106028672-85d73300-60cc-11eb-98dd-83fd364741e2.gif)

Settings are :
![image](https://user-images.githubusercontent.com/26444823/106028740-9be4f380-60cc-11eb-8d7b-1ef46891ca93.png)

Idea version : 
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: VisualVMLauncher, org.jetbrains.kotlin

I know that you don't maintain the plugin for Idea, but maybe you have a solution.

**Comment by jisedlac** [comment]
I assume you didn't install the VisualVM-GoToSource plugin into your VisualVM 2.0.6.

A quick workaround is to unselect the "Integrate with VisualVM-GoToSource plugin..." option in VisualVM Launcher settings. In case VisualVM starts with the broken UI again, close it and clear its caches by deleting these directories:

  - `C:\Users\[your account]\AppData\Roaming\VisualVM\2.0.6`
  - `C:\Users\[your account]\AppData\Local\VisualVM\Cache\2.0.6`

In case you want to use the GoToSource functionality with your IDE, start VisualVM from within the IntelliJ Idea and install the VisualVM-GoToSource plugin using the VisualVM main menu: Tools | Plugins | Available Plugins. Then select the "Integrate with VisualVM-GoToSource plugin..." option in VisualVM Launcher settings again.

**Comment by kamaloush** [comment]
It works ! Thanks
