### ISSUE TITLE
"Local Java applications cannot be detected." due to jdkhome not set in startup script [macOS]

### ISSUE THREAD

**Issue by tpoindex** [oracle/visualvm#266]
On startup, local applications cannot be detected due to an error in /Applications/VisualVM.app/Contents/MacOS/visualvm,  environment variable jdkhome is not set.

**To Reproduce**
1. Install on MacOS Catalina from official dmg.
2. Start VisualVM, either via command line or click on VisualVM in /Applications
3. See error

**Expected behavior**
Should detect local apps when started by clicking on VisualVM application, and without having to have a custom visualvm.conf file.

**VisualVM log**
Instead of logs, I have a diagnosis.

The 'visualvm' shell script only sets the value of 'visualvm_jdkhome' if found in the visualvm.conf file, and only when that file is found and contains a value for visualvm_jdkhome.  When nbexec is launched at the end of the script, the value of --jdkhome is '' (empty string).  

Consider a default setting of visualvm_jdkhome and/or jdkhome.

Also: Update the trouble shooting instructions at:  https://visualvm.github.io/troubleshooting.html
to include hints on starting with --jdkhome flag.  See the section "Local Applications Cannot Be Detected (Error Dialog On Startup)".

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - JDK version AdoptOpenJDK 11.0.8
 - Version 2.0.6

**Additional context**
Workaround:  start manually by setting --jdkhome as a command line option

`$ /Applications/VisualVM.app/Contents/MacOS/visualvm --jdkhome $JAVA_HOME`

or create a file: "~/Library/Application Support/VisualVM/2.0.6/etc/visualvm.conf"
that contains:
`visualvm_home=/path/to/jdk`

**Comment by thurka** [comment]
Thanks for the report. I followed your steps to reproduce, but VisualVM works fine for me and I don't need to set `jdkhome` in startup script or have custom visualvm.conf file. Local applications are detected just fine. I think it would be useful to see your messages.log file. This will help us to find out why do you see "Local Java applications cannot be detected" message.

**Comment by tpoindex** [comment]
Doooh, mystery solved, user error. on my part.

I run several JVMs for testing and development, the last JVM that I installed was AdoptOpenJDK OpenJ9, and that is the JVM that VisualVM started with (and became the default JVM without monkeying around with MacOS.)  

I just updated my Hotspot 11 JVM to the lastest build (again, AdoptOpenJDK), and now VisualVM finds itself and all other Hotspot JVM processes.

Thanks for your continuing work on VisualVM.

**Comment by thurka** [comment]
Thanks for letting us know how you solved this mystery. FYI: messages.log will show you which JDK is used to run VisualVM or you can see verbose output in Terminal if you run `/Applications/VisualVM.app/Contents/MacOS/visualvm -J-Dnetbeans.logger.console=true`
