### ISSUE TITLE
Detect that VisualVM is running on Eclipse OpenJ9 

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#268]
Since VisualVM does not support running on Eclipse OpenJ9, it would be useful to detect that VisualVM is running on OpenJ9 and exit early. There should be dialog explaining what is going on before exiting - similarly to running on JRE or on unsupported JDK version.

**Comment by thurka** [comment]
Fixed in master.

**Comment by keithc-ca** [comment]
Rather than prevent use of OpenJ9, perhaps we can address the problems that interfere with supporting VisualVM running on OpenJ9. Can you share any details of those problem? Thanks in advance.

**Comment by thurka** [comment]
> Rather than prevent use of OpenJ9, 

VisualVM simply does not work on OpenJ9 and it never worked. It looks like that due to adoptopenjdk.net some people are trying to run VisualVM on OpenJ9 so it makes sense to inform them early that they cannot use OpenJ9 to run VisualVM.

>perhaps we can address the problems that interfere with supporting VisualVM running on OpenJ9. Can you share any details of those problem? Thanks in advance.

For the start OpenJ9 need to implement jvmstat and HotSpot compatible Attach API.

**Comment by keithc-ca** [comment]
Thanks for responding promptly.

As I recall, when I was investigating #235, I used OpenJ9 both to run visualvm and the application being monitored. Perhaps things have changed since then.

**Comment by thurka** [comment]
> As I recall, when I was investigating #235, I used OpenJ9 both to run visualvm and the application being monitored. Perhaps things have changed since then.

I don't think so. I guess you just used direct JMX connection, since this is the only standard API for monitoring and therefor can be used for monitoring OpenJ9, all other monitoring APIs are HotSpot specific. So there is no wonder that OpenJ9 do not support them.
