### ISSUE TITLE
Go to to source plugin option configuration unavailable in MacOS 

### ISSUE THREAD

**Issue by mpgeleynse** [oracle/visualvm#271]
**Describe the bug**
Installed the Go To Source plugin on VisualVM version 2.0.6 on MacOS 10.15 (Catalina). The installation completed without issue, However I cannot set the source viewer or location as the Tools menu only display the 'Plugin' item. There is no 'Options' or 'Sources' items or tabs as indicated in the documentation on the web site. I am unable to configure the plugin at all

**To Reproduce**
1. Install the plugin on a mac or MacBook
2. Start (or restart Visual VM)
3. Go to 'Tools' menu
4. Observe there is no 'Options' menu item, only 'Plugins'

**Expected behavior**
As per the documentation, I expected to see an Options menu item under 'Tools'

the documentation excerpt is...
"Configuring the Plugin
   The plugin must be configured to provide the desired functionality. Open Tools | Options and switch to the Sources section to define location of the source code and the tool to display the sources."

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

**Screenshots**
<img width="502" alt="Screen Shot 2021-02-10 at 3 59 50 PM" src="https://user-images.githubusercontent.com/78880167/107571708-470ba780-6bb9-11eb-8e70-22811fb6b314.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - JDK version: JDK 1.8.0_202
 - Version 2.0.6

**Additional context**

**Comment by jisedlac** [comment]
Please use VisualVM | Preferences... on macOS to access the Options dialog.

**Comment by jisedlac** [comment]
Assuming the hint helped.
Online documentation updated.

**Comment by mpgeleynse** [comment]
Yes it did
