### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by kcpeppe** [oracle/visualvm#28]
Following the instructions on the GitHub page I cloned the visuavlm repository, I downloaded and installed the netbeans profiler and then opened the project in NetBeans and tried to run. The error is;
Compiling 107 source files to /Users/kirk/Projects/java/visualvm/visualvm/core/build/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/kirk/Projects/java/visualvm/visualvm/core/src/com/sun/tools/visualvm/core/options/GeneralOptionsPanel.java:295: error: cannot access GlobalProfilingSettings
        ProfilerIDESettings.getInstance().clearDoNotShowAgainMap();
  class file for org.netbeans.lib.profiler.common.GlobalProfilingSettings not found

Building with Ant 

 [nb-javac] /Users/kirk/Projects/java/visualvm/visualvm/core/src/com/sun/tools/visualvm/core/options/GeneralOptionsPanel.java:295: error: cannot access GlobalProfilingSettings
 [nb-javac]         ProfilerIDESettings.getInstance().clearDoNotShowAgainMap();

Will try to resolve

**Comment by thurka** [comment]
Please use JDK 7 for building VisualVM - this is already mentioned in the build guide.
