### ISSUE TITLE
VisualVM requires high performance GPU running on MBP with discrete graphics

### ISSUE THREAD

**Issue by arixmkii** [oracle/visualvm#281]
**Describe the bug**
On startup VisualVM (installed via homebrew cask, but should not be different from official package) creates java process, which locks the discrete (high-performance) GPU active. It doesn't look like it is really needed for the VisualVM to function properly, but it makes it a lot less convenient to run VisualVM in background, especially working on battery and for extended period of time.

**To Reproduce**
1. Fresh start the MacOS (restart if necessary)
2. Check that iGPU is active (for example with gfxCardStatus app)
3. Start VisualVM
4. Verify that java process is using dGPU (using gfxCardStatus app or with Activity Monitor)

**Expected behavior**
No switch to dGPU happening. Like with any regular Java application.

**VisualVM log**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - JDK version 15.0.2 adoptopenjdk
 - Version 2.0.6

**Additional context**
Affects only Intel based MBP with additional AMD GPU.

**Comment by arixmkii** [comment]
Same behavior is observed for Apache Netbeans. Could be that it is not VisualVM bug/can't be fixed in VisualVM.

**Comment by thurka** [comment]
I think that the right place for the fix is JDK. With the following [patch](https://gist.github.com/thurka/24c36838d61e2db9ca2016ec95fcf581) to JDK 11, I was able to fix it. See the screenshot from Activity Monitor.
<img width="854" alt="GPU" src="https://user-images.githubusercontent.com/22048069/111326222-ab180480-866c-11eb-8595-4732f43fa369.png">

**Comment by arixmkii** [comment]
Oh. I was under impression that there might be JNI launcher involved here (and then the plist files would come with VisualVM), but it is only used for Windows OS.

Introduction of JNI based launcher for MacOS should make it possible to adjust the settings on VisualVM side, but it is obviously an overkill to introduce this machinery just because of this behavior.

@thurka Thank you for your hint.

I don't know if this issue is worth being kept open for reference purposes.

**Comment by thurka** [comment]
JNI launcher is another way how to solve it. As you correctly noted - this not a simple task. Both launcher scripts (visualvm and nbexec in netbeans platform) have to be rewritten and also updated with the future changes to the scripts. So unless there is no other possibility, we are trying to avoid JNI launcher.

**Comment by thurka** [comment]
There is already a patch for JDK https://github.com/openjdk/jdk/pull/1139 . Unfortunately it seems to be stuck. :-( See the patch's discussion.

**Comment by arixmkii** [comment]
@thurka thank you a lot for the links and detailed analysis! I can understand why it is difficult to decide to include or not this fix in a something as generic as JDK. Many applications use JNI launchers to regain the control (don't know if it would be worse if the part, which needs dGPU would make their own JNI launchers).

I have humble hopes, that this might be addressed in project [Lanai](https://openjdk.java.net/projects/lanai/) and this [JEP](https://openjdk.java.net/jeps/382) for JDK 17. It looks reasonable to me, because they focus on OS specific features.

**Comment by thurka** [comment]
> I have humble hopes, that this might be addressed in project [Lanai](https://openjdk.java.net/projects/lanai/) and this [JEP 382](https://openjdk.java.net/jeps/382) for JDK 17. It looks reasonable to me, because they focus on OS specific features.

Yes, Metal rendering engine solves this issue. If you are running on the latest JDK 17 preview build (use `-J-Dorg.graalvm.visualvm.modules.startup.DisableStartupCheck=true`) and enables Metal rendering engine, High Perf GPU is not required.
