### ISSUE TITLE
"max heap size" JVM parameter set up in any java application(either through -Xmx500m or -XX:MaxHeapSize), is not being reflected in visualVM tool ( After attaching the process PID) under section Monitor - Memory-> heap >Max

### ISSUE THREAD

**Issue by pranjalsrivastava-crypto** [oracle/visualvm#287]
"max heap size" JVM parameter set up in any java application(either through -Xmx500m or -XX:MaxHeapSize), is not being reflected in visualVM tool ( After attaching the process PID) under section Monitor - Memory-> heap >Max

Observation:
if keeping the -XX:MaxHeapSize=600m, launched the java application and attached the PID of application in VisualVM tool then  under section Monitor - Memory-> heap >Max size is not showing as mentioned/provided value and it shows twice of the value i.e.Max: 1,258,291,232 B.

On the similar note, jconsole and -XX:+PrintFlagsFinal shows correct value. Please have a look and 
![toupload](https://user-images.githubusercontent.com/69041295/112264800-6b1dd680-8c97-11eb-88bc-b771a9fb2d32.png)

**Comment by thurka** [comment]
This is already reported, see GH-127.
