### ISSUE TITLE
UI Theme

### ISSUE THREAD

**Issue by ramtg** [oracle/visualvm#290]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Add an option so the user can either select the Windows 10 System Theme or choose one from a predefined menu of application defined themes . 

**Describe alternatives you've considered**
Visual VM as of v2.0.6 doesn't seem to apply the user selected Windows 10 Theme.

**Additional context**
Ease of access and UI ergonomics.

**Comment by jisedlac** [comment]
Can you please attach a screenshot of the incorrect VisualVM 2.0.6 appearance on Windows 10?

There were no changes in this area, VisualVM should start with the Windows LaF on Windows 10.

We don't plan to provide special support for switching LaFs, VisualVM should use the system appearance whenever possible.

If necessary, the appearance can be switched manually to a cross-platform LaF using the command line parameter:

- `visualvm.exe --laf Metal`
- `visualvm.exe --laf Nimbus`
