### ISSUE TITLE
Plugins | Settings | Proxy Settings Button Doesn't Work

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#292]
Windows 10, Oracle JDK 1.8.0_281, VisualVM 2.0.7.

In main menu invoked Tools | Plugins, switched to Settings tab, clicked the Proxy Settings button - no action.

Using the same setup and steps in VisualVM 2.0.6, the Options dialog is opened and Network tab preselected.

**Comment by thurka** [comment]
Fixed in master.
