### ISSUE TITLE
Mac big sur swith program  visualvm will exit

### ISSUE THREAD

**Issue by ShayLau** [oracle/visualvm#294]
**Describe the bug**
Visual can't work

**Expected behavior**

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.
[visualvm-log1.log](https://github.com/oracle/visualvm/files/6355694/visualvm-log1.log)

**Screenshots**
![open](https://user-images.githubusercontent.com/19186514/115659170-b39ae380-a36c-11eb-8ff5-49120bc97759.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - JDK version JDK "11.0.10" 2021-01-19 LTS
 - Version: visual vm 2.0.7

**Additional context**
[errorlog1.txt](https://github.com/oracle/visualvm/files/6355655/errorlog1.txt)

**Comment by thurka** [comment]
Native crash always suggests that this is JDK bug. Searching for `[AWTView keyboardInputSourceChanged:]` from your `errorlog1.txt` reveals that this crash is reported as JDK bug [JDK-8257242](https://bugs.openjdk.java.net/browse/JDK-8257242). It should be fixed in JDK 11.0.11.
