### ISSUE TITLE
Profiling results are empty in Profiler tab

### ISSUE THREAD

**Issue by APPravin** [oracle/visualvm#296]
Hi,
I am trying to profile my SpringBoot application with VisualVM. But when I open profiler tab and click on CPU button,it process successfully and shows the status as 'profiling successfully', but in the profiling results table, it doesn't show anything. Same thing for the memory button.
I also have attached the screenshots of the same.
I am using JDK 11 and Visual VM 2.0.7 version on windows 10 (64-bit).

Please help.
Thanks.
![Screenshot (30)](https://user-images.githubusercontent.com/20156452/116002701-938f4c80-a618-11eb-9759-ffcf0e722275.png)
![Screenshot (32)](https://user-images.githubusercontent.com/20156452/116002703-95f1a680-a618-11eb-89ee-3a1e53ce1c4c.png)

**Comment by thurka** [comment]
This hard to tell without actual code of `com.examle.ApApplication` class, but I guess that no `com.examle.ApApplication` code is running after you started profiling.
Can you provide steps to reproduce?

**Comment by APPravin** [comment]
Following is the code I am running :

package a.p;
@SpringBootApplication
public class ApApplication {
	static List<ApApplication> visualVMTestList = new ArrayList<ApApplication>();
	public static void main(String[] args) {
		SpringApplication.run(ApApplication.class, args);
		ap();
	}
	public static void ap() {
		for (int i = 0; i <= 10000; i++) {
			visualVMTestList.add(new ApApplication());
		}
		System.out.println("AP called");
	}
}

Following are the steps I am performing:
1.Run an application as Springboot Application.
2.Open VisualVM and open running application PID in visualVM.
3.Then Go to profiler tab.By default the status is 'inactive'.
4.Added package a.p.** in profiler classes box for both CPU settings and memory settings.
5.Click on CPU button.Status changed to profiling running and 14 methods instrumented.
-But still the profiling results are empty.

Thanks.

**Comment by thurka** [comment]
I am not familiar with SpringBoot application, but are you sure that the `ap()` method is invoked after the started the profiling? What does `SpringApplication.run()` do? How do you know that `SpringApplication.run()` ended? Is `AP called` text written to console? If so, is it before or after you started profiling?

**Comment by thurka** [comment]
Closing until more info is available.
