### ISSUE TITLE
Allow to save JFR recording

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#297]
It will be useful to add feature, which allows to save JFR recording from live process. This could be similar to 'Thread Dump' and 'Heap Dump' actions available on application node. The resulting JFR file should behave similarly to thread-dump and heap-dump profiler snapshot files. It will be part of the application snapshot and opened in a separate tab.

**Comment by thurka** [comment]
Done in master.

**Comment by thenetworkgrinch** [comment]
How do you save as a JFR?
