### ISSUE TITLE
Don't see polyglot functionality when running via JMX

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#304]
**Describe the bug**

I don't see polyglot functionality when running via JMX.

**To Reproduce**

Connect to a VM via JMX. You won't see polyglot functionality. However you do see the Graal logo so it does know it's a Graal VM.

**Expected behavior**

See polyglot functionality.

**VisualVM log**

[logfile.txt](https://github.com/oracle/visualvm/files/6510244/logfile.txt)

**Screenshots**

<img width="1194" alt="Screenshot 2021-05-19 at 17 10 59" src="https://user-images.githubusercontent.com/341094/118847015-3314c780-b8c5-11eb-821f-3869a24ddd33.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version: 11.0.11+8-jvmci-21.2-b01
 - Version: Dev (Build 210127)

CC @eregon

**Comment by thurka** [comment]
Truffle sampler is not supported for remote application.

**Comment by chrisseaton** [comment]
Can you say something about how the Truffle sampler works please if it's not able to work via a wire protocol?

**Comment by thurka** [comment]
I am not sure, what do you mean by 'wire protocol', but I guess you mean JMX. Am I right?
Polyglot sampler uses Attach API to upload special library, which will allow VisualVM to get the information from GraalVM. Attach API works only for locally running applications, so VisualVM is not able to obtain information for Polyglot sampler if the application is running on remote machine.

**Comment by chrisseaton** [comment]
That answers the question, thanks.

**Comment by thurka** [comment]
Note that you can run VisualVM on remote machine and display it on local one via VNC, RDP or remote X session.

**Comment by chrisseaton** [comment]
Could we implement remote functionality via a local tool that responds to remote requests? So I run VisualVM on my Mac, I install a server on my cloud development environment that listens to commands from VisualVM, and uses JMX to talk to the process?

**Comment by thurka** [comment]
It is possible to upload special library as java agent from command line using
```
jcmd <ruby_pid> JVMTI.agent_load $GRAALVM_HOME/lib/visualvm/visualvm/modules/ext/stagent.jar
```
If you are OK with this, I can modify VisualVM to enable Polyglot sampler for remote application connected via JMX.

**Comment by chrisseaton** [comment]
Yes that'd work. I can run any commands required on the machine the process is working on. I just don't want to run X (client or server) on the machine.

**Comment by thurka** [comment]
> Yes that'd work.

OK, I will update VisualVM to enable Polyglot sampler if the above agent is loaded in advance (before opening remote application).

**Comment by thurka** [comment]
Done in master. Note that VisualVM special library `stagent.jar` needs to be loaded into remote JVM before remote application is opened in VisualVM. To load the library, the  following command can be used:
```
jcmd <ruby_pid> JVMTI.agent_load $GRAALVM_HOME/lib/visualvm/visualvm/modules/ext/stagent.jar
```

**Comment by chrisseaton** [comment]
Works.
