### ISSUE TITLE
Password are saved in the connection configuration files

### ISSUE THREAD

**Issue by gvlx** [oracle/visualvm#306]
**Describe the bug**
Passwords should be stored on a secure vault

**To Reproduce**
Check the files in ``..\repository\jmxapplications``

**Expected behavior**
Only a password handle should exist on the file.

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0) , amd64 64bit
 - JDK: version 11.0.10; OpenJDK 64-Bit Server VM (11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
 - Version: 2.0.6 (Build 201219); platform 20201027-unknown-revn

**Additional context**
Consider using the same approach as in "Java Mission Control".

**Comment by thurka** [comment]
Done in master for newly created JMX connections.
