### ISSUE TITLE
VisualVM unable to profile TruffleRuby

### ISSUE THREAD

**Issue by nirvdrum** [oracle/visualvm#310]
[visualvm-logfile.txt](https://github.com/oracle/visualvm/files/6599238/visualvm-logfile.txt)
**Describe the bug**

I'm working on a performance issue with TruffleRuby, so I'm working against its _master_ version: 2d75a9837e3f6ca3ffc638bc312212e195e9d7f7. I'm using VisualVM build 210504. With this combination, I'm unable to profile a TruffleRuby application. Attempts to use the "Polyglot Sampler" result in an error.

On the TruffleRuby side, I see the following stack trace:

```
SEVERE: null
java.lang.NoSuchFieldException: impl
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at org.graalvm.visualvm.sampler.truffle.stagent.TruffleJMX.getContextImpl(TruffleJMX.java:107)
	at org.graalvm.visualvm.sampler.truffle.stagent.TruffleJMX.agentmain(TruffleJMX.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
```

**To Reproduce**

1. Clone TruffleRuby SHA 2d75a9837e3f6ca3ffc638bc312212e195e9d7f7.
2. Run VisualVM build 210504
3. Run a Ruby script: `jt ruby --jvm -e 'loop { "abc".size; sleep 1 }'
4. Go to the "Polyglot Sampler" tab in VisualVM
5. Wait a little bit and VisualVM will update the "CPU sampling" message to say "Not available. Cannot access truffle JMX in target application. Check the logfile for details (use Help | About | Logfile)."

**Expected behavior**

I expected to see profiled Ruby methods.

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

**Screenshots**

**Desktop (please complete the following information):**
- OS: macOS 11.3.1; Ubuntu 21.04
- Java version: 
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM 21.2.0-dev (build 11.0.11+8-jvmci-21.2-b02)
OpenJDK 64-Bit Server VM GraalVM 21.2.0-dev (build 11.0.11+8-jvmci-21.2-b02, mixed mode, sharing)  

**Additional context**
This was working as of a few days ago. It looks like an internal field may have been renamed causing a lookup to fail.

**Comment by chrisseaton** [comment]
The breaking commit is https://github.com/oracle/graal/commit/79f5b197112c055de30641e6e6fcab042c04871a.

I don't know if we can revert that locally?

Not being able to use VisualVM is not great for us.

**Comment by chumer** [comment]
@thurka  can we fix this on the visualvm side or do need to rename the field back? Can you elaborate why you need to do reflection on the polyglot classes?

**Comment by chumer** [comment]
@thurka  could you provide a list of things you are depending on in VisualVM? So we can add a test so we won't break them in the future?

**Comment by thurka** [comment]
> @thurka can we fix this on the visualvm side or do need to rename the field back?

I can fix it in VisualVM.

> Can you elaborate why you need to do reflection on the polyglot classes?

To get  `AbstractContextImpl` class loader so we are able to access `TruffleLocator` or `GraalVMLocator`.

**Comment by chumer** [comment]
> To get AbstractContextImpl class loader so we are able to access TruffleLocator or GraalVMLocator.

For this purpose there is already a hidden method: `Engine.loadLanguageClass`
We will continue to support that one and also works with older versions of GraalVM.

**Comment by thurka** [comment]
> For this purpose there is already a hidden method: `Engine.loadLanguageClass`

Thanks. This could be helpful for JDK 8. Unfortunately I am not able to call it from agent on JDK 11+ because of JPMS restrictions.

**Comment by thurka** [comment]
Fixed in master.

**Comment by chrisseaton** [comment]
Thank you. Is the process to get the new build referenced by GraalVM's suite automatic or do we need to do something there as well?

**Comment by thurka** [comment]
What is 'build referenced by GraalVM's suite'?

**Comment by chrisseaton** [comment]
https://github.com/oracle/graal/blob/c28ce4f4c39b5d2334e56da1e590d51108134ad4/tools/mx.tools/suite.py#L317-L346

**Comment by thurka** [comment]
I see, so you want this fix to be part of GraalVM dev. build. Am I right?

**Comment by chrisseaton** [comment]
Yes at the moment the VisualVM in GraalVM is not compatible with the rest of GraalVM. Should I open that issue back in the Graal repo? I guess they'll need a release from the VisualVM team to do the update so they'd have to pass it back here anyway.

**Comment by thurka** [comment]
There is no need to open issue in the Graal repo. I will make sure that VisualVM binaries are updated in GraalVM dev. build.

**Comment by thurka** [comment]
> I will make sure that VisualVM binaries are updated in GraalVM dev. build.

[Done](https://github.com/oracle/graal/commit/7fa6126b1cd793e6069b232e14518ed448a8c799#diff-81cc86ea0f5f1461dc0d4223caef12963706846b4ee0a6d768dfdf8ccdc7816c).

**Comment by chumer** [comment]
> This could be helpful for JDK 8. Unfortunately I am not able to call it from agent on JDK 11+ because of JPMS restrictions.

I see. I assume this is because you are using unsafe?

My prediction for the future is that we will unknowingly break this again. I think we need a test in truffle and a comment to avoid breakage.
