### ISSUE TITLE
Logfile/Options location instructions on macOS unclear

### ISSUE THREAD

**Issue by nirvdrum** [oracle/visualvm#311]
**Describe the bug**

I've encountered an issue within VisualVM with a message telling me where to find the log file:

```
Check the logfile for details (use Help | About | Logfile).
```

That path is not correct on macOS. VisualVM on macOS does have a "Help" menu, but that only brings up a search box to look through the help documentation. The real log file location is under "VisualVM" -> "About VisualVM" -> "Logfile."

**To Reproduce**

Induce an error in VisualVM somehow (#310 is how I did it).

**Expected behavior**

While I think it can be expected that people understand the menu layout on macOS is different than other platforms, the fact that there is a "Help" menu in VisualVM makes the issue a bit confusing.

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1
 - VisualVM: Build 210504

**Comment by jisedlac** [comment]
Similar problem with Options: `Tools | Options` vs. `VisualVM | Preferences...`

**Comment by jisedlac** [comment]
Fixed in master.
