### ISSUE TITLE
CPU Sampler | Hot Spots Showing No Results

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#312]
Windows 10, VisualVM 2.0.7, JDK 8u291.

Opened the host VisualVM process, configured CPU sampler to "Profile only classes" `javax.swing.*`, set "Sampling frequency" to 20ms.

Started CPU sampling, displayed both "Forward calls" and "Hot spots" views. The "Forward calls" shows code from `javax.swing.*` (e.g. `javax.swing.TimerQueue.run()`, `javax.swing.Timer.post()`), but at the same time the "Hot spots" show no results, see the attached screenshot.

The expected and correct behavior is "Hot spots" view showing code from classes in the `javax.swing` package, like `javax.swing.TimerQueue.run()`, `javax.swing.Timer.post()` and other.

![cpu_sampler_filtered](https://user-images.githubusercontent.com/22048050/121654537-1d4a8a80-ca9e-11eb-8d6c-af06ad09406c.png)

**Comment by thurka** [comment]
`javax.swing.**` seems to work fine.

**Comment by thurka** [comment]
Fixed in master.
