### ISSUE TITLE
Second invocation of specific OQL query doesn't show anything.

### ISSUE THREAD

**Issue by homes410** [oracle/visualvm#314]
**Describe the bug**
Following oql query don't show anything.
select map(heap.classes(), 'toArray(it.fields)')

https://github.com/oracle/visualvm/blob/f7e6b4ab8d2dcd63e42f6b3bf2bc8e93ae54d715/visualvm/libs.profiler/profiler.oql/src/org/graalvm/visualvm/lib/profiler/oql/engine/api/impl/hat.js#L461

you need to implement it as accessor function or just replace the above line to below.

this.fields = function(){return wrapIterator(jclass.fields.iterator(), true);}

Thank you.

**Comment by thurka** [comment]
FYI: First invocation of above query works fine.

**Comment by homes410** [comment]
Object.defineProperty(this,'fields',{get: function(){
    return wrapIterator(jclass.fields.iterator(), true);
}});
please apply this line and close this issue.

**Comment by thurka** [comment]
Fixed in master.
