### ISSUE TITLE
Maven Visual VM Repository

### ISSUE THREAD

**Issue by alexsuter** [oracle/visualvm#315]
Hi guys

I can't find the new url to where the VisualVM artifacts are hosted for building my VisualVM plugin with maven.
I have used this:
http://bits.netbeans.org/nexus/content/repositories/visualvm/

Where is the new repo?

**Comment by thurka** [comment]
There is no new repo, but can build maven artifacts yourself. For detailed steps, see release readme file: https://github.com/oracle/visualvm/tree/release207#generate-the-maven-artifacts
