### ISSUE TITLE
Heap analyzer displays "unknown class" for all non JDK classes

### ISSUE THREAD

**Issue by voidmain** [oracle/visualvm#325]
**Describe the bug**
When I open a heap dump taken from a production server running Java 14 and open it up in VisualVM, every class except for the JDK classes (`java.*`, `jdk.*`, etc) are listed as `<unknown class>`. I've also opened the dump file in a hex viewer and it looks like the classes exist properly with the correct names in the file itself.

I also tried appending our production classpath with all of our JAR files to the VisualVM classpath using the `--cp:p` option. This didn't help at all.

**To Reproduce**
Happy to share this heap dump privately as it might contain secure data. You'll be able to open it and see the issue pretty easily. It's about 2GB though.

**Expected behavior**
I expect to see the correct class name listed.

**VisualVM log**
Not sure where these are located, but I don't see them on my machine.

**Screenshots**
<img width="1028" alt="Screen Shot 2021-07-02 at 2 37 22 PM" src="https://user-images.githubusercontent.com/377102/124326084-16fe7a00-db43-11eb-8f76-b6d7e029119a.png">
<img width="2093" alt="Screen Shot 2021-07-02 at 2 37 38 PM" src="https://user-images.githubusercontent.com/377102/124326085-17971080-db43-11eb-9307-2c51c57b071b.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version JDK 16.0.1+9
 - Version 2.0.7

**Comment by thurka** [comment]
Ok @voidmain, how can we share this heap dump? Please use my email for further communication.

**Comment by thurka** [comment]
FYI: VisualVM log file is available from menu: VisualVM -> About VisualVM -> Logfile

**Comment by voidmain** [comment]
Sorry for the delay. FusionAuth has been growing like wild fire lately and I've been insanely busy. I will end you the logfivle via email and we'll need to coordinate a location for the dump since it is quite large (1.9G).

**Comment by thurka** [comment]
I inspected the heap dump you sent me and I have found out that it is indeed broken. The symbol names for classes, which are not loaded by boot classloader, are missing. This is the reason, why you see <unkonwn name> for most of the classes. This looks to me like JDK bug. [JI-9070068](https://bugs.openjdk.java.net/browse/JI-9070068) seems to be very similar to your case.

**Comment by voidmain** [comment]
I tried clicking that link and it requires a login. I couldn't find a way to create an account either. 

In any case, it sounds like this is a JDK bug and we just happened to hit it. That likely was the reason the JVM crashed. I'm fine closing this out since it isn't an issue with VisualVM.
