### ISSUE TITLE
Redefinition failed with error 62

### ISSUE THREAD

**Issue by sleepytomcat** [oracle/visualvm#33]
**Environment**
Version: 1.8.0_131 (Build 1390-170114); platform 20170114-unknown-revn
System: Mac OS X (10.12.5) , x86_64 64bit
Java: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM (25.131-b11, mixed mode)
Vendor: Oracle Corporation, http://java.oracle.com/

**Repro steps**
1) run application (source code blow);
2) run JVisualVM;
3) select application on Applications tab, then Profiler tab on the right, then press 'CPU' to start profiling.

**Result**
JVisualVM displays popup with error message "**Redefinition failed with error 62
Check JVMTI documentation for this error code.**"

**Test app source code**

class perf {
    public static void main(String[] args) throws InterruptedException {
        for(;;) {
            a();
            b();
            c();
        }
    }

    static void a()throws InterruptedException{Thread.sleep(200);};
    static void b()throws InterruptedException{Thread.sleep(1000);};
    static void c()throws InterruptedException{Thread.sleep(2000);};
}

**Comment by sleepytomcat** [comment]
Same issue happens to newer JVisualVM, Version: 1.3.9 (Build 161004); platform 20161002-268c3bcd7a42

**Comment by jisedlac** [comment]
Caused by an incompatible change in Java. We're working on resolving it somehow. The only workaround so far is to use JDK 8u112 or older.

**Comment by muffl0n** [comment]
Same with 1.8.0_144.

**Comment by namnatulco** [comment]
[this](https://stackoverflow.com/a/26851207/) workaround appears to work too, at least for me (I'm also running OpenJDK 1.8.0_144)

**Comment by thurka** [comment]
This should be fixed in the latest dev. version of VisualVM.

**Comment by midikiman** [comment]
Still present in JDK 1.8.0_161 (Build 170114)

**Comment by henriquedesousa** [comment]
How can I add the `-Xverify:none` option to a JUnit runner?

**Comment by Katsuryoku** [comment]
still present in JDK 1.8.0_162

**Comment by cecchisandrone** [comment]
See [https://visualvm.github.io/troubleshooting.html](https://visualvm.github.io/troubleshooting.html)

**Comment by Xerus2000** [comment]
Quick fix: JVM parameter `-Xverify:none`

**Comment by denisab85** [comment]
Xerus2000's workaround works for me. In Eclipse, opened
Run Configurations -> Arguments tab
and added "-Xverify:none" to the "VM Arguments" text area.

**Comment by dagnelies** [comment]
still present in JDK 1.8.0_171

**Comment by thurka** [comment]
You need to use VisualVM 1.4.1, not Java VisualVM from JDK 1.8.0_171.

**Comment by nageshgnn** [comment]
It works for after setting the below configuration:
Run Configurations -> Arguments tab
and added "-Xverify:none" to the "VM Arguments" text area.

Thanks

**Comment by artash** [comment]
Same issue, `-Xverify:none` workaround fixed it.

```java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)```
```sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G2307```

**Comment by thurka** [comment]
@ artash You need to use VisualVM 1.4.1 or VisualVM 1.4.2.

**Comment by wilx** [comment]
Well, I just hit this with 202.

**Comment by thurka** [comment]
> Well, I just hit this with 202.
8u202 contains VisualVM 1.3.9. You need to use VisualVM 1.4 or newer.

**Comment by sagnitude** [comment]
Same issue here with 8u11, VisualVM 1.4.1 Build 180424

**Comment by thurka** [comment]
> Same issue here with 8u11, VisualVM 1.4.1 Build 180424
This looks like different issue. Please file separate bug with steps how to reproduce it.

**Comment by m31collision** [comment]
I'm running on openjdk 11.0.2:

```
openjdk 11.0.2 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.2+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7, mixed mode)
```

and it also prints similar error:

```
Profiler Agent Error: Redefinition failed for classes:
my.GroovyScript
Profiler Agent Error: with message: Redefinition failed with error 62
Check JVMTI documentation for this error code.
Debug: writing class file: my.GroovyScript, into file: my.GroovyScript.class
```

when I try to profile app using visualvm 1.4.4.

Is this specific to Groovy?

**Comment by thurka** [comment]
@m31collision This looks like different issue. Please file new issue and provide steps how to reproduce it. Thanks.
