### ISSUE TITLE
In 4k resolution display, the font is too small to see

### ISSUE THREAD

**Issue by mozhuanzuojing** [oracle/visualvm#338]
**Describe the bug**
The display is 4k resolution. Windows system is set to 250% magnification. The font of visualvm is too small to see the text at all.

**To Reproduce**
1. Open the command line
2. Run visualvm

**Expected behavior**
The interface font is as big as the visualvm menu font or as big as the windows font

**VisualVM log**
[messages.log](https://github.com/oracle/visualvm/files/7026717/messages.log)
[messages.1.log](https://github.com/oracle/visualvm/files/7026721/messages.1.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/130346069-baaf7205-41be-4080-b562-22f49965352d.png)

**Desktop (please complete the following information):**
 - OS: [Windows_NT x64 10.0.19043]
 - JDK version [jdk-16.0.1.9-hotspot]
 - Version [2.1]

**Additional context**
The font size of the menu and title is correct. The following content font is particularly small. These two font sizes remain

**Comment by jisedlac** [comment]
Please define custom font size using `visualvm.exe --fontsize 20` and/or enable custom scaling using `visualvm.exe -J-Dsun.java2d.uiScale=2.0`.

This is a generic Swing or NetBeans platform issue, not to be addressed on VisualVM side.
