### ISSUE TITLE
Support Jolokia and kubernetes connections

### ISSUE THREAD

**Issue by skarsaune** [oracle/visualvm#340]
**Is your feature request related to a problem? Please describe.**
VisualVM should make use of the new support in Jolokia for JMX Service connections and also for JVMs running in kubernetes.

**Describe the solution you'd like**
Solution is demonstrated in PR: https://github.com/oracle/visualvm/pull/182 . 
as two virtualvm plugins.
Also demonstrated in video: https://www.youtube.com/watch?v=ALkMdEPPg1U

**Describe alternatives you've considered**
Plugins seems like the way forward, but I don't entirely understand why the jar needs to be in the GraalVM plugin.

**Comment by thurka** [comment]
New Jolokia plugin was added. it uses Jolokia 2.1.1 artifacts from maven central.
