### ISSUE TITLE
Local JVM monitoring dashboard is gone and can't be brought back

### ISSUE THREAD

**Issue by s50600822** [oracle/visualvm#348]
**Describe the bug**
Local JVM monitoring dashboard is gone and can't be brought back

**To Reproduce**
Don't know what leads to this but now any time visualVM is openned there's no localhost jvm detection. Can't add it back either. Uninstall - reinstall does not bring back the view

<img width="1163" alt="Screen Shot 2021-09-23 at 6 20 22 am" src="https://user-images.githubusercontent.com/5586453/134417512-de4f6760-525d-40db-810b-59d7a8910864.png">

<img width="1295" alt="Screen Shot 2021-09-23 at 6 28 03 am" src="https://user-images.githubusercontent.com/5586453/134417544-cc28f055-07dc-4c75-8920-1db2476cc1b8.png">

**Expected behavior**
visualVm show localhost monitoring any local JVMs

**VisualVM log**
Can't find any log file under .sdkman/candidates/visualvm/current

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version:
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

 - Version 2.1

**Comment by thurka** [comment]
Looks like you've closed the Applications pane. Use `Window -> Applications` or `Window  -> Reset Windows` in the menu bar to open it again.
The log file is available via `VisualVM -> About -> Logfile`

**Comment by s50600822** [comment]
You are right, thanks much @thurka
