### ISSUE TITLE
Allow methods (sun.reflect.GeneratedMethodAccess.*) to be excluded when displaying call stacks

### ISSUE THREAD

**Issue by ronosaurus** [oracle/visualvm#358]
**Is your feature request related to a problem? Please describe.**
Allow methods to be hidden from stack traces based on user settable wildcards or regexs.

**Describe the solution you'd like**
I'm using a framework that uses a lot of reflection that generates call stacks like this:
- sun.reflect.GeneratedMethodAccess58375.invoke()
- sun.reflect.GeneratedMethodAccess19293.invoke()
- sun.reflect.GeneratedMethodAccess69385.invoke()

**Additional context**
In this example if sun.reflect.GeneratedMethodAccess.* were filtered out I could more easily analyze snapshots and fit more information on the screen at the same time:

![image](https://user-images.githubusercontent.com/2015016/138606483-0d0a8d70-332f-4565-85c1-2027f686ddf9.png)

This stack:

- sun.reflect.GeneratedMethodAccess58375.invoke()
  - com.example.Hello.world()
- sun.reflect.GeneratedMethodAccess19293.invoke()
  - com.example.Foo.bar()
- sun.reflect.GeneratedMethodAccess69385.invoke()
  - com.example.Cat.meow()

would be simplified to:

- com.example.Hello.world()
- com.example.Foo.bar()
- com.example.Cat.meow()

**Comment by thurka** [comment]
You can use 'Filter' to filter out 'sun.reflect.' package. I think this can help you analyse your snapshot. See example below:
<img width="845" alt="original" src="https://user-images.githubusercontent.com/22048069/144570588-a7198ce6-a6ba-4ac8-a4b5-da4a3d05b24a.png">
<img width="854" alt="filtered" src="https://user-images.githubusercontent.com/22048069/144570614-a3cacecd-29cf-4083-ae96-c9b4f1558cd6.png">

**Comment by ronosaurus** [comment]
Yes that worked, thank you. I'll close this issue.
