### ISSUE TITLE
java.lang.NoClassDefFoundError: org/netbeans/lib/profiler/server/ProfilerRuntimeCPUFullInstr

### ISSUE THREAD

**Issue by DaveJarvis** [oracle/visualvm#36]
Complete instructions for running VisualVM against JBoss EAP 6.2.0 GA and JDK 1.7.0_80  are a little thin.

In NetBeans issue [214401](https://netbeans.org/bugzilla/show_bug.cgi?id=214401), @thurka mentions:

> You need to modify JBoss startup arguments. JBoss has to be started with "-Djboss.modules.system.pkgs=org.jboss.byteman,org.netbeans.lib.profiler.server" system property.

Others have mentioned similar parameters:

> -Djboss.modules.system.pkgs=org.netbeans.lib.profiler.server -Dorg.osgi.framework.bootdelegation=org.netbeans.lib.profiler.server,org.netbeans.lib.profiler.server.*

The `ProfilerRuntimeCPUFullInstr` class can be found within `%JAVA_HOME%\lib\visualvm\profiler\lib\jfluid-server.jar`, which is the version that must be run by JBoss. Without additional configuration, it seems unlikely that JBoss can find the class.

The file `domain.bat` has been changed to include:

```
set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman,org.netbeans.lib.profiler.server"
```

Yet this change alone is insufficient.  There are a number of ways to configure `domain.bat` so that the JBoss JVM, when started, can find the class that won't work:

* Set `CLASSPATH` or `JBOSS_CLASSPATH`.
* Use the `-cp` or `--classpath` parameter.
* Create a custom [module](https://developer.jboss.org/thread/242156).

How can JBoss be configured to find `ProfilerRuntimeCPUFullInstr`, tucked away inside `jfluid-server.jar`?

**Comment by thurka** [comment]
So what is wrong with
```
set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman,org.netbeans.lib.profiler.server”
```
