### ISSUE TITLE
Cannot Install visualvm_launcher_u3_eclipse

### ISSUE THREAD

**Issue by zolanet** [oracle/visualvm#375]
Hell, I get the following error when I try to install visualvm_launcher_u3_eclipse:

```
An error occurred while uninstalling
session context was:(profile=_Applications_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Uninstall, operand=[R]org.eclipse.pde.build 3.11.0.v20210429-0618 --> [R]org.eclipse.pde.build 3.11.100.v20210916-0743, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.UninstallBundleAction).
Error while loading manipulator.
Error while loading manipulator.
```

MacOs 10.15.7, Eclipse 2021-09 (4.21.0)

**Comment by thurka** [comment]
I was able to install VisualVM launcher into Eclipse 2021-09 (4.21.0) on macOS without any problem. Can you provide more details how to reproduce it? Can you attach whole log? `An error occurred while uninstalling` looks strange to me.

**Comment by thurka** [comment]
Closing until more info is available.
