### ISSUE TITLE
Any tips to accelerate the "Computing Reference" ?

### ISSUE THREAD

**Issue by Jiayi-Liao** [oracle/visualvm#381]
I'm analyzing a 4.5G dump file, but it took more than ten hours for VisualVM to anaylize the reference, I've already increased the JVM memory to -Xmx4096m but didn't help. 

Is there any way to accelerate the "Computing Reference" ? 
![image](https://user-images.githubusercontent.com/13514599/150622470-f9a060c4-3e89-44dd-813e-e20409dd9b84.png)

**Comment by thurka** [comment]
You need to provide more info. Can you please attach VisualVM log file? What is hardware specification of your computer? Where is the heap dump stored? On local disk? On external disk? On network disk? In general increasing Xmx is not necessary unless your are getting OOME or GC consumes too much CPU (you can check it yourself).
