### ISSUE TITLE
Incorrect Self time reported when merging threads sample results

### ISSUE THREAD

**Issue by NotStirred** [oracle/visualvm#383]
**Describe the bug**
`Self time` is incorrectly reported when multiple threads are merged in the view. The `Self time` values are not merged, only one is shown

**To Reproduce**
1. Open a snapshot with multiple threads where `Self time` takes up a noticeable amount of time (eg: [here](https://cdn.discordapp.com/attachments/416181498937606146/937349959819329536/incorrect-merged-selftime.nps))
2. Merge those threads
3. Check reported `Self time`

**Expected behavior**
Self time to be merged between the selected threads as all other methods are

**Screenshots**
![image](https://user-images.githubusercontent.com/16853282/151703145-e207ac60-22f3-4a37-b9ac-6b9748796e7a.png)

**Desktop (please complete the following information):**
 - Debian 10
 - JDK version - any
 - Version 2.0.6

**Comment by thurka** [comment]
Thanks for the bug report. I am able to reproduce the issue with attached CPU snapshot.

**Comment by thurka** [comment]
Fixed in master.
