### ISSUE TITLE
Sampler - Memory - Class Filter Missing

### ISSUE THREAD

**Issue by jhnmrls** [oracle/visualvm#385]
Under Sampler Tab, then Memory 

The Class Filter for searching specific object is missing

![image](https://user-images.githubusercontent.com/2167425/153143946-60eebdd6-8847-414c-9f26-07d009ec7554.png)

Is there any way to enable it?

**Comment by jhnmrls** [comment]
My bad, 

 In my memory it was always there, it is now disabled by default.
 
  You have to right+click an object and use "Find / Filter" for it to appear

**Comment by mhagnumdw** [comment]
The old way, always showing, is better.

**Comment by mhagnumdw** [comment]
Shortcuts:
- Ctrl + G: filter
- Ctrl + F: search
