### ISSUE TITLE
setting L&F cause crash

### ISSUE THREAD

**Issue by umjammer** [oracle/visualvm#386]
**Describe the bug**

adding look and feel settings to configuration file cause crush.

 * file
`/Applications/VisualVM.app/Contents/Resources/visualvm/etc/visualvm.conf`
 * section
`visualvm_default_options`
 * add
```
-J-cp=/Users/me/.m2/repository/com/formdev/flatlaf/1.6.1/flatlaf-1.6.1.jar -J-Dswing.defaultlaf=com.formdev.flatlaf.FlatLightLaf
```

like
```
visualvm_default_options="-J-Xms24m -J-Xmx768m -J-Dnetbeans.accept_license_class=org.graalvm.visualvm
<< abbreviation>>
VMOptions -J-cp=/Users/nsano/.m2/repository/com/formdev/flatlaf/1.6.1/flatlaf-1.6.1.jar -J-Dswing.defaultlaf=com.formdev.flatlaf.FlatLightLaf"
```

**To Reproduce**
1. edit `/Applications/VisualVM.app/Contents/Resources/visualvm/etc/visualvm.conf`
2. add look and feel option like above
3. run by command line

**Expected behavior**
exec correctly

**VisualVM log**
```
$ /Applications/VisualVM.app/Contents/MacOS/visualvm
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: package sun.awt.X11 not in java.desktop
java.lang.NullPointerException: Cannot invoke "javax.swing.LookAndFeel.getID()" because "<local0>" is null
	at org.netbeans.core.windows.view.ui.MainWindow.logLookAndFeelUsage(MainWindow.java:887)
	at org.netbeans.core.windows.view.ui.MainWindow.init(MainWindow.java:153)
	at org.netbeans.core.windows.WindowSystemImpl.init(WindowSystemImpl.java:46)
	at org.netbeans.core.GuiRunLevel.initializeMainWindow(GuiRunLevel.java:127)
	at org.netbeans.core.GuiRunLevel.run(GuiRunLevel.java:72)
	at org.netbeans.core.startup.Main.start(Main.java:295)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - JDK version [openjdk version "17.0.1" 2021-10-19]
 - Version [2.1.2]

**Additional context**
previous version (it's overridden by 2.1.2, so i couldn't get) visualvm was working w/ that l&f option.

**Comment by thurka** [comment]
Please attach whole messages.log file. Thanks.

**Comment by jisedlac** [comment]
A quick tip - have you tried the VisualVM `--laf` argument to set the LaF instead of `-J-Dswing.defaultlaf`?

Please see https://visualvm.github.io/docs/command-line-options.html#appearance_options and the example right above this section, for `--cp:p and --cp:a`.
