### ISSUE TITLE
Plugin Installer

### ISSUE THREAD

**Issue by 1569637105** [oracle/visualvm#387]
There is a  Note: Missing modules may be published on Update Centers. Please run "Check for Newest" from the "Available Plugins" tab.
VisualVM Version 2.1.2 Generated when the plug-in is installe
![d2715d962cf1f127a176c153f76ea65](https://user-images.githubusercontent.com/99977345/154705003-dd35322b-39c2-4fe0-b104-8e4e5d17eb2b.png)
d

**Comment by thurka** [comment]
I don't have any problem installing Visual GC plugin version 2.1.3 in VisualVM 2.1.2. Did you invoked "Check for Newest" from the "Available Plugins" tab? Can you please provide steps to reproduce and also can you attach messages.log file? Thanks.

**Comment by 1569637105** [comment]
Since my JDK version is 11.0.11, I downloaded version 2.1.2 from the official website.   When I open the software, I go directly to the plug-in to download GC.   While I was in the middle of downloading, an abnormal download occurred and was terminated.   Then I configured the plugin center link based on the blogs on the web.   Then when I downloaded it again, the problem I reported above appeared.    I also tried to download the GC plug-in "Add Plugins..." and install it, but it still didn't work
[messages.log](https://github.com/oracle/visualvm/files/8098600/messages.log)
[messages2.log](https://github.com/oracle/visualvm/files/8098601/messages2.log)
.

**Comment by 1569637105** [comment]
-- What do you mean by "abnormal download"?   What is termination?   Download or VisualVM?   
This refers to the installation of the GC when an exception occurred and the GC terminated the installation.   

-- Where did you download the plugin?   It looks very old and is not compatible with the current version of VisualVM.   
https://visualvm.github.io/uc/8u131/updates.html   

-- What can it do?   
This refers to the（I also tried downloading the GC plugin "Add Plugins..."   And install) still cannot install.   

-- Are you behind the proxy server?   
I operate from the Intranet. Not a proxy server

**Comment by thurka** [comment]
> -- Where did you download the plugin? It looks very old and is not compatible with the current version of VisualVM. https://visualvm.github.io/uc/8u131/updates.html

This is plugin center for Java VisualVM (bundled with JDK 8) and released in 2017. Please refer to https://visualvm.github.io/pluginscenters.html and select the link for VisualVM version you are using. In your case for VisualVM 2.1.2 use https://visualvm.github.io/uc/release212/updates.html

>-- Are you behind the proxy server?
> I operate from the Intranet. Not a proxy server

Well according to exception from the log file, JDK have problem connecting to github website to download plugin itself. So you have to download right plugin manually and install it via "Add Plugins...".

**Comment by 1569637105** [comment]
Thank you very much for your details!   VisualVM2.1.2 installation GC issue.   Can be obtained by manual download at https://visualvm.github.io/uc/release212/updates.html GC 2.1.3 version of the plugin and through the "add plug-ins..."   Install.   Problem solved!
