### ISSUE TITLE
current version of visualvm does not compile

### ISSUE THREAD

**Issue by bennetelli** [oracle/visualvm#40]
I just cloned the latest version of visualvm, downloaded and moved the netbeans profiler stuff to the visualvm/visualvm/ folder as described in the readme (see: https://github.com/oracle/visualvm) and it seems like the code does not compile. Would be nice if someone could help me, please.

**Comment by jisedlac** [comment]
Hi, will you provide any details on this? Logs, setup etc.

**Comment by bennetelli** [comment]
i opened the visualvm parent module in netbeans and wanted to run it via ant run. During the build I get the following error:
/Users/bennet/dev/visualvm/visualvm/core/src/com/sun/tools/visualvm/core/options/GeneralOptionsPanel.java:295: error: cannot access GlobalProfilingSettings
        ProfilerIDESettings.getInstance().clearDoNotShowAgainMap();
  class file for org.netbeans.lib.profiler.common.GlobalProfilingSettings not found
1 error

**Comment by bennetelli** [comment]
I'm using NetBeans 8.2. Do I have to use an older version of it?

**Comment by jisedlac** [comment]
Which JDK version do you use for building VisualVM?

**Comment by bennetelli** [comment]
1.8.0_131

**Comment by jisedlac** [comment]
Please follow the build instructions and use JDK 7 to build VisualVM - see Issue #26 for details.

**Comment by bennetelli** [comment]
I'm getting the same errors as Bruno in Issue #26 . After adding the dependency as described in the issue the build works fine.

<dependency>
        <code-name-base>org.netbeans.lib.profiler.common</code-name-base>
        <build-prerequisite/>
        <compile-dependency/>
        <run-dependency>
        <release-version>1</release-version>
        <specification-version>1.10.1</specification-version>
        </run-dependency>
</dependency>

**Comment by bennetelli** [comment]
I dont get the issue when opening the projects in NetBeans 8.0.2 instead of 8.2.0. So with 8.0.2 I don't need to add the XML dependency snippet to the build.xml
