### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by angel-gruevski** [oracle/visualvm#403]
I cannot use VisualVM on Sway Window Manager which is using Wayland. Are chance for adding support for Wayland?

**Comment by thurka** [comment]
I am missing steps to reproduce. Can you provide them? Can you also specify, what does it mean 'I cannot use VisualVM'? What does not work?

**Comment by angel-gruevski** [comment]
Starting VisualVM shows only a white screen

Steps: Just start the program.

![20220507_15h12m36s_grim](https://user-images.githubusercontent.com/81828120/167255967-43ba3197-8b95-4187-aa9c-3ccd7f0f56e7.png)

**Comment by pflaska** [comment]
I'm running VisualVM on Ubuntu 22.04 LTS (Wayland) without any problem.

Version: 2.1.2 (Build 211216); platform 20210621-2172674416
Linux (5.15.0-27-generic) , amd64 64bit
Java: 1.8.0_212; Java HotSpot(TM) 64-Bit Server VM (25.212-b31, mixed mode)

**Comment by Mesabloo** [comment]
I stumbled upon the same problem, though not on Wayland. The application rendered only a black/white background, but the GUI was still usable (mouse clicks could open menus etc.).

If you are using the XMonad window manager, adding `setWMName "LG3D"` to the startup hook (see https://stackoverflow.com/a/30742663/6718698) seems to solve the issue. (it did for me at least)

**Comment by angel-gruevski** [comment]
> I stumbled upon the same problem, though not on Wayland. The application rendered only a black/white background, but the GUI was still usable (mouse clicks could open menus etc.).
> 
> If you are using the XMonad window manager, adding `setWMName "LG3D"` to the startup hook (see https://stackoverflow.com/a/30742663/6718698) seems to solve the issue. (it did for me at least)

Unfortunately I am using Sway WM, and still having issues with VisualVM. On my end I can only see a blank white screen and nothing works.

**Comment by angel-gruevski** [comment]
With the help of the answer of the following link https://github.com/swaywm/sway/issues/595#issuecomment-214131422 , I was able to solve the issue.

One just needs to export an environment variable `export _JAVA_AWT_WM_NONREPARENTING=1`

**Comment by thurka** [comment]
@angel-gruevski Thanks for investigation it. This looks to me like generic JDK problem, which is not specific to VisualVM.
