### ISSUE TITLE
can not download Memory Pools in Plugins Centers 1.3.9

### ISSUE THREAD

**Issue by yang2yang** [oracle/visualvm#41]
I want to download Memory Pools manually.
My visualvm version is 1.3.9.
But I found that Memory Pools in https://visualvm.github.io/uc/release139/updates.html is Invalid.
And I also try to download other plugin like Visual GC.I found Visual GC is valid.

**Comment by rickardrockard** [comment]
This is already discussed in https://github.com/oracle/visualvm/issues/25
