### ISSUE TITLE
Remove Self time nodes from the sampler/profiler CPU trees when their total time is at 0,0 ms.

### ISSUE THREAD

**Issue by SuperPat45** [oracle/visualvm#423]
Remove Self time nodes from the sampler/profiler CPU trees when their total time is at 0,0 ms.

Maybe with an option?

Self time at 0,0 ms are not useful and would greatly simplify deep trees.

![image](https://user-images.githubusercontent.com/7791600/182821824-538fd541-f14a-469f-928d-87ed9fe5f137.png)

**Comment by thurka** [comment]
Ok, this could be implemented in a similar way heap viewer has 'Hide Classes With No Instances'.

![no_instances](https://user-images.githubusercontent.com/22048069/183640979-ead90272-0b43-4138-88bb-64fde345887a.png)

**Comment by thurka** [comment]
Below is the screenshot from the prototype. Is this what you requested?
![self](https://user-images.githubusercontent.com/22048069/186605208-e1112c30-1e64-4817-8d16-cfb7c673593a.jpg)

**Comment by SuperPat45** [comment]
Excellent !

**Comment by thurka** [comment]
Done in master.

**Comment by SuperPat45** [comment]
@thurka  How can I open this filter bar?
I know only the Ctrl+F shortcut who open a "Find" bar

**Comment by thurka** [comment]
Right-click in results and select 'Filter'. Shortcut is Ctrl-G.
