### ISSUE TITLE
GitHub issue template should explain how to obtain `messages.log`

### ISSUE THREAD

**Issue by Marcono1234** [oracle/visualvm#426]
**Is your feature request related to a problem? Please describe.**
The GitHub issue template currently only says:
https://github.com/oracle/visualvm/blob/0c39bd63aeb5134fa400021509b5bf85192efdd7/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L24

It might not be clear to users where to find this file.

**Describe the solution you'd like**
Extend the GitHub issue template to mention that the file can be obtained from "Help" > "About" > "Logfile" (or mention the default file path where it is stored).

**Comment by thurka** [comment]
Done.
