### ISSUE TITLE
Application snapshot is missing most of the data when not monitoring

### ISSUE THREAD

**Issue by sp1r0s** [oracle/visualvm#43]
If you try and take an application snapshot without actively monitoring the app the snapshot is pretty much empty. If this is "as designed", then you should disable the option to take a snapshot when the app is not being monitored.

**Comment by jisedlac** [comment]
This is as designed and we're not going to disable this option. You're still getting a lot of information - Java version, arguments, system properties, memory size, running threads etc., exactly what is this feature designed for. You'll also get all the thread dumps and heap dumps taken so far saved inside the application snapshot.
