### ISSUE TITLE
Heap dump file is not created (version 2.1.4)

### ISSUE THREAD

**Issue by aguedeney** [oracle/visualvm#433]
**Describe the bug**

After running a remote profiler session on my MacBook Pro, I clicked the heap button in the Monitor tab.  I looked in the remote profile computer (VirtualBox virtual) /tmp directory as described in the messagebox and could not find an .hprof tmp file.

I'm using JDK17 (latest) on the latest release of Alpine Linux in VirtualBox on a MacBook Pro.

**To Reproduce**

**Expected behavior**

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

messages.log is available via Help | About | Logfile and
via VisualVM | About VisualVM | Logfile on macOS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - JDK version [JDK 1.8.0_181]
 - Version [e.g. 2.0]

**Additional context**

**Comment by thurka** [comment]
Can you please attach messages.log? Thanks.

**Comment by thurka** [comment]
Closing until more info is available.
