### ISSUE TITLE
Does the project plan to support jdk9 ?

### ISSUE THREAD

**Issue by smarkm** [oracle/visualvm#44]
Does the project plan to support jdk9 ?

**Comment by jisedlac** [comment]
Not sure what you mean by supporting JDK 9. VisualVM 1.3.9 runs on JDK 9 and is able to monitor Java 9 applications. Do you experience any issues using Java 9?

**Comment by naoliv** [comment]
I can't run visualvm with JDK 9.
This is what I get when trying to run it:

```
$ visualvm 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
WARNING: Unknown module: jdk.jvmstat specified to --add-exports
WARNING: Unknown module: jdk.jvmstat specified to --add-exports
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/usr/share/netbeans/platform18/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Which is also https://bugs.debian.org/877792

Any ideas about the problem, please?

**Comment by thurka** [comment]
@naoliv This looks like OpenJDK problem. VisualVM 1.3.9 works fine for me on Oracle JDK 9. See attached image.
![visualvm_139](https://user-images.githubusercontent.com/22048069/32728021-0e51e020-c87f-11e7-977b-223b9db3bb21.png)

**Comment by thurka** [comment]
Note that you can run VisualVM on JDK 8 and monitor application running on JDK 9.
