### ISSUE TITLE
Not able to monitor remote applications

### ISSUE THREAD

**Issue by siddjain** [oracle/visualvm#443]
**Describe the bug**
I am not able to monitor remote applications with VisualVM.

  Product Version         = VisualVM 2.1.4
  Operating System        = Mac OS X version 11.6.8 running on x86_64
  Java; VM; Vendor        = 17.0.2; OpenJDK 64-Bit Server VM 17.0.2+8-86; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 17.0.2+8-86
  Java Home               = /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home

**To Reproduce**
I have tried it two ways. First using jstat. command to run jstat is:

```
jstatd -J-Djava.security.policy=.jstat.all.policy &
```

where

```
$ cat .jstatd.all.policy
grant codebase "jrt:/jdk.jstatd" {
permission java.security.AllPermission;
};
grant codebase "jrt:/jdk.internal.jvmstat" {
   permission java.security.AllPermission;
};
```

i can see:

```
$ ss -tpln
State      Recv-Q     Send-Q         Local Address:Port          Peer Address:Port     Process
LISTEN     0          80                 127.0.0.1:3306               0.0.0.0:*
LISTEN     0          128                  0.0.0.0:22                 0.0.0.0:*
LISTEN     0          50                         *:46015                    *:*         users:(("java",pid=767412,fd=10))
LISTEN     0          50                         *:42981                    *:*         users:(("java",pid=767412,fd=14))
LISTEN     0          50                         *:1099                     *:*         users:(("jstatd",pid=761237,fd=11))
LISTEN     0          50                         *:37199                    *:*         users:(("jstatd",pid=761237,fd=9))
```

Accordingly I attached to VM but don't see any applications in VisualVM. I have verified Java application is running on remote VM btw :)

The second way I tried is to use JMX as described [here](https://www.baeldung.com/visualvm-jmx-remote). I run the program using:

```
MAVEN_OPTS="-enableassertions -Dcom.sun.management.jmxremote.port=8080 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xms1024m -Xmx1024m" \
mvn exec:java -Dexec.mainClass=com.oracle.App -Dexec.cleanupDaemonThreads=false \
-Dexec.args="app.properties"
```

and add JMX connection. Again remote application is not listed in VisualVM

**Expected behavior**
Visual VM should show remote applications but nothing happens

**VisualVM log**
attached.

messages.log is available via Help | About | Logfile and
via VisualVM | About VisualVM | Logfile on macOS

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version see above
[visualvm.logfile.txt](https://github.com/oracle/visualvm/files/9585656/visualvm.logfile.txt)

**Additional context**

**Comment by siddjain** [comment]
screenshot
<img width="600" alt="Screen Shot 2022-09-16 at 9 26 56 AM" src="https://user-images.githubusercontent.com/758321/190686011-e53f712b-6ec7-4794-946b-2ac96614ceea.png">

**Comment by thurka** [comment]
VisualVM is probably not able to connect to your remote machine. This looks to me like a network configuration problem. Are there any firewalls between your macOS and remote machine?

**Comment by thurka** [comment]
According to GH-444, it seems that you find out, what is wrong and you are able to use `jstatd`. What was the problem?

**Comment by siddjain** [comment]
Hi, you are right. The problem was a firewall that was blocking the client to connect to port 1099. Fixed.

**Comment by robozb** [comment]
I can connect to my Tomcat8 server's JVM (behind a firewall, port is open) with JMX with these setting:

'''
#JAVA_OPTS="${JAVA_OPTS} \
#-Dcom.sun.management.jmxremote \
#-Dcom.sun.management.jmxremote.port=8019 \
#-Dcom.sun.management.jmxremote.rmi.port=8019 \
#-Dcom.sun.management.jmxremote.ssl=false \
#-Dcom.sun.management.jmxremote.authenticate=false \
#-Djava.rmi.server.hostname=wfs.hu"
'''
But If I try connect to jstatd nothong happen #433 

Policy file
'''
grant codebase "jrt:/jdk.jstatd" {
 permission java.security.AllPermission;
};
grant codebase "jrt:/jdk.internal.jvmstat" {
 permission java.security.AllPermission;
};

'''



![1](https://user-images.githubusercontent.com/8656998/207387265-25feac4d-ef1e-41e1-b9f5-e3ba3b5ab01c.JPG)
