### ISSUE TITLE
Cannot open JFR snapshot

### ISSUE THREAD

**Issue by pwinckles** [oracle/visualvm#447]
**Describe the bug**

I get the following errors in the VisualVM log when I attempt to open a JFR snapshot:

```
INFO [org.graalvm.visualvm.jfr.model.JFRModelProvider]: Could not load JFR snapshot (JDK11 loader): /Users/peter.winckles/Desktop/recording.jfr
INFO [org.graalvm.visualvm.jfr.model.JFRModelProvider]: Could not load JFR snapshot (generic loader): /Users/peter.winckles/Desktop/recording.jfr
SEVERE [org.graalvm.visualvm.jfr.view.JFRView]: No JFR model for /Users/peter.winckles/Desktop/recording.jfr
```

Interestingly enough, I am able to compile and run the following against the jars distributed with VisualVM:

```java
var con = JFRJDK11Model.class.getDeclaredConstructor(String.class, File.class);
con.setAccessible(true);
var model = con.newInstance("id", new File("/Users/peter.winckles/Desktop/recording.jfr"));
System.out.print(model.getJvmArgs());
```

**To Reproduce**

1. Open VisualVM
2. Click "Add JFR Snapshot"
3. **Type** in the path to the snapshot (May or may not be related, but I was unable to see the snapshot in the file chooser dialog)
4. See "Failed to read the JFR snapshot."

**Expected behavior**

The snapshot should have been opened.

**VisualVM log**

See above

**Screenshots**

NA

**Desktop (please complete the following information):**

```
  Product Version         = VisualVM 2.1.4
  Operating System        = Mac OS X version 12.4 running on aarch64
  Java; VM; Vendor        = 11.0.15; OpenJDK 64-Bit Server VM 11.0.15+10; Eclipse Adoptium
  Runtime                 = OpenJDK Runtime Environment 11.0.15+10
```

**Additional context**

NA

**Comment by thurka** [comment]
Can you please attach the jfr snapshot, so we can reproduce it? Whole VisualVM log will be also useful. Thanks.

**Comment by pwinckles** [comment]
I'll try to get the files together for you tomorrow

**Comment by pwinckles** [comment]
Could it possibly be related to running it on an M1? It is also puzzling that I was able to open the snapshot using the visualvm jars and the Java code I included, but could not through the gui.

**Comment by thurka** [comment]
I am able to open it on M1 as well. Can you try different JDK? What about the latest update of JDK 17?

**Comment by pwinckles** [comment]
Same result with a fresh install of JDK 17:

```
  Product Version         = VisualVM 2.1.4
  Operating System        = Mac OS X version 12.4 running on aarch64
  Java; VM; Vendor        = 17.0.4; OpenJDK 64-Bit Server VM 17.0.4+8-LTS; Amazon.com Inc.
  Runtime                 = OpenJDK Runtime Environment 17.0.4+8-LTS
```

However, I did some further experimenting and _was_ able to eventually get it open. I had original installed VisualVM using the app image. I tried downloading the zip, and started it from the terminal. From there, I _was_ able to open the snapshot. Next, I went to `/Applications/VisualVM.app/Contents/MacOS` in the terminal and invoked `visualvm` from there, and it worked there as well. Finally, I started VisualVM from spotlight/finder, and it still _failed_ to open the image! Very odd.

**Comment by thurka** [comment]
Can you please try to put your jfr file out of your Desktop, Downloads, and Documents folders? Maybe this change will allow you to open the jfr file.

**Comment by pwinckles** [comment]
Yep, moving the snapshot does make it work.

**Comment by thurka** [comment]
Closing.
