### ISSUE TITLE
Make it possible to refresh connections.

### ISSUE THREAD

**Issue by mihxil** [oracle/visualvm#45]
I use to tunnel JMX ports for remote hosts. This works (though I don't quite get why the local port must equal the actual port).

The annoying thing it that the connection is made only once. If the remote server restarts, or so, I must restart visualvm too. Which is inconvenient and sometimes even more than that, because I might have other connections to other applications open too (e.g with open graphs).

A simple 'reconnect' option, which will for a certain connection simply completely rebuild it, would be handy.  

What one now tends to do is close the concerning tab, and try to reopen it by clicking in the left overview of applications. But it seems to do some caching there or something, and therefore in these cases  it simply doesn't work. You end up with a new tab with hardly anything useful in it.  You have to completely restart visualvm, which I find myself doing sometimes dozens of times per day.

**Comment by jisedlac** [comment]
Hello, thanks for the feedback! We're aware of this annoyance and plan to address it in some of the future VisualVM releases. Unfortunately it's not a quick-fix as it requires some API changes in the VisualVM core (currently a terminated/lost connection app cannot be resurrected).

**Comment by mageddo** [comment]
I've the same requirement, I am doing some tests connecting to a JVM inside a docker container then I have to restart it many times and today I have to restart visualvm as well.

**Comment by vmoloko** [comment]
+1

**Comment by humera-khan** [comment]
+1, Instead of restarting, again and again, we can have "refresh" option.

**Comment by seadub** [comment]
+1. Certainly a struggle.

Running on Mac OS High Sierra.

**Comment by sm4rk0** [comment]
**PLEASE, don't comment with a "+1".**
A lot of people are receiving useless email every time someone does that.

It should be enough to hit "thumbs up" at the original post and subscribe to the issue to be notified when it's closed.

**Comment by mcekovic** [comment]
+1 (this one is ultimate annoyance)

**Comment by tenstriker** [comment]
Any updates on this? Been over a year now since case was opened.

**Comment by krishna81m** [comment]
Woah, looks like its been like this for years now :), any idea when this will be fixed?

**Comment by Diarsid** [comment]
+1

**Comment by jisedlac** [comment]
Fixed in master.

**Comment by seadub** [comment]
Can you share the commit for us?

**Comment by jeffwidman** [comment]
Nudge @jisedlac ☝️

**Comment by jisedlac** [comment]
Actually a lot of commits related to the JMX improvements, feel free to browse at https://github.com/oracle/visualvm/commits/master.

Just released in VisualVM 2.0, enjoy! More improvements already pending, stay tuned.

**Comment by seadub** [comment]
Great news, thank you @jeffwidman  and @jisedlac!

**Comment by mihxil** [comment]
Thanks a lot. Much better!

**Comment by cowwoc** [comment]
It's nice that this is fixed, but how does one force a refresh?

**Comment by vadipp** [comment]
Just click right click on a connection in the list and click Connect. A Refresh button will appear in the already open tab for that connection. Click it and the tab will be refreshed.
Better than it used to be. Though I don't understand why it should be a three-click operation, instead of one-click 🤦‍♂️

**Comment by cowwoc** [comment]
In my experience the "connect" button is grayed out, and while "auto connect" is enabled it does not seem to work. The connection stays grayed out.

If, however, I uncheck "auto connect" and re-check it, a refresh gets triggered.

**Comment by thurka** [comment]
> In my experience the "connect" button is grayed out, and while "auto connect" is enabled it does not seem to work.

Right, see #422.
