### ISSUE TITLE
Allow keyboard shortcut to execute oql

### ISSUE THREAD

**Issue by byteit101** [oracle/visualvm#454]
**Is your feature request related to a problem? Please describe.**
When typing OQL, my hands are on the keyboard. I have to move them to the mouse to execute oql. If there was a keyboard shortcut, I could iterate faster on my OQL queries

**Describe the solution you'd like**
Ctrl-Enter, Shift-Enter, or some other similarly common shortcut when focused in the oql query box should cause oql execution
The shortcut should be then listed in the tooltip

**Comment by thurka** [comment]
Done in master. The shortcut is Crtl-R and is displayed in the tooltip of the execute action.
