### ISSUE TITLE
Change the display font of VisualVM

### ISSUE THREAD

**Issue by mikelue** [oracle/visualvm#456]
**Is your feature request related to a problem? Please describe.**
This is not a problem of software.

I am using `Windows 11`(`Traditional Chinese(CP-950)`) with `Java 17`,
how do I change the fonts shown on my computer?

![圖片](https://user-images.githubusercontent.com/556726/196099280-f1c82686-62d7-4cd6-abf2-acd45175edda.png)

I've tried [Font configuration file](https://docs.oracle.com/en/java/javase/18/intl/font-configuration-files.html), and it does have some affects.

I want to know what can change the fonts, e.g., text in _summary_ area.

Any thinking or suggestion would be appreciated, thanks a lot.

My `fontconfig.properties`
[fontconfig.zip](https://github.com/oracle/visualvm/files/9810347/fontconfig.zip)

**Comment by thurka** [comment]
Can you please attach your font configuration file?

**Comment by mikelue** [comment]
> Can you please attach your font configuration file?

I've attach file in the description, thanks for your reply.

**Comment by thurka** [comment]
> I've attached file in the description

Thanks. I will try to find out, why it does not work for you. BTW: Which font do you want to use in summary area?

**Comment by mikelue** [comment]
> > I've attached file in the description
> 
> Thanks. I will try to find out, why it does not work for you. BTW: Which font do you want to use in summary area?

I would like use monospaced fonts in most areas of application, if not too trouble.
Thanks a lot.

**Comment by thurka** [comment]
Please try to run visualvm using the command below:
```
visualvm.exe -J-Dswing.useSystemFontSettings=false -J-Dnetbeans.plaf.disable.ui.customizations=true
```
This should use fonts defined in your `fontconfig.properties` file. In addition to that your `fontconfig.properties` file is missing Font file name properties for your fonts. 
```
filename.<PlatformFontName>=<File.ttf>
```
The documentation says that "File names are required for all physical fonts on Windows".

**Comment by thurka** [comment]
To debug processing of `fontconfig.properties` file you can add `-J-Dsun.java2d.debugfonts=true` to commandline. The debug output will be in VisualVM log file (Help->About->Logfile).

**Comment by mikelue** [comment]
Everything is as good as I want! Thanks for your help. 😁

This is my startup command:
```sh
visualvm -J-Dsun.java2d.uiScale=1.0 --fontsize 13 -J-Dswing.useSystemFontSettings=false -J-Dnetbeans.plaf.disable.ui.customizations=true
```
