### ISSUE TITLE
Unusual proxy port notation

### ISSUE THREAD

**Issue by FieteO** [oracle/visualvm#457]
**Is your feature request related to a problem? Please describe.**
When entering a proxy port in *Tools -> Options -> Network* it first is displayed as `8080`, which is what I would expect.
Upon clicking into other inputs, the `8080` is then displayed as `8,080`, which I find really irritating as a user.

**Describe the solution you'd like**
I would expect the port not to have any commas in it.

**Comment by thurka** [comment]
Note that this `,` is a thousands separator used by default number formatter.

**Comment by thurka** [comment]
You are right that it is unusual. I just wanted to explain, why `,` is there.

**Comment by thurka** [comment]
Fixed in master.
