### ISSUE TITLE
VisualVM does not support JDK 19

### ISSUE THREAD

**Issue by otavio-silva** [oracle/visualvm#458]
**Describe the bug**
VisualVVM does not support JDK 19, the current default version of JDK as made recently.

**To Reproduce**
1. Installed through Scoop using `scoop install visualvm`
2. Opened VisualVM

**Expected behavior**
The software to open properly, I guess

**VisualVM log**
Can't

**Screenshots**
![image](https://user-images.githubusercontent.com/22914610/196287229-906d8b68-f116-4334-a0a8-dfa1816cf14d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Ver 21H2
 - JDK version: temurin-jdk 19.0.0-36

**Additional context**
JDK 19 solved a bug related to UTF-8 characters on path, so using older JDK versions is not an option for me, see [here](https://stackoverflow.com/questions/73665603/java-doesnt-recognize-unicode-character-in-path-on-windows-11)

**Comment by thurka** [comment]
JDK-19 support is tracked by GH-415. It will be part of next VisualVM release.

**Comment by thurka** [comment]
VisualVM 2.1.5 supports JDK 19.
