### ISSUE TITLE
java.lang.StackOverflowError in CPUCCTContainer.addFlatProfTimeForNode()

### ISSUE THREAD

**Issue by ewirch** [oracle/visualvm#46]
Version: 1.3.9

I've been sampling cpu, creating thread dumps and snapshots when this exception occurred. See attached log.

[messages.log](https://github.com/oracle/visualvm/files/1494830/messages.log)

**Comment by thurka** [comment]
You can increase default VisualVM stack size by starting it with `-J-Xss<size>`, where `<size>` is a size of stack size. Is your application running with default `-Xss` setting? Does it have deep stack traces?
