### ISSUE TITLE
version2.15 can not launched on jdk17.0.5  

### ISSUE THREAD

**Issue by Lovecxgood** [oracle/visualvm#460]
The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: package sun.awt.X11 not in java.desktop
Error: Could not find or load main class org.netbeans.Main
Caused by: java.lang.ClassNotFoundException: org.netbeans.Main

**Comment by thurka** [comment]
This looks to me like broken installation. Please double check that visualvm zip was correctly extracted. If this is not the case, please start visualvm from command line with:
```
visualvm.exe --trace C:\log.txt
```
and attach the `log.txt` file to this issue. Thanks.

**Comment by Spartak101** [comment]
Та же история для JDK 19 и 16.
А команда вообще не распозналась
![Screenshot_1](https://user-images.githubusercontent.com/124740564/217381373-fb17ee74-736f-4a63-b167-53034b1dd05d.png)

**Comment by pseudo555** [comment]
No issue on my side (win 10 x64 22h2), but when i start a program by eclipse, from time to time, the application is not properly recognized. In such case, visualvm saw a "local application".
I guess, the eclipse JVM is not well recognized by visualvm.

**Comment by thurka** [comment]
> when i start a program by eclipse, from time to time, the application is not properly recognized. In such case, visualvm saw a "local application".

This looks similar to GH-493.

**Comment by pseudo555** [comment]
> > when i start a program by eclipse, from time to time, the application is not properly recognized. In such case, visualvm saw a "local application".
> 
> This looks similar to [GH-493](https://github.com/oracle/visualvm/issues/493).

You're absolutely right.

**Comment by thurka** [comment]
Closing as duplicate of GH-493.
