### ISSUE TITLE
Nothing happen when I try to add jstatd connection

### ISSUE THREAD

**Issue by robozb** [oracle/visualvm#469]
I can connect to my Tomcat8 server's JVM (behind a firewall, port is open) with JMX with these settings:

```
#JAVA_OPTS="${JAVA_OPTS} \
#-Dcom.sun.management.jmxremote \
#-Dcom.sun.management.jmxremote.port=8019 \
#-Dcom.sun.management.jmxremote.rmi.port=8019 \
#-Dcom.sun.management.jmxremote.ssl=false \
#-Dcom.sun.management.jmxremote.authenticate=false \
#-Djava.rmi.server.hostname=wfs.hu"
```
But If I try to connect to jstatd nothing happens

Policy file(jstatd-java11.policy)
```
grant codebase "jrt:/jdk.jstatd" {
 permission java.security.AllPermission;
};
grant codebase "jrt:/jdk.internal.jvmstat" {
 permission java.security.AllPermission;
};
```
Start.sh
```
#!/bin/bash
/usr/lib/jvm/java-11-openjdk-amd64/bin/jstatd -p 1089 \
-J-Djava.security.policy=./jstatd-java11.policy \
-J-Djava.rmi.server.hostname=192.168.1.12 \
-J-Djava.rmi.server.logCalls=true \
-J-Djava.net.preferIPv4Stack=true
```

But It seems there is communication between the VisualVM and server:

![1](https://user-images.githubusercontent.com/8656998/207393124-f6cbf4a1-a520-4218-aac8-e4b89b3c9099.JPG)

VisualVM infos:
JVM: Java HotSpot(TM) 64-Bit Server VM (11.0.16.1+1-LTS-1, mixed mode)
Java: version 11.0.16.1 2022-08-18 LTS, vendor Oracle Corporation
Java Home: G:\Program Files\Java\jdk-11.0.16.1

Server infos:
root@lxc-web-sajat-java:~/visualvm# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@lxc-web-sajat-java:~/visualvm# java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb10u1, mixed mode, sharing)

**Comment by thurka** [comment]
Some discussion about `jstatd` is here: https://stackoverflow.com/questions/40288382/how-to-force-or-predict-the-second-open-port-of-jstatd

**Comment by thurka** [comment]
There is JDK issue, which should address your problem https://bugs.openjdk.org/browse/JDK-8196729 .

**Comment by thurka** [comment]
Closing.
