### ISSUE TITLE
Extract a .class of an object in the heap dump

### ISSUE THREAD

**Issue by jbescos** [oracle/visualvm#471]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I would like to download the .class of a certain object in the heap dump. I don't know whether this is possible.

**Describe alternatives you've considered**
N/A

**Additional context**
Sometimes there are some third party libraries that you want to investigate, so I would be good to be able to extract the .class from the heap dump.

**Comment by thurka** [comment]
Unfortunately java bytecode is not part of the heap dump file.

**Comment by jbescos** [comment]
OK, then we can close it. Thank you for the information.
