### ISSUE TITLE
VisualVM 2.1.5 does not load VM (Not supported for this JVM.)

### ISSUE THREAD

**Issue by wirowka** [oracle/visualvm#472]
**Describe the bug**
Everyone, try to connect to JVM running in Linux RHEL 8.4 (OpenJDK Runtime Environment Corretto-8.242.07.1) from a Windows Server (2019) where I started VisualVM 2.1.5 (with Corretto jdk11.0.17_8). 
A single port jmx port (6089) - between Windows Server and Linux running the JVM - is opened - VisualVM looks like attempting to connect, but every is grey out and I see "Not supported for this JVM." 

**To Reproduce**
1. Add remote server
2. Add remote JMX connection
3. Connect

**Expected behavior**
Status of a remote JVM

**VisualVM log**
[logfile.txt](https://github.com/oracle/visualvm/files/10331021/logfile.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/21661371/210219706-44f6085f-1a62-4055-8e09-23b99f18c22a.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Corretto jdk11.0.17_8

**Comment by wirowka** [comment]
I found the issue, closing

**Comment by thurka** [comment]
> I found the issue, closing

Some details are at https://gitter.im/VisualVM/Feedback?at=63b2a68c410c633d4806c268

**Comment by WestFarmer** [comment]
for me, set both port to the same: 
```
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 8888; nested exception is: 
        java.net.BindException: Address already in use (Bind failed)
sun.management.AgentConfigurationError: java.rmi.server.ExportException: Port already in use: 8888; nested exception is: 
        java.net.BindException: Address already in use (Bind failed)
        at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:480)
        at sun.management.Agent.startAgent(Agent.java:262)
        at sun.management.Agent.startAgent(Agent.java:452)

```
