### ISSUE TITLE
JFluid wire protocol error: code does not correspond to command or response.

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#476]
Sometimes profiling fails with the error below:
```
*** Profiler error (Thu Jan 05 14:50:48 CET 2023): exception while trying to get response from the target JVM:
java.io.IOException: JFluid wire protocol error: code does not correspond to command or response. Value 28
*** Profiler error (Thu Jan 05 14:50:48 CET 2023): exception when trying to send a response: java.net.SocketException: Socket closed
```

**Comment by joy-jreij** [comment]
@thurka I am getting the same IOException but with a different "Profiler error":

`Profiler Agent Error: Exception when handling command from client:
java.io.IOException: JFluid wire protocol error: code does not correspond to command or response. Value -1
Profiler Agent: Connection with agent closed`

**Comment by thurka** [comment]
@joy-jreij This looks to me like different issue. Can you please file a separate bug report? Thanks.

**Comment by WernherVonData** [comment]
Got similar issue as @joy-jreij  - is there a ticket for that? Didn't see any on the list. For me removing the location given to the `--userdir` helped (might be just a coincidence as well).

**Comment by thurka** [comment]
This particular problem of "_code does not correspond to command or response_" (identified by `Value` > 0) happens when reading `RootClassLoadedCommand`.

**Comment by thurka** [comment]
Fixed in master.
