### ISSUE TITLE
JDBC profiler - SQL query is truncated to 1024 chars

### ISSUE THREAD

**Issue by da-z** [oracle/visualvm#482]
**Describe the bug**
JDBC profiler - SQL query is truncated to 1024 chars.

**To Reproduce**
1. Profile JDBC
2. Right click on SQL Query in the profiling results -> View SQL query

**Expected behavior**
The query is not truncated

**Actual**
Query is truncated to 1024 characters

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version OpenJDK 64-Bit Server VM (18.0.2.1+1-1, mixed mode, sharing)
 - Version 2.1.5

**Comment by thurka** [comment]
You are right, the limit is 1024 chars and it is currently not configurable. As a workaround you can change MAX_STRING_LENGTH constant in ProfilerRuntimeCPUand rebuild VisualVM. This way you can increase the max char limit of SQL query. There are additional limits and currently you can probably set it maximally to 8450. Can you provide more info about your use-case? Why the queries are so long and why is so important not to truncate them? Are they computer generated?

**Comment by da-z** [comment]
Thank you for the advice. Yes, I am using VisualVM to inspect some SQL queries. The advantage over say Hibernate SQL logs being that the query has the parameters bound inline instead of showing as ?. I prefer this method over hijacking the jdbc driver :)

**Comment by da-z** [comment]
Works like a charm, thank you. I upped to 2048 * 4

**Comment by otbutz** [comment]
@thurka I think the issue itself is still relevant. For those of us who are dealing with ORM frameworks, it would be very helpful to be able to change that limit without rebuilding visualvm. If there's a technical limit, the settings UI would be the best place to define an upper limit.

**Comment by ismail-bertalfilali** [comment]
Hello,
   this is very important feature, can we make it configurable ?
