### ISSUE TITLE
Delay loading previous nps captures for servers in Applications tree

### ISSUE THREAD

**Issue by ronosaurus** [oracle/visualvm#485]
I have a bad habit of keeping many nps accessible within the Applications tree. I've noticed when I let nps files pile up over several weeks the available memory of VisualVM continues to decrease at launch because it seems to load each nps file at startup. This is what the memory graph looked like when I start with VisualVM with 50+ nps files spread across many servers in the Applications tree:

![image](https://user-images.githubusercontent.com/2015016/221974904-102889f1-3f22-42d3-822d-dbdc66c3259b.png)

Clicking on the graph to trigger a GC doesn't free up memory. When I delete all the nps files from the tree there is more memory available:

![image](https://user-images.githubusercontent.com/2015016/221975217-3ace9cda-92b9-446e-bf24-5b6771b8403d.png)

It would be nice if there were an option to opt-out of loading previous nps files until they were actually needed. I'm ok with losing the friendly name "[snapshot] Feb 28, 2023 11:10:00 AM" and only have a file create time if it means I'll have gigabytes more memory to do captures. Can the "[snapshot] ..." stuff be extracted from the file then close the file so it doesn't consume any memory?

Assuming there's an opt-in feature to delay loading previous nps files, perhaps there could be a right click menu item to parse/load all snapshots at this level of the tree:

![image](https://user-images.githubusercontent.com/2015016/221976401-7e7844bd-075d-4349-ae83-3ff403675139.png)

My distribution of nps files is typically two dozen remote servers in the Applications tree each with 15-35 nps files. I typically only work with one or two servers at a time on a given day. I keep the files in the tree because I may go weeks between re-visiting the server and being able to see what happened in the past is helpful.

**Comment by thurka** [comment]
Done in master.

**Comment by ronosaurus** [comment]
Wanted to share that the issue was fixed correctly at startup:

![image](https://user-images.githubusercontent.com/2015016/236967752-cf9210b9-6ee7-4ddb-ba93-d062b6f1711c.png)

and after clicking on the graph to trigger a GC:

![image](https://user-images.githubusercontent.com/2015016/236967791-97d57a51-1da7-4424-bba1-6cefd81380a6.png)

Thank you

**Comment by thurka** [comment]
You are welcome. BTW: Running VisualVM with ~6GB Xmx is not necessary.
