### ISSUE TITLE
Cannot instantiate remote class *

### ISSUE THREAD

**Issue by NguyenMinhDung** [oracle/visualvm#49]
When I used visualvm to monitor spring application, I clicked Mbean->Operator-> My method, i receive error cannt instantiate remote class *
![capture](https://user-images.githubusercontent.com/2491855/34642991-22fe28f8-f34f-11e7-86a0-754af516fa0b.PNG)
![capture2](https://user-images.githubusercontent.com/2491855/34642992-2333f550-f34f-11e7-84f2-25362bc4b276.PNG)

Please help me, thank you.

**Comment by jisedlac** [comment]
Hello, according to the sources at https://github.com/oracle/visualvm/blob/master/plugins/mbeans/src/com/sun/tools/visualvm/modules/mbeans/XMBeanOperations.java#L202, you're hitting a ClassNotFoundException. This means that your method isn't configured correctly. This is unrelated to VisualVM.
