### ISSUE TITLE
Application detected as "Local Application"

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#493]
When the machine is a under heavy load, newly created local applications are sometimes detected as "Local Application" and when they are opened, they have no details. See attached screenshot.

<img width="767" alt="local_app,png" src="https://user-images.githubusercontent.com/22048069/235226289-233a7f70-c82b-4983-b775-69173fb5f98f.png">

In addition, `messages.log` file contains the following message:
```
INFO [org.graalvm.visualvm.jvmstat.JvmstatModelProvider]: java.property.java.vm.version is null
```

**Comment by thurka** [comment]
Fixed in master.

**Comment by pseudo555** [comment]
Is it really in 2.1.6 ?
![image](https://github.com/oracle/visualvm/assets/18347988/9aecfdbb-7e96-42df-96ec-01228de8532c)

I still got it for a java application started by eclipse in debug mode (using embedded eclipse JVM 17.0.6).
