### ISSUE TITLE
Profiler tabs show same results

### ISSUE THREAD

**Issue by erazor-de** [oracle/visualvm#496]
Hello,
I tried using VisualVM 2.1.6 on Linux in combination with Adoptium JDK 17.

How to reproduce the issue:
Start VisualVM
Run a Java application
Open this local application in VisualVM
Start CPU profiling, use the application and stop profiling.
-> Results in monitor, threads and profiler tabs.
Now stop and restart the application under test
-> Application has different pid now
Open this local application in VisualVM
Start CPU profiling, use the application and stop profiling.
-> Results in monitor, threads and profiler tabs.
Switch back to tab of first application profiling data.
-> The profiling data of the first invocation has been replaced with the second profiling data. Both show the same profile data now while monitor and threads tabs show their individual data.

I hope you can reproduce this.

**Comment by thurka** [comment]
Thanks, I am able to reproduce it.

**Comment by thurka** [comment]
Fixed in master.
