### ISSUE TITLE
Save connections for later use

### ISSUE THREAD

**Issue by gerbsen** [oracle/visualvm#5]
Hello,
I have to connect via Port Forwarding to a JVM inside a VPN. The problem is now, that I have to enter the JMX connection details every time I restart VisualVM. Is this normal? How can I circumvent this?

Cheers,
Daniel

**Comment by jisedlac** [comment]
Hi Daniel, could you please describe your steps in more details? In general, if you create a JMX connection using the Add JMX Connection action in VisualVM, the connection is restored on subsequent VisualVM sessions as long as you don't clear the user directory. Did you check the VisualVM logfile for any errors (Help | About | Logfile)?

**Comment by gerbsen** [comment]
Sorry, I should have been more precise. I've seen the feature that the JMX get's restored after relaunch, but this only works if my port forwarding is active the next time. If I start VVM without the port forwarding active nothing is restored and I have to add this again.

**Comment by jisedlac** [comment]
Fixed in master.
