### ISSUE TITLE
1.4 missing Visual GC plugin

### ISSUE THREAD

**Issue by TimMoore** [oracle/visualvm#50]
After updating to VisualVM 1.4, I can no longer install the Visual GC plugin.

On the [releases](https://github.com/oracle/visualvm/releases) page, I see a `com-sun-tools-visualvm-modules-visualgc.nbm` asset for the 1.3.9 release, but not for 1.4.

Has this been removed intentionally? It is still listed on the [Plugins](https://visualvm.github.io/plugins.html) page of the web site.

**Comment by thurka** [comment]
Visual GC plugin should be now available for VisualVM 1.4.

**Comment by TimMoore** [comment]
Great! Thank you.

**Comment by samspycher** [comment]
That's got to be my shortest experienced time from follow to fix-notification for a pre-existing ticket, thanks! 💯

**Comment by unlimitedsola** [comment]
is Visual GC plugin open source?
