### ISSUE TITLE
Update password for existing JMX Connection

### ISSUE THREAD

**Issue by jbreitman** [oracle/visualvm#512]
My company uses authenticated JMX Connections and periodically requires us to update our password.
I am forced to delete all of my JMX Connections and can't find a way to update the password once I set and save it.  The credential fields are greyed out.

I would like to see VisualVM prompt me when authentication fails and give me the ability to update my password without recreating the JMX Connection.  Ultimately, I would store the credentials once, assign a profile name to that credential pair and assign the authentication profile to a JMX Connection.

Please let me know if a solution already exists or if you can implement my suggestion.
I am running VisualVM 2.1.3 on macOS.

**Comment by thurka** [comment]
> Please let me know if a solution already exists or if you can implement my suggestion.

Thanks for the feedback. Let me see if there is a way to implement it.

**Comment by jbreitman** [comment]
I appreciate your help.  This will be a big win.  Thank you.

**Comment by jbreitman** [comment]
@thurka - Were you able to reproduce the issue that I described and identify a fix?

**Comment by thurka** [comment]
Yes, I am able to reproduce the issue.

**Comment by jbreitman** [comment]
Are you able to provide me with an update?  The solution will help me a lot.

**Comment by jbreitman** [comment]
Are you able to provide me with an update? The solution will help me a lot.

**Comment by thurka** [comment]
Done in trunk. VisualVM prompts you when authentication fails. The new username and password are stored for subsequent connections.

**Comment by jbreitman** [comment]
Thank you very much.  We are in the process of testing and this update will be very helpful.

**Comment by thurka** [comment]
Fix is part of VisualVM 2.1.9

**Comment by jbreitman** [comment]
Thank you.
My team tested and reported that they were not challenged / prompted when opening an existing "Connect Automatically" JMX Connection with credentials that no longer work.  We also disabled the "Connect Automatically" and had the same result when clicking "Connect" on that JMX Connection.  Is there anything we need to do on our side with preferences or settings?

**Comment by thurka** [comment]
> they were not challenged / prompted when opening an existing "Connect Automatically" JMX Connection with credentials that no longer work.

This is strange, since the connection with wrong password should fail and you should see the connection dialog with username and password. Can you describe in more detail what JMX settings are used on monitored JVM?

**Comment by thurka** [comment]
I was using this for testing:
```
/usr/lib/jvm/java-11-openjdk-amd64/bin/jrunscript -J-Dcom.sun.management.jmxremote.port=5321 -J-Dcom.sun.management.jmxremote.password.file=/tmp/jmxremote.password -J-Dcom.sun.management.jmxremote.ssl=false
```
The steps were:
- add JMX connection to above process
- quit VisualVM
- change password in `/tmp/jmxremote.password`
- start VisualVM
- connect to JMX
- username/password dialog appears
- filed new password
- connection were establised
- restart VisualVM
- connection works without asking for new password

**Comment by jbreitman** [comment]
The differences that I see are that our JMX Authentication uses LDAP via JAAS with SSL and we do not restart the Java Service after a person resets their password.  The VisualVM Client was restarted as the person is using the new version.

**Comment by thurka** [comment]
> JMX Authentication uses LDAP via JAAS with SSL

This is problably the reason, why you don't see the username/password dialog. For some reason it behaves differently from ordinary case with password file. Please provide steps how to replicate your setup. Thanks.

**Comment by thurka** [comment]
Any update on your setup?

**Comment by jbreitman** [comment]
https://docs.oracle.com/en/java/javase/17/management/monitoring-and-management-using-jmx-technology.html#GUID-F08985BB-629A-4FBF-A0CB-8762DF7590E0

Go to the section "Using LDAP Authentication" and there is a sample command line below that.

**Comment by thurka** [comment]
OK, now I know about LDAP, but what other JMX features do you use? What jmx related commnadline options do you use?

**Comment by jbreitman** [comment]
-Dcom.sun.management.jmxremote.port=1111
-Djava.security.auth.login.config=/dir/jaas.conf
-Dcom.sun.management.jmxremote.authenticate=true
-Dcom.sun.management.jmxremote.login.config=JmxAuth
-Dcom.sun.management.jmxremote.access.file=/dir/jmxremote.access
-Dcom.sun.management.jmxremote.ssl=true
-Dcom.sun.management.jmxremote.ssl.config.file=/dir/jmxAuthSSL.conf

**Comment by thurka** [comment]
Hmm, interesting. You have both LDAP and password authentication enabled together. How does that work? Which technology is used first?

**Comment by jbreitman** [comment]
Our configuration uses LDAP and LDAP has passwords as one of its attributes.  I do not believe I understand your question.  Please clarify.

**Comment by thurka** [comment]
> Please clarify.

Ok, I will try. JMX can use different authorizations. One possibility is to use LDAP. Another possibility is to use [file based authorization](https://docs.oracle.com/javadb/10.10.1.2/adminguide/radminjmxenablesimpleauth.html).

LDAP authorization is enabled by:
```
-Djava.security.auth.login.config=/dir/jaas.conf
-Dcom.sun.management.jmxremote.login.config=JmxAuth
```

File based authorization is enabled by:
```
-Dcom.sun.management.jmxremote.authenticate=true
-Dcom.sun.management.jmxremote.access.file=/dir/jmxremote.access
```

Looking at your commandline options, you have both enabled and I find that strange.
Why do use both? Which technology is used first?

**Comment by jbreitman** [comment]
For our purposes, com.sun.management.jmxremote.authenticate means do you want to challenge people for authentication or not.  The documentation references passwords, but it does not say local passwords based on my reading.  In our case, we use LDAP as the password store.

The com.sun.management.jmxremote.access.file option references a file that includes a group and type of access that group has after they authenticate.  The group ties back to LDAP for us.  (read or readwrite)

We do not use the password file option.
I think this is a good reference.  https://docs.oracle.com/en/java/javase/17/management/monitoring-and-management-using-jmx-technology.html#GUID-F08985BB-629A-4FBF-A0CB-8762DF7590E0

**Comment by thurka** [comment]
> We do not use the password file option.

OK, I finally figured out what is going on. I misplaced `com.sun.management.jmxremote.access.file` for `com.sun.management.jmxremote.password.file`.

**Comment by thurka** [comment]
The problem with LDAP is caused by the following JDK bug: https://bugs.openjdk.org/browse/JDK-8338037
