### ISSUE TITLE
Wrong max heap detected when using Generational ZGC.

### ISSUE THREAD

**Issue by sblantipodi** [oracle/visualvm#518]
Hi,
I'm trying to use latest VisualVM on one of my app that uses JDK21 along with Generational ZGC.

If I use the Generational ZGC flag the max heap size is double than what I specified in the XMX flag.
![image](https://github.com/oracle/visualvm/assets/4722227/8cd0b0ab-ffa1-4747-94f2-0956711360dd)
![image](https://github.com/oracle/visualvm/assets/4722227/5aa061ee-195f-411a-9c64-5af96e63eac4)

If I remove Generational flag, max heap size is respected.
![image](https://github.com/oracle/visualvm/assets/4722227/1519c8bb-6c18-4b5d-8c23-6b0086d68f6d)
![image](https://github.com/oracle/visualvm/assets/4722227/e55d2853-7ce8-42a0-845b-b47e30337b77)

Is this a bug in VisualVM or it's a behaviour that I'm not understanding currently?

Thanks

**Comment by thurka** [comment]
@sblantipodi Thanks for report. I need to take a look how Generational ZGC reports memory usage via Jvmstat. Maybe this bug in VisualVM maybe this bug in JDK 21.

**Comment by sblantipodi** [comment]
ok thank you for the answer. 👍

**Comment by thurka** [comment]
This issue looks similar to G1 issue GH-127.

**Comment by thurka** [comment]
> yes the problem is very similar, it seems fixed now with G1

I know, It is fixed. I added the workaroud for G1. Unfortunately the similar workaround would be probably needed for ZGC. :-(

**Comment by thurka** [comment]
Fixed in master.
