### ISSUE TITLE
Strange Class (Array) Name Displayed in Heap Histogram

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#523]
Windows 10, OpenJDK 21 build from https://jdk.java.net/21/, VisualVM devbuild with support for Java 21.

Started JConsole from the OpenJDK, started Memory Sampler for its process, the Heap Histogram shows strange item `Ljdk.internal.vm.FillerArray;`.

![array_name](https://github.com/oracle/visualvm/assets/22048050/c61bb4a8-5ee4-4e80-874d-a372f2b1f5a8)

**Comment by thurka** [comment]
`FillerArray` was introduced by https://bugs.openjdk.org/browse/JDK-8284435 .

**Comment by thurka** [comment]
.. and renamed by https://bugs.openjdk.org/browse/JDK-8294000

**Comment by thurka** [comment]
This is now tracked at https://bugs.openjdk.org/browse/JDK-8319548

**Comment by thurka** [comment]
Closing. JDK bug was fixed.
