### ISSUE TITLE
Problems Displaying OS in JFR Viewer

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#524]
Windows 10, OpenJDK 21 build from https://jdk.java.net/21/, VisualVM devbuild with support for Java 21.

Started JConsole from the OpenJDK, created a JFR snapshot of its process. In the Environment tab the OS: line is empty and the OS details pane displays the OS string on a new line.

![jfr_os](https://github.com/oracle/visualvm/assets/22048050/7ce5d5fe-497d-460f-8018-119f3665c329)

**Comment by thurka** [comment]
Fixed in master.
