### ISSUE TITLE
VisualVM crashes on macOS 14.0 Sonoma at launch (due to no longer supported Carbon menu APIs)

### ISSUE THREAD

**Issue by fwcd** [oracle/visualvm#528]
**Describe the bug**
VisualVM crashes on macOS 14.0 Sonoma.

**To Reproduce**

1. Open VisualVM on macOS 14

**Expected behavior**

To not crash.

**Crash log**

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               java [13354]
Path:                  /opt/homebrew/*/java
Identifier:            java
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        Exited process [13244]
User ID:               501

Date/Time:             2023-10-04 13:39:06.2193 +0100
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        F77EC4D1-E3BB-6DA3-0587-1AC8732E6ACD

Sleep/Wake UUID:       2FEAA728-CBAD-4DFF-8DD6-2FAEF239C7A1

Time Awake Since Boot: 370000 seconds
Time Since Wake:       12415 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000189ed961c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [13354]

Application Specific Information:
References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.
```

Full crash log: [visualvm-sonoma-crash.txt](https://github.com/oracle/visualvm/files/12803452/visualvm-sonoma-crash.txt)

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - JDK version: OpenJDK 21 (Homebrew)
 - Version: 2.1.7

**Additional context**

**Comment by thurka** [comment]
It does not look to me like VisualVM bug.

**Comment by fwcd** [comment]
Looks like it could also be a bug in Apple's `JavaRuntimeSupport` framework (or somewhere in between that and `AppKit`), I've sent the crash log to them.

**Comment by thurka** [comment]
FYI: I am able to run VisualVM 2.1.7 on official build of OpenJDK 21 just fine on macOS 14.0. 
```
-------------------------------------------------------------------------------
>Log Session: Wednesday, October 4, 2023, 7:33:22 PM Central European Summer Time
>System Info: 
  Product Version         = VisualVM 2.1.7
  Operating System        = Mac OS X version 14.0 running on x86_64
  Java; VM; Vendor        = 21; OpenJDK 64-Bit Server VM 21+35-2513; Oracle Corporation
  Runtime                 = OpenJDK Runtime Environment 21+35-2513
  Java Home               = /Users/thurka/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
```

**Comment by fwcd** [comment]
Hm, that's strange, perhaps the issue only occurs on Apple Silicon/arm64 Macs?

**Comment by sdavids** [comment]
I have the same problem:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               java [10897]
Path:                  /Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/bin/java
Identifier:            java
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        bash [10787]
User ID:               501

Date/Time:             2023-10-05 14:42:18.0807 +0200
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        C4681EC2-6242-F697-8752-AA7EFD28A6B8


Time Awake Since Boot: 28000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001889c961c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [10897]

Application Specific Information:
References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.
```

```shell
$ sw_vers
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
$ uname -a
Darwin dev 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
$ java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment Homebrew (build 21)
OpenJDK 64-Bit Server VM Homebrew (build 21, mixed mode, sharing)
$ /usr/libexec/PlistBuddy -c "Print:CFBundleName" -c "Print:CFBundleVersion" /Applications/VisualVM.app/Contents/Info.plist
VisualVM
2.1.7
```

**Comment by Jag026** [comment]
I got this error running jmeter and was able to resolve it by updating Java. You may also need to set the JAVA_HOME variable, I created a temporary session for jmeter (you'll need to change this to the application you're using): export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter

**Comment by caizixian** [comment]
I had the same error. The VisualVM launch script selects the Homebrew OpenJDK.

```
/opt/homebrew/Cellar/openjdk/21/libexec/openjdk.jdk/Contents/Home/bin/java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment Homebrew (build 21)
OpenJDK 64-Bit Server VM Homebrew (build 21, mixed mode, sharing)
```

I workaround the problem by using Temurin 8.
`visualvm_jdkhome=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/ /Applications/VisualVM.app/Contents/MacOS/visualvm`

**Comment by caizixian** [comment]
Temurin 17 and 21 are also fine (installed through Homebrew Cask). But not the normal Homebrew `openjdk`.

**Comment by caizixian** [comment]
So this could be a Homebrew `openjdk` formula problem.

**Comment by thurka** [comment]
So it looks like the Homebrew JDK is incorrectly built.

**Comment by thurka** [comment]
It is now clear that this not VisualVM issue. Closing.

**Comment by andrewserff** [comment]
In case anyone else is running into this issue with other applications (It was affecting NetBeans for me), I found the solution in this issue on a different project: https://github.com/apache/jmeter/issues/6083. Ultimately the solution was to use a different distribution of OpenJDK. [Amazon Corretto](https://aws.amazon.com/corretto/) seems to work (at least for NetBeans).

**Comment by b005t3r** [comment]
> In case anyone else is running into this issue with other applications (It was affecting NetBeans for me), I found the solution in this issue on a different project: [apache/jmeter#6083](https://github.com/apache/jmeter/issues/6083). Ultimately the solution was to use a different distribution of OpenJDK. [Amazon Corretto](https://aws.amazon.com/corretto/) seems to work (at least for NetBeans).

That's definitely not the ultimate solution. I just tried the Amazon JDK and it does not fix the crash for me (it's a crash in my macOS app).

**Comment by r0k3tkutt3r** [comment]
I don't think this is simply for Homebrew since I also had this issue in MCreator (A Java-based minecraft mod creator)

**Comment by yusufyilmazfr** [comment]
> I had the same error. The VisualVM launch script selects the Homebrew OpenJDK.
> 
> ```
> /opt/homebrew/Cellar/openjdk/21/libexec/openjdk.jdk/Contents/Home/bin/java -version
> openjdk version "21" 2023-09-19
> OpenJDK Runtime Environment Homebrew (build 21)
> OpenJDK 64-Bit Server VM Homebrew (build 21, mixed mode, sharing)
> ```
> 
> I workaround the problem by using Temurin 8. `visualvm_jdkhome=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/ /Applications/VisualVM.app/Contents/MacOS/visualvm`

You're awesome @caizixian! ❤️ You've saved my time, i've spending 2 days for this problem.
