### ISSUE TITLE
Sort threads by name is incorrect

### ISSUE THREAD

**Issue by chdw** [oracle/visualvm#529]
Sort threads by name is incorrect

1. Take a heap dump file
2. Open heap dump file
3. Switch the main panel to "Threads" 
4. Click the table column "Name"
5. But the Thread name is not sort by name!

**Screenshots**
![20231018111850](https://github.com/oracle/visualvm/assets/1484407/c7d32f38-5286-4401-9e6b-b06c64361eed)

**Desktop (please complete the following information):**
 - OS:  MacOS
 - JDK version [JDK 1.8.0_181]
 - Version 2.1.7

**Comment by thurka** [comment]
Thanks for the bug report. I am able to reproduce it.

**Comment by thurka** [comment]
Fixed in master.
