### ISSUE TITLE
Additional File in HeapViewer's hwcache on Windows

### ISSUE THREAD

**Issue by jisedlac** [oracle/visualvm#530]
Once all metadata (references, retained sizes, etc.) for a heapdump are computed, the corresponding `hwcache` folder contains the following files:
```
NBProfiler.nphd
NBProfiler<number>.map
NBProfiler<number>.ref
```
However, on Windows there's an extra `.gc` file in this folder:
```
NBProfiler.nphd
NBProfiler<number>.gc
NBProfiler<number>.ref
NBProfiler<number>.map
```
Based on the implementation details, this file is not needed and should be deleted.

**Comment by thurka** [comment]
Fixed in master.
