### ISSUE TITLE
find string

### ISSUE THREAD

**Issue by spiritwindy** [oracle/visualvm#532]
I want to find a string or a character array in a snapshot and find the reference to this object

**Comment by thurka** [comment]
When you said 'find in snapshot', do you mean heap dump? If yes, you can use OQL to find find a string or a character array in heap dump. OQL documentation is available [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/visualvm/visualvm.java.net.backup/master/www/oqlhelp.html).
