### ISSUE TITLE
Mac OS distribution — missing CFBundleIdentifier

### ISSUE THREAD

**Issue by odisseus** [oracle/visualvm#535]
**Describe the bug**
The Info.plist file of the VisualVM bundle doesn’t have the `CFBundleIdentifier` field, which is [required](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier) by the specification.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and install VisualVM.
2. `cat /Applications/VisualVM.app/Contents/Info.plist | grep CFBundleIdentifier -A 1`

**Expected behavior**
The above command should print a the value of `CFBundleIdentifier`.

**Desktop (please complete the following information):**
 - OS: MacOS
 - JDK version [JDK 1.8.0_181]
 - Version 2.1.5, 2.1.7

**Comment by thurka** [comment]
You are right. It will be fixed in the next release.

**Comment by thurka** [comment]
It should be fixed in VisualVM 2.1.8.
