### ISSUE TITLE
Make thread view collapsable in heapViewer

### ISSUE THREAD

**Issue by TimKack** [oracle/visualvm#55]
Here is a feature request: I normally work with heaps containing 500-800 threads.
It is quite cumbersome to manually collapse the all the thread manually.
It would be fantastic to have a "Collapse all / Expand all" right-click menu option to collapse all the threads in the treeviews.
I.e. from this
![pleasecollapse](https://user-images.githubusercontent.com/1034172/35141039-ccfd2436-fcf9-11e7-8942-44902d4bf006.png)
to this:
![collapsedthreads](https://user-images.githubusercontent.com/1034172/35141041-d1f779c8-fcf9-11e7-96e2-316b2932dbc8.png)

I know that this is possible by selecting "Threads" in the breadcrumb - but it is not intuitive

**Comment by jisedlac** [comment]
Thanks for the tip! Implemented in master - added 'Expand All Threads' and 'Collapse All Threads' actions to the context menu. Enabling Filter for this view might also be useful.
