### ISSUE TITLE
Version of OpenJDK is not supported. Please use the default-jdk.

### ISSUE THREAD

**Issue by thmasker** [oracle/visualvm#558]
Trying to open VisualVM outputs following error:

**VisualVM log**
`Version of OpenJDK is not supported. Please use the default-jdk.`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04.3 LTS

**Additional context**
`java -version` outputs:
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)
```

and `$JAVA_HOME` is `/usr/lib/jvm/java-17-openjdk-amd64`

**Comment by thurka** [comment]
What version of VisualVM do you use? How you 'open' the VisualVM? Can you please post the whole output from terminal.

**Comment by thmasker** [comment]
I write `visualvm` in the terminal, and the whole output is exactly what I put:
`Version of OpenJDK is not supported. Please use the default-jdk.`

I've tested it with several versions of VisualVM, including 2.06, and the latest: 2.1.7

**Comment by thmasker** [comment]
I've also tried that. Same error is obtained

**Comment by thurka** [comment]
Can you try use absolute path for `visualvm`?

**Comment by thmasker** [comment]
you mean like `/usr/bin/visualvm --jdkhome /usr/lib/jvm/java-17-openjdk-amd64`? Tried it with and without `--jdkhome`. Same output error

**Comment by thurka** [comment]
Hmm, this is strange. That error is not part of VisualVM sources. Where did you get VisualVM from? Please try the following: 

1. download VisualVM 2.1.7 from https://visualvm.github.io
2. unzip it to `/tmp`
3. run it with `/tmp/visualvm_217/bin/visualvm --jdkhome /usr/lib/jvm/java-17-openjdk-amd64`

**Comment by thmasker** [comment]
Well I'm seeing exactly this error message on `/usr/bin/visualvm` line 87... Anyway the steps you just gave me worked

**Comment by thmasker** [comment]
I installed it via apt

**Comment by thurka** [comment]
I see. Unfortunately we cannot control what is installed by `apt-get install visualvm`. This is probably not the original visualvm version and it looks like the visualvm launcher script was modified. If in doubt, please use version from https://visualvm.github.io/
Thanks.

**Comment by thmasker** [comment]
Ok, then. Thank you!
