### ISSUE TITLE
Not able to open large heap dump files

### ISSUE THREAD

**Issue by sarthak77** [oracle/visualvm#568]
**Describe the bug**
Not able to open large [ ~8GB ] heap dump files. 

**To Reproduce**
- Download visualvm from https://visualvm.github.io/download.html
- Try opening a large heap dump

**Expected behavior**
Expectation was that some dump analysis would show up on the UI

**VisualVM log**
No log as such. Jut the upload file process takes a lot of time making it unusable

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [Mac M1 Pro]
 - JDK version [JDK 11.0.11]
 - Version [e.g. 2.1.8]

**Additional context**
NA

**Comment by thurka** [comment]
Please attach the messages.log, which is  available via VisualVM | About VisualVM | Logfile.
Thanks.

**Comment by sarthak77** [comment]
Hi @thurka !!
There is no error as such. Just the file upload takes a lot of time. Should I attach log file in that case as well?

**Comment by thurka** [comment]
Yes, please attach log file.

**Comment by sarthak77** [comment]
[logfile.txt](https://github.com/oracle/visualvm/files/15060556/logfile.txt)

**Comment by sarthak77** [comment]
```
(base) ➜  ~/Desktop file /usr/local/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home/bin/java

/usr/local/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home/bin/java: Mach-O 64-bit executable x86_64
```

**Comment by thurka** [comment]
Ok, this confirms my suspission that you are running **Intel (x86_64)** version of JDK on Mac M1 Pro. Please install JDK with correct architecture. Intel version is run using [Rosseta 2](https://en.wikipedia.org/wiki/Rosetta_(software)) and is obviously slower than running AArch64 version.

**Comment by sarthak77** [comment]
Ok. Let me try with that.
