### ISSUE TITLE
VSCode Extension - add custom cpu profiler filter

### ISSUE THREAD

**Issue by shoblingr** [oracle/visualvm#570]
Thanks for the new VSCode extension for VisualVM integration! It works quiet well :).

It would be nice if we could have custom class filtering in cpu filtering to focus a special package, for instance 'com.she.utils.**'

Regards,

Stephane

**Comment by jisedlac** [comment]
Thank you for your feedback! Persisting a custom filter in context of a VS Code project makes a lot of sense.

**Comment by jisedlac** [comment]
Implemented.
