### ISSUE TITLE
Compatible with JDK 9 or not ?

### ISSUE THREAD

**Issue by DhiralKaniya** [oracle/visualvm#58]
I installed JDK 9 and visualvm from the terminal. I have set jdk path and usrdir parth in visualvm.config from usr/share/visualvm/etc/ but not able to open it.

**Comment by thurka** [comment]
JDK 9 is supported. See [VisualVM 1.4 release notes](https://visualvm.github.io/relnotes.html).

You need to provide more information. Please run visualvm from terminal with:
`/usr/share/visualvm/bin/visualvm -J-Dnetbeans.logger.console=true`
and attach the output from terminal. BTW: There is no need to modify "usrdir parth in visualvm.config"

**Comment by thurka** [comment]
Closing until more info is available.
