### ISSUE TITLE
JDBC sampler is gone

### ISSUE THREAD

**Issue by maciejmiklas** [oracle/visualvm#580]
**Describe the bug**
Tab Sampler contains only: CPU, Memory, Stop

JDBC is missing

**To Reproduce**
Donwload the verson 2.1.8 connect to java process.

**Expected behavior**
JDBC should be there

**VisualVM log**
Please attach VisualVM messages.log file to help diagnose your problem.

messages.log is available via Help | About | Logfile and
via VisualVM | About VisualVM | Logfile on macOS

**Screenshots**
<img width="997" alt="image" src="https://github.com/oracle/visualvm/assets/3326660/6010b814-b889-40da-8389-7c35655e0039">

**Desktop (please complete the following information):**
 - OS: Mac OS 14.5 (23F79)
 -  Boundle 
 - Version 2.1.8

**Additional context**
-

**Comment by thurka** [comment]
JDBC was never in Sampler tab. It was and it is available in Profiler tab.
