### ISSUE TITLE
Use visualvm 2.1.8 to open visual gc to display "Not supported for this JVM"

### ISSUE THREAD

**Issue by sititch** [oracle/visualvm#586]
The remote connection "Monitor" is no problem, you can see the data, but visual gc can not display it
<img width="1248" alt="image" src="https://github.com/oracle/visualvm/assets/39956341/52cfd395-4574-4ab7-a6d7-35d79f3b9d96">
<img width="939" alt="image" src="https://github.com/oracle/visualvm/assets/39956341/2ad68735-1695-4476-910b-3ec4074405cf">
[root@localhost pmce]# java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
[root@localhost pmce]#

**Comment by thurka** [comment]
Please provide steps to reproduce.

**Comment by sititch** [comment]
> Please provide steps to reproduce

I don't quite understand

**Comment by thurka** [comment]
If you file this issue here: https://github.com/oracle/visualvm/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

There is a section 'To Reproduce' - you didn't fill out this part.
