### ISSUE TITLE
The retained size of arrays does not include the retained size of it's elements

### ISSUE THREAD

**Issue by jukzi** [oracle/visualvm#589]
The retained size of an Object should be explained by the sum of its fields but it does not. Example:
![image](https://github.com/oracle/visualvm/assets/51790620/f12e5fcf-153a-430b-a547-47a1916f2cd1)
Here one has to guess that an array field is causing the retained size:
The member itself shows only a retained size equal to its (shallow) size - neglecting  its elements:
![image](https://github.com/oracle/visualvm/assets/51790620/04853890-61c2-450e-8945-5133336dadf6)

**Comment by thurka** [comment]
> The retained size of an Object should be explained by the sum of its fields but it does not.

This is not true. The definition of retained size is completly different. Retained size of the object is the amount of heap memory that will be freed when the object is garbage collected.

**Comment by jukzi** [comment]
> will be freed when the object is garbage collected.

The array elements will be garbage collected when their root is collected. the root of the elements is the array!
![image](https://github.com/oracle/visualvm/assets/51790620/adc29e92-3cdc-4f8a-966b-d1d2d9d98141)

**Comment by thurka** [comment]
> The array elements will be garbage collected when their root is collected.

No, this is not true. You need to go through all childred of all elements recursively and verify that there's no other way to the GC root.
