### ISSUE TITLE
VSCode Extension - Source Roots don't work in VSCode extension

### ISSUE THREAD

**Issue by Trass3r** [oracle/visualvm#598]
It's a multi-root workspace fwiw. And the `Java: List All Java Source Paths` command lists all paths properly.
Yet it only calls VisualVM with the jdk root:

```sh
[info] [visualvm] Starting VisualVM
[info] [visualvm] Found defined installation path: c:\VisualVM
[info] [visualvm] VisualVM executable found in standard installation: c:\VisualVM\bin\visualvm.exe
[info] [visualvm] Found valid executable: c:\VisualVM\bin\visualvm.exe
[info] [visualvm] Found valid org-graalvm-visualvm-gotosource.jar: c:\VisualVM\visualvm\modules\org-graalvm-visualvm-gotosource.jar
[info] [jdk] Getting a JDK
[info] [jdk] Resolved path for setting netbeans.jdkhome: c:\GraalVM
[info] [jdk] Verified path for setting netbeans.jdkhome: c:\GraalVM
[info] [jdk] Getting a JDK
[info] [jdk] Resolved path for setting netbeans.jdkhome: c:\GraalVM
[info] [jdk] Verified path for setting netbeans.jdkhome: c:\GraalVM
[info] [visualvm] Command: c:\VisualVM\bin\visualvm.exe -J-XX:PerfMaxStringConstLength=10240 --jdkhome "c:\GraalVM" --source-viewer="%22C:\Users\...\AppData\Local\Programs\Microsoft%20VS%20Code\bin\code.cmd%22 -g {file}:{line}:{column}" --source-roots="c:\GraalVM\lib\src.zip[subpaths=*modules*]" --window-to-front
```

Any hints at how to find out what's wrong?

**Comment by Trass3r** [comment]
I've already tried to open one of the folders in the workspace on its own, but that didn't change anything.
Now I created a fresh vscode profile and [set up the basics](https://code.visualstudio.com/docs/java/java-spring-boot) for testing. Extension Pack for Java, Spring stuff, VisualVM, GraalVM 17.0.12. Of course it worked.
Then I moved the code into a subfolder and it stopped working. So this should be the problem.

**Comment by jisedlac** [comment]
Thank you for the test code! I'm now able to reproduce the problem. Obviously the solution is to open the actual project folder directly containing `pom.xml`.

I'll try to improve the current implementation to find the source roots in nested folders to be consistent with the VS Code Java support.

**Comment by Trass3r** [comment]
Thanks! Yeah `Java: List All Java Source Paths` finds the paths correctly in all cases.

**Comment by jisedlac** [comment]
Fixed in master.
