### ISSUE TITLE
[RFC] provide option to disable auto connect JMX when VisualVM start

### ISSUE THREAD

**Issue by missedone** [oracle/visualvm#6]
hi folks
I have several remote servers managed in VisualVM, and each has a JMX connection.
every time I start VisualVM, it tries to reconnect the JMX which make the start really slow and not responding for a quite long while.

the workaround for now is to delete the JMX connection before close VisualVM, and re-add next time.

so could you provide an option to disable this auto JMX connect.
thanks

**Comment by woj-tek** [comment]
Highly needed. It makes startup very slow and quite often we don't need to connect to all configured entries (I consider them sort of bookmarks to quickly connect to defined servers).

**Comment by jisedlac** [comment]
JMX connections now behave as bookmarks - you can either connect/disconnect manually using a context menu action or enable automatic connection whenever the target is available.

First available in VisualVM 2.0.1.
