### ISSUE TITLE
Display 'Average Time' as a column similar to 'Total Time'

### ISSUE THREAD

**Issue by m4mukulgarg** [oracle/visualvm#606]
**Is your feature request related to a problem? Please describe.**
I have to mentally calculate the average time for each thread/query executed

**Describe the solution you'd like**
A new column in the profiling results tab where I can see the average time (calculated as total_time/invocations) is displayed for each row
 
**Describe alternatives you've considered**
Mentally calculating the results.

**Additional context**
![image](https://github.com/user-attachments/assets/ccd0eb49-2a38-4f4c-bada-b299dbcba5fe)

**Comment by thurka** [comment]
Done in master. New 'Average Time' column was added. It is hidden by default.
