### ISSUE TITLE
Jumping charts

### ISSUE THREAD

**Issue by oshyshko** [oracle/visualvm#61]
VisualVM `1.4 (Build 171211)`.
OS X `10.12.6`.

Notice, how the chart after 3:45pm jumps back and forth: `-`, `\`, `/`

![image](https://user-images.githubusercontent.com/73026/35891069-42f9bfd0-0b57-11e8-92b4-18db47b9bea3.png)

![image](https://user-images.githubusercontent.com/73026/35891094-593b2eb4-0b57-11e8-9f77-ad67cf6ffc0c.png)

![image](https://user-images.githubusercontent.com/73026/35891114-795821f2-0b57-11e8-984a-8daa4f49fcb2.png)

**Comment by jisedlac** [comment]
This actually works as designed. For performance reasons the charts use "sampling" - one of the values for a given pixel is picked and rendered. In your case, there are many different values on both sides of the line and based on which of them are currently used for rendering, the line appears as - or \ or /.

To get more details on values in the area in question, take an Application Snapshot of the process and use zoom feature in the snapshot charts (not available for live charts).

**Comment by jisedlac** [comment]
Revised, fixed.
