### ISSUE TITLE
[HeapWalker] java.lang.OutOfMemoryError: Map failed

### ISSUE THREAD

**Issue by thurka** [oracle/visualvm#67]
Computing references of the heap fails with java.lang.OutOfMemoryError: Map failed
Steps to reproduce:

1. Start VisualVM on 32bit JDK. 
2. Open large (>1G) heap dump.
3. Compute references
4. At the end of references computation `java.lang.OutOfMemoryError: Map failed` is thrown.

See attached [messages.log](https://github.com/oracle/visualvm/files/1747204/messages.log) for full stacktrace.

**Comment by blandger** [comment]
I'm confirming OoM, but head dump is too big to attache here.

**Comment by blandger** [comment]
[messages.log](https://github.com/oracle/visualvm/files/1867983/messages.log)

**Comment by thurka** [comment]
Fixed in VisualVM 1.4.1

**Comment by thurka** [comment]
Fixed in master [a5fbca4](https://github.com/oracle/visualvm/commit/a5fbca468b96777828a3433290112024462962e7).
