### ISSUE TITLE
Error on opening jvisualvm

### ISSUE THREAD

**Issue by zieshen** [oracle/visualvm#68]
Getting error "Not a NPSS snapshot." while opening jvisualvm and not opening.Can see only icon on status bar no window.

Java: jdk1.8.0_101

**Comment by thurka** [comment]
It looks like you are trying to open file, which is not NPSS file. Can you please run VisualVM from command line with the following option:
`jvisualvm -J-Dnetbeans.logger.console=true`
and attach the log from your console? Thanks.

**Comment by thurka** [comment]
Closing until more information is available.
