### ISSUE TITLE
NullPointerException when starting with eclipse Launcher

### ISSUE THREAD

**Issue by DaGeRe** [oracle/visualvm#7]
When I start an arbitrary main or an JUnit-Test with the VisualVM launcher, I always get an NullPointerException:

An internal error occurred during: "Launching BenchmarkTest".
java.lang.NullPointerException

Unfortunately, that is the only output that I receive. Is there a workaround for this?

I've set in Preferences -> Run/Debug -> Launching -> VisualVM Configuration VisualVM executable to /usr/bin/visualvm and JDK Home to /usr/lib/jvm/java-8-openjdk-amd64, and I am using Ubuntu 16.10.

**Comment by bagage** [comment]
Facing the same issue; @DaGeRe did you manage to make it work?

**Comment by buzden** [comment]
I'm facing the same problem.

The local reason I see is that [VisualVMHelper](https://github.com/oracle/visualvm/blob/master/integrations/eclipse/org.eclipse.visualvm.launcher.common/src/org/eclipse/visualvm/launcher/api/VisualVMHelper.java) does not manage with `null` at the line 105.

The global reason I see is that they are trying to read closed stdout and stderr streams of the finished process.

**Comment by thurka** [comment]
Fixed in Eclipse Launcher for VisualVM 1.4
