### ISSUE TITLE
When loading 'Tracer-JavaFX Probes' plugin, no other probes are loaded

### ISSUE THREAD

**Issue by dragetd** [oracle/visualvm#74]
When loading the 'Tracer-JavaFX Probes' plugin into VisualVM 1.4, I no longer see any other tracer probes or just a very limited set listed in the tracer tab.

It seems like the JavaFX plugin is crashing or doing something that prevents further probes from being loaded so only the first plugins are loaded. When deactivating the plugin, I see all the other probes again.

**Comment by thurka** [comment]
The problem with JavaFX tracer plugin can be seen in VisualVM log file. It is accessible via Help->About->Logfile.
[messages.log](https://github.com/oracle/visualvm/files/1880036/messages.log)

**Comment by thurka** [comment]
The JavaFX probes fails with:
`javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 26`

**Comment by thurka** [comment]
Fixed in [master](https://github.com/oracle/visualvm/commit/d6a87885fc6b414297435bfc7dfee41a02dc1d1a).
