### ISSUE TITLE
automatically install plugins

### ISSUE THREAD

**Issue by moaxcp** [oracle/visualvm#77]
Is it possible to automatically install plugins? I would like to update the nixos install to add plugins using the nix language. I found some information to do this for netbeans but I don't think it would work. http://wiki.netbeans.org/FaqSilentInstallationNBPlugin. Any ideas?

**Comment by thurka** [comment]
@moaxcp I have an idea - try to use information how to do this for netbeans. Why do you think it will not work?

**Comment by moaxcp** [comment]
Ok is the page still accurate? Which cluster do I put the files under? Do they all go under profiler or visualvm? Or is it specific to each plugin?

Also I'm not sure about accessing the netbeans userdir. Is this where the plugins get saved? Or can the plugins be installed at the system level for all users. Does the command need to be run once per user?

**Comment by thurka** [comment]
> Ok is the page still accurate? 

I guess it is.

> Which cluster do I put the files under? Do they all go under profiler or visualvm? Or is it specific to each plugin?

Use visualvm cluster.

> Also I'm not sure about accessing the netbeans userdir. Is this where the plugins get saved? 

Yes, normally plugins are saved to userdir.

> Or can the plugins be installed at the system level for all users. 

Yes, it can. The setting is at Tools->Plugins->Settings->Plugin install Location

> Does the command need to be run once per user?

Yes, is does.
