### ISSUE TITLE
Profiling a single class taking extraordinarily long time

### ISSUE THREAD

**Issue by exabrial** [oracle/visualvm#78]
I put a single class from my application (< 200 LOC, 15 methods that do nothing but interaction with collections and some reflection) into the profiler roots box, and in the "Profile Only Class" I put that class's package. Profile new runnables is unchecked.

VisualVM is taking a massive amount of time at the "profiler busy" progress bar. I have a feeling that the class filter is not working properly. JDK 1.8 latest with latest visualvm distribution

**Comment by jisedlac** [comment]
Hi, thanks for submitting the bug report! Could you please share the profiler settings - ideally attach a screenshot of the Profiler tab with the CPU settings visible.

I assume you're using the Java VisualVM tool bundled in your JDK 1.8. Could you please try the most recent VisualVM version from GitHub (http://visualvm.github.io/download.html) if it makes any difference?

**Comment by thurka** [comment]
Closing until more info is available.
