### ISSUE TITLE
On connecting to jstatd "10" prepended to host ip

### ISSUE THREAD

**Issue by flyasky** [oracle/visualvm#79]
I try connect  to jstatd on remote

I got error and in see next lines in log:

```
INFO [com.sun.tools.visualvm.jvmstat.application.JvmstatApplicationProvider]: Jvmstat connection to rt-sth-kvm-sdp01 [IP: 192.168.217.180] failed.
java.net.UnknownHostException: 10192.168.217.180
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:221)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)

```
Why "10" is prepended?

VisualVM 1.4 was donloaded from site today.

**Comment by jisedlac** [comment]
I haven't found any problem in VisualVM implementation. Please doublecheck a typo on your side.

In case you're still experiencing the problem, please provide detailed steps to reproduce it & full VisualVM logfile.

**Comment by thurka** [comment]
Closing until more information is available.
