### ISSUE TITLE
Why can't I find the btrace tab

### ISSUE THREAD

**Issue by kdyzm** [oracle/visualvm#87]
As the title shows, I can't find the btrace tab. The java version is 1.8.0_77.All plugins I have installed, where am I wrong?

![image](https://user-images.githubusercontent.com/12097910/39960191-e49a1008-5650-11e8-9c31-e126286aed43.png)

![image](https://user-images.githubusercontent.com/12097910/39960162-59a23f16-5650-11e8-9ee2-2e803fbba6bd.png)

**Comment by thurka** [comment]
Right-click on 'com.kdyzm.jvm04..' application and select 'Trace Application...'
