### ISSUE TITLE
Also display PID if application specifies a custom display name

### ISSUE THREAD

**Issue by richardfearn** [oracle/visualvm#89]
An application can specify `-Dvisualvm.display.name=some-name` to specify a custom name to be displayed in the "Applications" panel in VisualVM. If a display name is specified, VisualVM doesn't include the PID in brackets after the name.

Always including the PID would make it easier to distinguish between different instances of the same application.

**Comment by perlun** [comment]
@richardfearn Nice improvement! Do you intend to submit  your patch as a PR to the main repo?

**Comment by richardfearn** [comment]
@perlun #90 is the PR. Originally the commit was a6f91c8 which changed `com.sun.tools.visualvm.application.ApplicationDescriptor`. Later the packages were renamed so I pushed 4a2a823 which changes `org.graalvm.visualvm.application.ApplicationDescriptor`.

**Comment by jisedlac** [comment]
Introduced two parameters to format the `visualvm.display.name`:

`%pid` - replaced by the process ID number (like "12345") or "unknown" where not available

`%PID` - replaced by "(pid 12345)" and leading/trailing space as needed

The typical usage is `java -Dvisualvm.display.name=CustomProcess%PID -jar CustomProcess.jar` which produces similar output as the VisualVM default: "CustomProcess (pid 12345)".

Should also work for user-defined display names of JMX connections, including Rename.

**Comment by perlun** [comment]
Thanks @jisedlac, much appreciated! Is it still impossible to have a space in the display name? I tried that and noticed that it doesn't work since the code would only take the name until the next space in the provided list of arguments. Is this still the case?

(It's not a huge issue, more like a slight annoyance.)

**Comment by jisedlac** [comment]
You're right, space in display name doesn't work, caused by the underlying NetBeans platform. Could be workarounded by adding another %parameter to be replaced by space, but I believe the current state is perfectly OK for the desired use case.
