### ISSUE TITLE
Heap graph: detalize heap by region: old and eden

### ISSUE THREAD

**Issue by stokito** [oracle/visualvm#95]
Graph of heap usage shows all consumed memory but it's not clear if new or old region was used.
I have an application which uses a gibibytes of old memory but only mibibytes of eden space.
I figured out this only when installed Visual GC plugin which shows detailed graph by region. 
Is it possible to show on monitor heap graph a separate line with new memory?

**Comment by thurka** [comment]
You already find out that Visual GC plugin plugin provides this info, so why don't you use it?

**Comment by stokito** [comment]
I'm using it, just wanted to see this on a main heap graph. Closing the issue

**Comment by thurka** [comment]
The monitoring view (which also contains other metrics) provides only global info about java process. We would like to have there only simple info, which is easy to understand my majority of the users. For those, who need more detailed info about heap, there is VisualGC plugin.
