### ISSUE TITLE
Thread state is WAIT instead of PARK when monitoring Java 9+ application

### ISSUE THREAD

**Issue by cowwoc** [oracle/visualvm#96]
Version 1.4.1

I am running an instance of VisualVM and attaching it to the same application, one time running under Java 8 and later running under Java 10. When running under Java 8 I see the thread state as PARK most of the time. When I run under Java 10, those same threads show up as WAIT most of the time time. I never see PARK used under Java 10.

Is this a bug in VisualVM or does Java 10 never use PARK anymore?

**Comment by thurka** [comment]
Detection of 'park' thread state does not work for JDK 9+ due to substantial changes in JDK 9.

**Comment by thurka** [comment]
Fixed in master [5e36af0](https://github.com/oracle/visualvm/commit/5e36af0992015e3397745a205ade8a2154c7ba90).
